// GENERATO da strumenti/sprite/roba.py --gioco dal catalogo roba.json: non si scrive a mano.
// Le figure che può avere un pezzo trovato, per base: la tinta (l'elemento che la figura richiama) e il pregio
// (1 da bottega, 4 da leggenda). Chi sceglie è aspettoDi in dati/cose.js (docs/sotterraneo/figure.md)
export const ASPETTI = {
  'spada': [
    { sprite: 'spada-01', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-02', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-03', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'spada-04', tinta: 'natura', pregio: 2 },
    { sprite: 'spada-05', tinta: 'fuoco', pregio: 2 },
    { sprite: 'spada-06', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-12', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'spada-13', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-14', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-15', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-17', tinta: 'natura', pregio: 3 },
    { sprite: 'spada-19', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-20', tinta: 'veleno', pregio: 2 },
    { sprite: 'spada-21', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-22', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'spada-23', tinta: 'ombra', pregio: 3 },
    { sprite: 'spada-24', tinta: 'luce', pregio: 2 },
    { sprite: 'spada', tinta: 'natura', pregio: 3 },
    { sprite: 'spada-27', tinta: 'sangue', pregio: 3 },
    { sprite: 'spada-28', tinta: 'fuoco', pregio: 3 },
  ],
  'spada-corta': [
    { sprite: 'spada-08', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-09', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-10', tinta: 'luce', pregio: 3 },
    { sprite: 'spada-corta', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-33', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-34', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-35', tinta: 'ombra', pregio: 2 },
  ],
  'spadone': [
    { sprite: 'spada-11', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'spadone', tinta: 'oro', pregio: 3 },
    { sprite: 'spada-36', tinta: 'arcano', pregio: 3 },
  ],
  'ascia': [
    { sprite: 'spada-30', tinta: 'nessuno', pregio: 1 },
    { sprite: 'spada-31', tinta: 'nessuno', pregio: 2 },
    { sprite: 'spada-32', tinta: 'nessuno', pregio: 2 },
    { sprite: 'ascia', tinta: 'nessuno', pregio: 3 },
    { sprite: 'ascia-05', tinta: 'nessuno', pregio: 1 },
    { sprite: 'ascia-06', tinta: 'nessuno', pregio: 1 },
    { sprite: 'ascia-07', tinta: 'nessuno', pregio: 2 },
  ],
  'accetta': [
    { sprite: 'accetta', tinta: 'nessuno', pregio: 2 },
  ],
  'bipenne': [
    { sprite: 'bipenne', tinta: 'nessuno', pregio: 3 },
  ],
  'arco-corto': [
    { sprite: 'arco-corto', tinta: 'nessuno', pregio: 1 },
    { sprite: 'arco-04', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'arco-05', tinta: 'natura', pregio: 3 },
  ],
  'arco-lungo': [
    { sprite: 'arco-02', tinta: 'nessuno', pregio: 1 },
    { sprite: 'arco-lungo', tinta: 'nessuno', pregio: 2 },
  ],
  'balestra': [
    { sprite: 'balestra', tinta: 'ombra', pregio: 3 },
  ],
  'scettro': [
    { sprite: 'bastone-01', tinta: 'acqua', pregio: 3 },
    { sprite: 'bastone-19', tinta: 'arcano', pregio: 3 },
    { sprite: 'bastone-21', tinta: 'sangue', pregio: 3 },
    { sprite: 'bastone-23', tinta: 'oro', pregio: 3 },
    { sprite: 'bastone-28', tinta: 'natura', pregio: 3 },
    { sprite: 'scettro', tinta: 'fuoco', pregio: 2 },
    { sprite: 'bastone-48', tinta: 'arcano', pregio: 3 },
  ],
  'bastone-magico': [
    { sprite: 'bastone-02', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'bastone-03', tinta: 'natura', pregio: 2 },
    { sprite: 'bastone-04', tinta: 'ombra', pregio: 2 },
    { sprite: 'bastone-05', tinta: 'fuoco', pregio: 3 },
    { sprite: 'bastone-06', tinta: 'arcano', pregio: 3 },
    { sprite: 'bastone-07', tinta: 'arcano', pregio: 2 },
    { sprite: 'bastone-08', tinta: 'fuoco', pregio: 3 },
    { sprite: 'bastone-09', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-10', tinta: 'arcano', pregio: 3 },
    { sprite: 'bastone-11', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-12', tinta: 'fuoco', pregio: 2 },
    { sprite: 'bastone-15', tinta: 'acqua', pregio: 2 },
    { sprite: 'bastone-16', tinta: 'acqua', pregio: 2 },
    { sprite: 'bastone-17', tinta: 'luce', pregio: 2 },
    { sprite: 'bastone-18', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-20', tinta: 'arcano', pregio: 4 },
    { sprite: 'bastone-25', tinta: 'luce', pregio: 3 },
    { sprite: 'bastone-26', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-27', tinta: 'acqua', pregio: 3 },
    { sprite: 'bastone-29', tinta: 'fuoco', pregio: 2 },
    { sprite: 'bastone-30', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-31', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-32', tinta: 'arcano', pregio: 2 },
    { sprite: 'bastone-33', tinta: 'fuoco', pregio: 3 },
    { sprite: 'bastone-34', tinta: 'luce', pregio: 3 },
    { sprite: 'bastone-magico', tinta: 'acqua', pregio: 2 },
    { sprite: 'bastone-37', tinta: 'natura', pregio: 2 },
    { sprite: 'bastone-38', tinta: 'veleno', pregio: 2 },
    { sprite: 'bastone-39', tinta: 'sangue', pregio: 3 },
    { sprite: 'bastone-40', tinta: 'arcano', pregio: 2 },
    { sprite: 'bastone-44', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'bastone-45', tinta: 'ombra', pregio: 3 },
    { sprite: 'bastone-47', tinta: 'ombra', pregio: 2 },
  ],
  'verga': [
    { sprite: 'bastone-22', tinta: 'natura', pregio: 2 },
    { sprite: 'verga', tinta: 'natura', pregio: 1 },
    { sprite: 'bastone-42', tinta: 'arcano', pregio: 2 },
  ],
  'corazza': [
    { sprite: 'corpo-piastre', tinta: 'nessuno', pregio: 2 },
    { sprite: 'veste-03', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'veste-04', tinta: 'nessuno', pregio: 1 },
    { sprite: 'veste-05', tinta: 'nessuno', pregio: 2 },
    { sprite: 'veste-06', tinta: 'luce', pregio: 4 },
    { sprite: 'veste-09', tinta: 'nessuno', pregio: 2 },
    { sprite: 'veste-10', tinta: 'luce', pregio: 2 },
    { sprite: 'veste-11', tinta: 'fuoco', pregio: 3 },
    { sprite: 'veste-12', tinta: 'ombra', pregio: 3 },
    { sprite: 'veste-13', tinta: 'ombra', pregio: 3 },
  ],
  'panciotto': [
    { sprite: 'veste-08', tinta: 'natura', pregio: 2 },
    { sprite: 'corpo-cuoio', tinta: 'nessuno', pregio: 1 },
    { sprite: 'veste-16', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'veste-18', tinta: 'fuoco', pregio: 2 },
  ],
  'saio': [
    { sprite: 'corpo-saio', tinta: 'luce', pregio: 1 },
    { sprite: 'veste-21', tinta: 'acqua', pregio: 2 },
    { sprite: 'veste-22', tinta: 'natura', pregio: 2 },
    { sprite: 'veste-25', tinta: 'arcano', pregio: 3 },
    { sprite: 'veste-26', tinta: 'luce', pregio: 3 },
    { sprite: 'veste-27', tinta: 'ombra', pregio: 2 },
    { sprite: 'veste-37', tinta: 'arcano', pregio: 4 },
  ],
  'manto': [
    { sprite: 'veste-17', tinta: 'natura', pregio: 1 },
    { sprite: 'veste-19', tinta: 'arcano', pregio: 2 },
    { sprite: 'veste-20', tinta: 'ombra', pregio: 2 },
    { sprite: 'veste-23', tinta: 'fuoco', pregio: 2 },
    { sprite: 'veste-24', tinta: 'acqua', pregio: 1 },
    { sprite: 'veste-28', tinta: 'luce', pregio: 3 },
    { sprite: 'corpo-manto', tinta: 'fuoco', pregio: 3 },
    { sprite: 'veste-30', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'veste-31', tinta: 'arcano', pregio: 3 },
    { sprite: 'veste-32', tinta: 'nessuno', pregio: 1 },
    { sprite: 'veste-33', tinta: 'nessuno', pregio: 1 },
    { sprite: 'veste-34', tinta: 'arcano', pregio: 2 },
    { sprite: 'veste-35', tinta: 'sangue', pregio: 2 },
    { sprite: 'veste-36', tinta: 'veleno', pregio: 2 },
    { sprite: 'veste-39', tinta: 'fuoco', pregio: 3 },
  ],
  'scudo-borchiato': [
    { sprite: 'scudo-01', tinta: 'nessuno', pregio: 1 },
    { sprite: 'scudo-02', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-borchiato', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-17', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-28', tinta: 'nessuno', pregio: 1 },
  ],
  'scudo-crociato': [
    { sprite: 'scudo-03', tinta: 'luce', pregio: 3 },
    { sprite: 'scudo-04', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-05', tinta: 'arcano', pregio: 2 },
    { sprite: 'scudo-07', tinta: 'luce', pregio: 2 },
    { sprite: 'scudo-08', tinta: 'natura', pregio: 3 },
    { sprite: 'scudo-10', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-13', tinta: 'arcano', pregio: 3 },
    { sprite: 'scudo-crociato', tinta: 'luce', pregio: 2 },
    { sprite: 'scudo-19', tinta: 'luce', pregio: 2 },
    { sprite: 'scudo-21', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-23', tinta: 'natura', pregio: 1 },
    { sprite: 'scudo-24', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-30', tinta: 'fuoco', pregio: 2 },
    { sprite: 'scudo-32', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-34', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-41', tinta: 'nessuno', pregio: 1 },
    { sprite: 'scudo-42', tinta: 'luce', pregio: 1 },
    { sprite: 'scudo-44', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-45', tinta: 'luce', pregio: 3 },
    { sprite: 'scudo-48', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-52', tinta: 'nessuno', pregio: 2 },
  ],
  'scudo-teschio': [
    { sprite: 'scudo-06', tinta: 'morte', pregio: 3 },
    { sprite: 'scudo-29', tinta: 'morte', pregio: 2 },
    { sprite: 'scudo-36', tinta: 'sangue', pregio: 2 },
    { sprite: 'scudo-38', tinta: 'morte', pregio: 3 },
    { sprite: 'scudo-40', tinta: 'morte', pregio: 3 },
    { sprite: 'scudo-teschio', tinta: 'veleno', pregio: 2 },
  ],
  'scudo-ferro': [
    { sprite: 'scudo-11', tinta: 'nessuno', pregio: 2 },
    { sprite: 'scudo-12', tinta: 'fuoco', pregio: 3 },
    { sprite: 'scudo-14', tinta: 'sangue', pregio: 3 },
    { sprite: 'scudo-25', tinta: 'ombra', pregio: 2 },
    { sprite: 'scudo-ferro', tinta: 'ombra', pregio: 2 },
    { sprite: 'scudo-27', tinta: 'luce', pregio: 3 },
    { sprite: 'scudo-33', tinta: 'fuoco', pregio: 3 },
    { sprite: 'scudo-35', tinta: 'ombra', pregio: 3 },
    { sprite: 'scudo-46', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'scudo-47', tinta: 'luce', pregio: 4 },
    { sprite: 'scudo-49', tinta: 'arcano', pregio: 3 },
    { sprite: 'scudo-50', tinta: 'arcano', pregio: 4 },
    { sprite: 'scudo-53', tinta: 'fuoco', pregio: 4 },
  ],
  'scudo-legno': [
    { sprite: 'scudo-legno', tinta: 'nessuno', pregio: 1 },
  ],
  'scudo-leone': [
    { sprite: 'scudo-leone', tinta: 'oro', pregio: 3 },
    { sprite: 'scudo-31', tinta: 'oro', pregio: 3 },
    { sprite: 'scudo-37', tinta: 'fuoco', pregio: 2 },
    { sprite: 'scudo-39', tinta: 'oro', pregio: 3 },
    { sprite: 'scudo-51', tinta: 'oro', pregio: 3 },
  ],
  'amuleto-rosso': [
    { sprite: 'amuleto-01', tinta: 'fuoco', pregio: 2 },
    { sprite: 'amuleto-13', tinta: 'fuoco', pregio: 1 },
    { sprite: 'amuleto-20', tinta: 'fuoco', pregio: 2 },
    { sprite: 'amuleto-22', tinta: 'sangue', pregio: 3 },
    { sprite: 'amuleto-31', tinta: 'sangue', pregio: 2 },
  ],
  'amuleto-azzurro': [
    { sprite: 'amuleto-02', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'amuleto-azzurro', tinta: 'ghiaccio', pregio: 3 },
    { sprite: 'amuleto-09', tinta: 'acqua', pregio: 3 },
    { sprite: 'amuleto-16', tinta: 'acqua', pregio: 2 },
    { sprite: 'amuleto-18', tinta: 'ghiaccio', pregio: 2 },
    { sprite: 'amuleto-25', tinta: 'acqua', pregio: 3 },
    { sprite: 'amuleto-28', tinta: 'ghiaccio', pregio: 3 },
  ],
  'medaglione': [
    { sprite: 'amuleto-03', tinta: 'natura', pregio: 2 },
    { sprite: 'amuleto-04', tinta: 'arcano', pregio: 2 },
    { sprite: 'amuleto-06', tinta: 'ombra', pregio: 2 },
    { sprite: 'amuleto-08', tinta: 'arcano', pregio: 4 },
    { sprite: 'amuleto-10', tinta: 'luce', pregio: 3 },
    { sprite: 'amuleto-11', tinta: 'luce', pregio: 3 },
    { sprite: 'amuleto-14', tinta: 'arcano', pregio: 3 },
    { sprite: 'amuleto-17', tinta: 'veleno', pregio: 2 },
    { sprite: 'amuleto-19', tinta: 'arcano', pregio: 2 },
    { sprite: 'amuleto-21', tinta: 'ombra', pregio: 3 },
    { sprite: 'amuleto-23', tinta: 'ombra', pregio: 3 },
    { sprite: 'amuleto-24', tinta: 'natura', pregio: 3 },
    { sprite: 'amuleto-26', tinta: 'natura', pregio: 3 },
    { sprite: 'amuleto-27', tinta: 'ombra', pregio: 2 },
    { sprite: 'amuleto-30', tinta: 'ombra', pregio: 3 },
    { sprite: 'amuleto-32', tinta: 'luce', pregio: 2 },
  ],
  'teschio-cercatore': [
    { sprite: 'amuleto-teschio', tinta: 'morte', pregio: 3 },
  ],
  'anello-ambra': [
    { sprite: 'anello-ambra', tinta: 'fuoco', pregio: 4 },
  ],
  'anello-verde': [
    { sprite: 'anello-verde', tinta: 'arcano', pregio: 4 },
  ],
}
