/* ═══════════════════════════════════════════════════════════════════
   LE CAMPAGNE DEL GENERALE, PER L'EDITOR — FILE GENERATO

   Non si scrive a mano: esce da `node strumenti/mappe/estrai-campagne.mjs`,
   che lo ricava da `src/data/campagne-generale.js`. Serve perché
   l'editor si apre da `file://`, dove un modulo ES non si carica.

   Rilancialo quando cambiano le tappe: il test `unita/mappe` confronta
   la firma e diventa rosso se questo file è di ieri.

   24 tappe, firma 3a140d334293.
   ═══════════════════════════════════════════════════════════════════ */
globalThis.CAMPAGNE_MAPPE = {
  firma: '3a140d334293',
  campagne: [
    {
      id: 'dungeon',
      nome: 'Il dungeon',
      emoji: '🏚️',
      sottotitolo: 'Quattro avventurieri, una scala che scende e nessuno che li richiama',
      tappe: [
        {
          id: 'scalinata',
          nome: 'La scalinata',
          idea: 'gli ordini si eseguono uno dopo l\'altro, dal primo all\'ultimo, e quello che non hai scritto non succede',
          cassetta: ['vai'],
          par: 4,
          dritta: 'Scrivi la fila di ordini e poi guarda. Una meta alla volta — il pianerottolo, la svolta, il fondo, la porta — e ricordati che quello che non hai scritto non succede.',
          n: 1,
          emoji: '🕯️',
          storia: 'Il dungeon è là sotto e la scalinata è l\'unica strada. Gli ordini si firmano qui in cima: più giù non si parla più.',
          concetto: {
            id: 'sequenza',
            nome: 'La fila',
            cosa: 'gli ordini si eseguono uno dopo l\'altro, dal primo all\'ultimo, e quello che non hai scritto non succede',
          },
          scartati: [],
          unita: 1,
          attori: ['mira'],
          nemico: null,
          scene: [
            'la scalinata al lume di torcia, dritta fino alla porta',
            'la stessa scalinata, con l\'acqua che gocciola dal soffitto',
            'la stessa scalinata, e un ratto che attraversa: non fa niente, ma si vede',
          ],
          haMappa: false,
        },
        {
          id: 'chiavistello',
          nome: 'Il chiavistello',
          idea: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          cassetta: ['vai', 'apri'],
          par: 5,
          dritta: '«Apri» non cammina. Porta Gedeo fin lì con una fila di «vai», una meta dopo l\'altra, e solo quando è davanti alla porta digli di aprire.',
          n: 2,
          emoji: '🔩',
          storia: 'In fondo alla scalinata c\'è una porta di ferro, e il chiavistello sta dalla nostra parte. Basta tirarlo: ma da lontano non si tira niente, e di serrature ci capisce solo Gedeo.',
          concetto: {
            id: 'prossimita',
            nome: 'Da vicino',
            cosa: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          },
          scartati: [],
          unita: 1,
          attori: ['gedeo'],
          nemico: null,
          scene: [
            'una porta di ferro con il chiavistello',
            'nello stesso posto, un baule con il coperchio pesante',
            'nello stesso posto, una grata che scorre di lato',
          ],
          haMappa: false,
        },
        {
          id: 'primi-mostri',
          nome: 'I primi mostri',
          idea: 'certe azioni ne pretendono un\'altra prima — la spada prima del mostro — e l\'ordine in cui si scrivono è la differenza fra vincere e perdere',
          cassetta: ['vai', 'apri', 'prendi', 'attacca'],
          par: 8,
          dritta: 'Gli stessi ordini in un altro ordine sono un altro piano: prima la rastrelliera, poi il ratto. E la spada la prende Berto — Mira porta la torcia e non mena.',
          n: 3,
          emoji: '🐀',
          storia: 'Dietro la porta qualcosa si muove nel buio. Le spade sono nella rastrelliera all\'ingresso, e nessuno attacca un ratto gigante a mani vuote.',
          concetto: {
            id: 'prerequisiti',
            nome: 'Prima quello',
            cosa: 'certe azioni ne pretendono un\'altra prima — la spada prima del mostro — e l\'ordine in cui si scrivono è la differenza fra vincere e perdere',
          },
          scartati: [],
          unita: 2,
          attori: ['mira', 'berto'],
          nemico: 'ratti giganti',
          scene: [
            'un ratto, e la rastrelliera vicino all\'ingresso',
            'due ratti, uno per angolo',
            'la rastrelliera è in fondo alla sala, i ratti stanno in mezzo',
          ],
          haMappa: false,
        },
        {
          id: 'colonne',
          nome: 'La sala delle colonne',
          idea: 'lo stesso «vai», puntato alla cosa invece che alla casella: uno vale sei, e regge anche quando la cosa si è spostata',
          cassetta: ['vai', 'apri', 'prendi', 'attacca'],
          par: 3,
          dritta: '«Vai alla torcia» costa un ordine invece di sei. Ma la ragione vera è un\'altra: sei mete nominate a mano non ci arrivano più se la torcia cambia colonna, «vai alla torcia» sì.',
          n: 4,
          emoji: '🏛️',
          storia: 'La sala è così grande che il fondo non si vede, e la torcia da accendere è appesa a una colonna. Nominare una per una le mete fin là dentro non finisce più — e il brutto è che ogni volta la colonna è un\'altra.',
          concetto: {
            id: 'astrazione',
            nome: 'Un ordine per sei',
            cosa: 'dire dove si va invece di nominare una per una le mete della strada: costa meno e soprattutto regge quando la stanza cambia',
          },
          scartati: [],
          unita: 2,
          attori: ['mira', 'berto'],
          nemico: null,
          scene: [
            'la torcia sulla colonna di destra',
            'la stessa sala, la torcia sulla colonna in fondo',
            'la sala è più larga e la torcia sta nel mezzo',
          ],
          haMappa: false,
        },
        {
          id: 'corridoi',
          nome: 'I due corridoi',
          idea: 'un ordine con una guardia si esegue solo se la cosa è vera, e se non lo è si salta: è il modo di firmare un piano prima di sapere cosa si troverà',
          cassetta: ['vai', 'apri', 'prendi', 'attacca'],
          par: 7,
          dritta: 'Appendi «se» a un ordine e quell\'ordine, quando tocca a lui, guarda e decide: se la cosa non è vera si salta e il piano tira dritto. Due ordini con due «se» opposti coprono tutti e due i corridoi.',
          n: 5,
          emoji: '🔀',
          storia: 'Due corridoi, e uno solo è aperto. Quale, lo si scopre arrivandoci. Gli ordini però si firmano prima di arrivarci.',
          concetto: {
            id: 'condizione',
            nome: 'Se',
            cosa: 'un ordine con una guardia si esegue solo se la cosa è vera, e se non lo è si salta: è il modo di firmare un piano prima di sapere cosa si troverà',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
          ],
          unita: 2,
          attori: ['mira', 'gedeo'],
          nemico: null,
          scene: [
            'è aperto il corridoio di destra',
            'è aperto quello di sinistra',
            'sono aperti tutti e due: si passa da quello che si trova per primo',
          ],
          haMappa: false,
        },
        {
          id: 'saracinesca',
          nome: 'La saracinesca',
          idea: 'fermarsi finché un fatto succede, invece di contare i momenti e sperare che siano sempre gli stessi',
          cassetta: ['vai', 'apri', 'prendi', 'attacca', 'aspetta'],
          par: 6,
          dritta: '«Aspetta» prende due cose, e una è la trappola: «aspetta un momento» conta e spera, e funziona su una scena su tre. «Aspetta che la saracinesca è alzata» guarda la saracinesca, non l\'orologio. E occhio al «se»: una guardia guarda una volta sola, e se in quel momento la saracinesca è giù salta l\'ordine e nessuno lo rifà.',
          n: 6,
          emoji: '⛓️',
          storia: 'La saracinesca si alza da sola con un rumore di catene, resta su un po\' e poi ricade. Aspettare il momento giusto va bene. Contare fino a tre no, perché non è sempre tre.',
          concetto: {
            id: 'attesa',
            nome: 'Aspetta che',
            cosa: 'fermarsi finché un fatto succede, invece di contare i momenti e sperare che siano sempre gli stessi',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
          ],
          unita: 2,
          attori: ['mira', 'gedeo'],
          nemico: null,
          scene: [
            'la saracinesca si alza dopo tre momenti',
            'dopo sette',
            'si alza subito ma resta su la metà del tempo',
          ],
          haMappa: false,
        },
        {
          id: 'ingranaggio',
          nome: 'L\'ingranaggio',
          idea: 'uno vede e tutti sanno: un\'unità chiama un fatto per nome, le altre hanno una lista che comincia con «quando arriva»',
          cassetta: ['vai', 'apri', 'prendi', 'attacca', 'aspetta', 'chiama'],
          par: 8,
          dritta: 'La manovella la gira Gedeo, che è l\'unico capace, e appena è girata chiama «🚪 porta aperta». Mira ha una seconda lista che parte solo quando arriva quel segnale. Nessuno dei due deve indovinare quanto ci mette l\'altro — e il segnale si sceglie per quello che dice, non per il colore.',
          n: 7,
          emoji: '⚙️',
          storia: 'L\'ingranaggio sta in una stanza e il ponte che alza sta in un\'altra. Chi gira la manovella non vede il ponte; chi è sul ponte non vede la manovella. Bisogna dirselo.',
          concetto: {
            id: 'eventi',
            nome: 'Il segnale',
            cosa: 'uno vede e tutti sanno: un\'unità chiama un fatto per nome, le altre hanno una lista che comincia con «quando arriva»',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 2,
          attori: ['gedeo', 'mira'],
          nemico: null,
          scene: [
            'manovella e ponte come sulla pianta',
            'la manovella è più lontana: girarla porta via il doppio del tempo',
            'davanti alla manovella c\'è una porta da aprire: nessuno sa quando Gedeo avrà finito',
          ],
          haMappa: false,
        },
        {
          id: 'botola',
          nome: 'La botola',
          idea: 'due unità che dipendono l\'una dall\'altra per tutta la scena, non per un istante solo — e chi fa cosa lo decide chi lo sa fare',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
          ],
          par: 10,
          dritta: 'Gedeo apre la botola, quindi sulla piastra ci deve stare Lilla: non è una scelta, è l\'unica distribuzione che funziona. Sotto, copiare la strada di Mira in un altro piano regge una volta e poi si sfalsa — basta che lei si fermi un momento. «Segui Mira» non si sfalsa mai.',
          n: 8,
          emoji: '🕳️',
          storia: 'Sotto il tappeto c\'è una botola, e resta aperta solo finché qualcuno sta sulla piastra dall\'altra parte della sala. Aprirla sa farlo solo Gedeo, e sotto è buio: la torcia ce l\'ha Mira.',
          concetto: {
            id: 'coordinamento',
            nome: 'In due',
            cosa: 'due unità che dipendono l\'una dall\'altra per tutta la scena, non per un istante solo — e chi fa cosa lo decide chi lo sa fare',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 3,
          attori: ['mira', 'gedeo', 'lilla'],
          nemico: null,
          scene: [
            'la piastra a destra, la botola nel mezzo',
            'la piastra in fondo alla sala: chi ci sta sopra arriva molto più tardi',
            'sotto, il pavimento buono fa una curva diversa',
          ],
          haMappa: false,
        },
        {
          id: 'statue',
          nome: 'Il corridoio delle statue',
          idea: 'la stessa cosa tante volte, scritta a mano: lunga da scrivere e fragile da cambiare — ed è il punto',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
          ],
          par: 14,
          dritta: 'È il piano più lungo di tutta la campagna, e va scritto tutto: Berto va da un capo all\'altro del corridoio 10 volte, e sono 10 righe uguali. Contale mentre le scrivi: alla prossima tappa ti serviranno per un motivo.',
          n: 9,
          emoji: '🗿',
          storia: 'Le statue del corridoio si girano quando nessuno le guarda, e restano ferme finché qualcuno cammina avanti e indietro davanti a loro. Gli altri intanto lavorano in fondo.',
          concetto: {
            id: 'ripetizione',
            nome: 'Ancora e ancora',
            cosa: 'la stessa cosa tante volte, scritta a mano: lunga da scrivere e fragile da cambiare — ed è il punto',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 3,
          attori: ['berto', 'gedeo', 'lilla'],
          nemico: 'le statue',
          scene: [
            'un corridoio con quattro statue',
            'lo stesso corridoio, più lungo',
            'sei statue e una svolta a metà',
          ],
          haMappa: false,
        },
        {
          id: 'sala-buia',
          nome: 'La sala buia',
          idea: 'la ripetizione detta in un ordine solo, con la condizione che dice quando smettere',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
            'pattuglia',
          ],
          par: 6,
          dritta: 'La prima scena è il corridoio di ieri: rifallo e conta gli ordini, da 10 righe a una. Poi c\'è la sala buia, dove una fila scritta a mano non basterebbe comunque, perché la chiave si sposta.',
          n: 10,
          emoji: '🔁',
          storia: '10 righe uguali, ieri, per tenere ferme le statue. Oggi nella cassetta c\'è «pattuglia … finché», che è la stessa cosa detta in una riga sola — e serve subito, perché la chiave del tesoro è in un angolo della sala buia e non è sempre lo stesso angolo.',
          concetto: {
            id: 'ciclo',
            nome: 'Finché',
            cosa: 'la ripetizione detta in un ordine solo, con la condizione che dice quando smettere',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 3,
          attori: ['berto', 'gedeo', 'lilla'],
          nemico: 'le statue',
          scene: [
            'il corridoio delle statue della tappa scorsa, da rifare in un ordine',
            'la sala buia, con la chiave nell\'angolo a nord',
            'la sala buia, con la chiave a sud e una porta che si richiude',
          ],
          haMappa: false,
        },
        {
          id: 'guardia',
          nome: 'La guardia del tesoro',
          idea: 'anche l\'avversario ha ordini firmati, e si possono leggere prima dei propri: non è fortuna, è lettura',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
            'pattuglia',
          ],
          par: 10,
          dritta: 'Non serve batterlo: serve sapere dov\'è. Leggi il suo giro, trova il momento in cui dà le spalle alla porta, e fai partire il tuo da lì — e ricordati che la porta la apre solo Gedeo, quindi è lui che deve essere lì in quel momento.',
          n: 11,
          emoji: '📜',
          storia: 'Davanti alla porta del tesoro c\'è un ogre che non dorme mai. I suoi ordini però sono scritti su una tavola appesa al muro, e si leggono prima di firmare i nostri.',
          concetto: {
            id: 'piano-altrui',
            nome: 'Il piano dell\'altro',
            cosa: 'anche l\'avversario ha ordini firmati, e si possono leggere prima dei propri: non è fortuna, è lettura',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 3,
          attori: ['mira', 'lilla', 'gedeo'],
          nemico: 'l\'ogre',
          scene: [
            'l\'ogre fa avanti e indietro davanti alla porta',
            'lo stesso giro, ma parte dall\'altro capo',
            'l\'ogre si ferma a bere: il suo giro dura di più',
          ],
          haMappa: false,
        },
        {
          id: 'portone',
          nome: 'Il portone',
          idea: 'nel piano dell\'avversario c\'è uno sbaglio. Non va corretto: va usato',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
            'pattuglia',
          ],
          par: 11,
          dritta: 'Leggi il suo piano riga per riga e cerca le due che stanno nell\'ordine sbagliato. Poi mettiti dove ti conviene essere nel momento in cui le esegue.',
          n: 12,
          emoji: '🐞',
          storia: 'Anche il capitano degli orchi ha firmato i suoi ordini, e uno è sbagliato: apre il portone e solo dopo guarda chi c\'è fuori. Nessuno gliel\'ha detto. Non va corretto: va usato.',
          concetto: {
            id: 'bug',
            nome: 'L\'errore dell\'altro',
            cosa: 'nel piano dell\'avversario c\'è uno sbaglio. Non va corretto: va usato',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 4,
          attori: ['mira', 'berto', 'gedeo', 'lilla'],
          nemico: 'il capitano Grum',
          scene: [
            'il capitano da solo',
            'il capitano e una sentinella sulle mura',
            'la sentinella chiama «👁️ nemico in vista»: Grum lo sente, ma le sue due righe restano in quell\'ordine',
          ],
          haMappa: false,
        },
        {
          id: 'cuore',
          nome: 'Il cuore del dungeon',
          idea: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          cassetta: [
            'vai',
            'apri',
            'prendi',
            'attacca',
            'aspetta',
            'chiama',
            'segui',
            'pattuglia',
          ],
          par: 18,
          dritta: 'Nessuna parola nuova. Guarda la sala, decidi chi fa cosa — le porte e le leve sono di Gedeo, il drago di Berto — e ricordati che il drago si sveglia col rumore: le leve vanno tirate nell\'ordine giusto.',
          n: 13,
          emoji: '🐲',
          storia: 'L\'ultima sala ha quattro porte, due leve, un drago che dorme e nessun ordine nuovo. Tutto quello che serve è già stato imparato: qui si tratta di metterlo in fila.',
          concetto: {
            id: 'sintesi',
            nome: 'Tutto insieme',
            cosa: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
          ],
          unita: 4,
          attori: ['mira', 'berto', 'gedeo', 'lilla'],
          nemico: 'il drago',
          scene: [
            'quattro porte, due leve, il drago dorme',
            'una leva è già abbassata e una porta è chiusa a chiave',
            'il drago si sveglia a metà scena',
          ],
          haMappa: false,
        },
      ],
    },
    {
      id: 'nina',
      nome: 'Nina e il draghetto',
      emoji: '🐉',
      sottotitolo: 'Una bambina, un cane e una festa da preparare',
      tappe: [
        {
          id: 'mela',
          nome: 'La mela',
          idea: 'gli ordini si eseguono uno dopo l\'altro, dal primo all\'ultimo, e quello che non hai scritto non succede',
          cassetta: ['vai'],
          par: 3,
          dritta: 'Un ordine alla volta, dal primo all\'ultimo. Dille dove andare, un posto per volta.',
          n: 1,
          emoji: '🍎',
          storia: 'Nina ha fame. La mela è in fondo al prato.',
          concetto: {
            id: 'sequenza',
            nome: 'La fila',
            cosa: 'gli ordini si eseguono uno dopo l\'altro, dal primo all\'ultimo, e quello che non hai scritto non succede',
          },
          scartati: [],
          unita: 1,
          attori: ['nina'],
          nemico: null,
          scene: [
            'il prato con le margherite',
            'lo stesso prato di sera',
            'lo stesso prato, e una farfalla',
          ],
          haMappa: false,
        },
        {
          id: 'chiave',
          nome: 'La chiave',
          idea: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          cassetta: ['vai', 'prendi'],
          par: 4,
          dritta: 'Per prendere una cosa bisogna esserci sopra.',
          n: 2,
          emoji: '🔑',
          storia: 'La chiave è nell\'erba. Nina la vuole.',
          concetto: {
            id: 'prossimita',
            nome: 'Da vicino',
            cosa: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          },
          scartati: [],
          unita: 1,
          attori: ['nina'],
          nemico: null,
          scene: [
            'la chiave nell\'erba alta',
            'la chiave vicino al sasso',
            'la chiave sotto la panchina',
          ],
          haMappa: false,
        },
        {
          id: 'porta',
          nome: 'La porta',
          idea: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          cassetta: ['vai', 'prendi', 'apri'],
          par: 4,
          dritta: 'Da lontano non si apre niente. Prima arrivarci, poi aprire.',
          n: 3,
          emoji: '🚪',
          storia: 'La porta dell\'orto è chiusa. Nina va e apre.',
          concetto: {
            id: 'prossimita',
            nome: 'Da vicino',
            cosa: 'un\'azione non cammina: per aprire una cosa bisogna già esserle davanti',
          },
          scartati: [],
          unita: 1,
          attori: ['nina'],
          nemico: null,
          scene: [
            'la porta di legno',
            'la stessa porta, con il gatto sopra',
            'la stessa porta, e piove',
          ],
          haMappa: false,
        },
        {
          id: 'cancello',
          nome: 'Pippo',
          idea: 'certe azioni ne pretendono un\'altra prima — la spada prima del mostro — e l\'ordine in cui si scrivono è la differenza fra vincere e perdere',
          cassetta: ['vai', 'prendi', 'apri'],
          par: 5,
          dritta: 'Senza chiave il cancello non si apre.',
          n: 4,
          emoji: '🐾',
          storia: 'Pippo è nel recinto. Prima la chiave, poi il cancello.',
          concetto: {
            id: 'prerequisiti',
            nome: 'Prima quello',
            cosa: 'certe azioni ne pretendono un\'altra prima — la spada prima del mostro — e l\'ordine in cui si scrivono è la differenza fra vincere e perdere',
          },
          scartati: [],
          unita: 1,
          attori: ['nina', 'pippo'],
          nemico: null,
          scene: [
            'la chiave sul muretto',
            'la chiave dietro il fienile',
            'due cancelli e una chiave sola',
          ],
          haMappa: false,
        },
        {
          id: 'prato-grande',
          nome: 'Il prato grande',
          idea: 'lo stesso «vai» di sempre, ma puntato all\'albero invece che a sei posti in fila: uno vale sei',
          cassetta: ['vai', 'prendi', 'apri'],
          par: 3,
          dritta: '«Vai all\'albero» vale sei posti in fila.',
          n: 5,
          emoji: '🌾',
          storia: 'Il prato è grande. Nina dice dove va.',
          concetto: {
            id: 'astrazione',
            nome: 'Un ordine per sei',
            cosa: 'dire dove si va invece di nominare una per una le mete della strada: costa meno e soprattutto regge quando la stanza cambia',
          },
          scartati: [],
          unita: 1,
          attori: ['nina'],
          nemico: null,
          scene: [
            'l\'albero a destra',
            'l\'albero in fondo',
            'l\'albero dall\'altra parte',
          ],
          haMappa: false,
        },
        {
          id: 'festa',
          nome: 'La festa',
          idea: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          cassetta: ['vai', 'prendi', 'apri'],
          par: 7,
          dritta: 'Due amici, due liste di ordini. Pippo non ha le mani: la torta e le candele le porta Nina. Lui sa correre e basta, e allora mandalo dal draghetto.',
          n: 6,
          emoji: '🎂',
          storia: 'Il draghetto fa gli anni. Torta e candele!',
          concetto: {
            id: 'sintesi',
            nome: 'Tutto insieme',
            cosa: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          },
          scartati: [],
          unita: 2,
          attori: ['nina', 'pippo', 'draghetto'],
          nemico: null,
          scene: [
            'la torta in cucina',
            'la torta in dispensa, chiusa a chiave',
            'le candele sono due e stanno lontane',
          ],
          haMappa: false,
        },
      ],
    },
    {
      id: 'fortezza',
      nome: 'La fortezza degli orchi',
      emoji: '🏰',
      sottotitolo: 'Stavolta i tuoi sono quelli dentro, e gli altri hanno un piano',
      tappe: [
        {
          id: 'turno',
          nome: 'Il turno di guardia',
          idea: 'si comanda chi difende, e chi attacca è il programma: pensare a dove passerà, non a dove è',
          cassetta: [
            'vai',
            'prendi',
            'apri',
            'attacca',
            'aspetta',
            'chiama',
            'pattuglia',
            'segui',
          ],
          par: 8,
          dritta: 'Non inseguirli. Leggi dove vanno e mettici Zanna prima che ci arrivino: «difendi il portone» vuol dire restare lì anche quando sembra che non serva.',
          n: 1,
          emoji: '🛡️',
          storia: 'Stavolta la fortezza è nostra. Gli avventurieri sono là fuori, i loro ordini sono già scritti e si leggono: quello che manca è qualcuno che stia dove passeranno.',
          concetto: {
            id: 'inversione',
            nome: 'Dall\'altra parte',
            cosa: 'si comanda chi difende, e chi attacca è il programma: pensare a dove passerà, non a dove è',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
            {
              ordine: 'difendi',
              perche: 'difendere un posto non è ancora nel formato',
            },
          ],
          unita: 2,
          attori: ['zanna', 'grum'],
          nemico: 'gli avventurieri',
          scene: [
            'tre avventurieri e una porta sola',
            'gli stessi tre entrano dal lato opposto',
            'uno resta fuori a fare da richiamo',
          ],
          haMappa: false,
        },
        {
          id: 'ronda',
          nome: 'La ronda sulle mura',
          idea: 'una pattuglia non copre uno spazio: copre uno spazio ogni tanto. Il buco che lascia è nel tempo, e si misura',
          cassetta: [
            'vai',
            'prendi',
            'apri',
            'attacca',
            'aspetta',
            'chiama',
            'pattuglia',
            'segui',
          ],
          par: 7,
          dritta: 'Zanna al portone non si sposta, quindi la ronda è di Mola: una sola, e lunga quanto decidi tu. Una pattuglia lunga copre tanto muro e lo copre di rado. Guarda quando arrivano loro, poi decidi quanto larga farla.',
          n: 2,
          emoji: '🧱',
          storia: 'Le mura sono lunghe e gli orchi sono due. Chi cammina non può essere in due posti, quindi la domanda non è dove mettersi: è per quanto tempo un pezzo di muro resta scoperto.',
          concetto: {
            id: 'ciclo',
            nome: 'Finché',
            cosa: 'la ripetizione detta in un ordine solo, con la condizione che dice quando smettere',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
            {
              ordine: 'difendi',
              perche: 'difendere un posto non è ancora nel formato',
            },
          ],
          unita: 2,
          attori: ['zanna', 'mola'],
          nemico: 'gli avventurieri',
          scene: [
            'entrano da nord appena comincia',
            'entrano da sud, più tardi',
            'aspettano che la ronda si allontani e poi scavalcano',
          ],
          haMappa: false,
        },
        {
          id: 'vedetta',
          nome: 'La vedetta',
          idea: 'nel dungeon il segnale si ascoltava; qui si decide chi lo chiama e quale — e un segnale che dice solo «sono arrivati» non basta a nessuno',
          cassetta: [
            'vai',
            'prendi',
            'apri',
            'attacca',
            'aspetta',
            'chiama',
            'pattuglia',
            'segui',
          ],
          par: 10,
          dritta: 'Un segnale solo non basta se entrano da due parti: appendi un «se» alla chiamata e Occhio sceglie quale nome dire — «👁️ nemico in vista» o «🚪 porta aperta» — e chi lo sente va in due posti diversi.',
          n: 3,
          emoji: '🔔',
          storia: 'Dalla torre si vede tutto e non si difende niente. Occhio lassù vale gli altri tre, ma solo se dice quello che vede, e solo se gli altri hanno una lista che comincia con «quando arriva».',
          concetto: {
            id: 'eventi',
            nome: 'Il segnale',
            cosa: 'uno vede e tutti sanno: un\'unità chiama un fatto per nome, le altre hanno una lista che comincia con «quando arriva»',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
            {
              ordine: 'difendi',
              perche: 'difendere un posto non è ancora nel formato',
            },
          ],
          unita: 3,
          attori: ['occhio', 'zanna', 'mola'],
          nemico: 'gli avventurieri',
          scene: [
            'entrano in tre dallo stesso lato',
            'si dividono in due gruppi',
            'uno finge di entrare da nord mentre gli altri passano da sud',
          ],
          haMappa: false,
        },
        {
          id: 'crepa',
          nome: 'La crepa',
          idea: 'stavolta lo sbaglio è nel tuo piano: si riguarda la scena finché non si vede dov\'è',
          cassetta: [
            'vai',
            'prendi',
            'apri',
            'attacca',
            'aspetta',
            'chiama',
            'pattuglia',
            'segui',
          ],
          par: 10,
          dritta: 'Guarda la scena una volta senza toccare niente e segnati il momento in cui entrano. Poi torna indietro e guarda cosa stavano facendo i due del cortile in quel momento.',
          n: 4,
          emoji: '🩹',
          storia: 'Il piano di ieri notte è ancora appeso al muro, e la fortezza è caduta lo stesso. Non è colpa degli avventurieri: nel piano c\'è una crepa, e la scena si riguarda finché non si trova dov\'è.',
          concetto: {
            id: 'debug',
            nome: 'La crepa',
            cosa: 'stavolta lo sbaglio è nel tuo piano: si riguarda la scena finché non si vede dov\'è',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
            {
              ordine: 'difendi',
              perche: 'difendere un posto non è ancora nel formato',
            },
          ],
          unita: 3,
          attori: ['grum', 'zanna', 'mola'],
          nemico: 'gli avventurieri',
          scene: [
            'la scena persa di ieri notte, da guardare',
            'gli avventurieri arrivano prima',
            'gli avventurieri sono quattro',
          ],
          haMappa: false,
        },
        {
          id: 'notte',
          nome: 'La notte lunga',
          idea: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          cassetta: [
            'vai',
            'prendi',
            'apri',
            'attacca',
            'aspetta',
            'chiama',
            'pattuglia',
            'segui',
          ],
          par: 16,
          dritta: 'Il piano degli avventurieri è lungo e si legge tutto. Leggilo prima: metà del lavoro è già lì dentro. E i portoni li apre e li chiude solo Mola, quindi il suo giro va scritto per primo.',
          n: 5,
          emoji: '🌑',
          storia: 'Quattro orchi, sei avventurieri, due portoni e nessun ordine nuovo. Se la fortezza regge fino all\'alba, il dungeon resta nostro.',
          concetto: {
            id: 'sintesi',
            nome: 'Tutto insieme',
            cosa: 'niente di nuovo nella cassetta: quello che c\'è va messo in fila',
          },
          scartati: [
            {
              ordine: 'se',
              perche: 'non è un verbo: è la guardia «quando» di un ordine',
            },
            {
              ordine: 'quando-arriva',
              perche: 'non è un verbo di questo formato',
            },
            {
              ordine: 'difendi',
              perche: 'difendere un posto non è ancora nel formato',
            },
          ],
          unita: 4,
          attori: ['grum', 'zanna', 'mola', 'occhio'],
          nemico: 'gli avventurieri',
          scene: [
            'entrano tutti insieme dal portone grande',
            'si dividono in tre gruppi e uno fa il giro largo',
            'uno di loro sa del segnale e lo fa chiamare apposta',
          ],
          haMappa: false,
        },
      ],
    },
  ],
}
