// Le frasi componibili del mondo «prima», la valle dei girasoli. `es` minuscolo
// e senza punteggiatura (¿ ? li mette la fila); gli id di data/frasi-es.js
// restano solo sulla stessa frase. La difficoltà dell'isola è il genere:
// el pato, el auto, la cometa, el mapa, la regla non sono come in italiano.
// Formato e regole in docs/lingue/spagnolo-motore.md.
export default {
  mondo: 'prima',
  frasi: [
    /* ── È un cane, è una mucca ── */
    { id: 'pr-es-perro', tappa: 'prima-es-un', forma: 'es-un', it: 'è un cane', es: 'es un perro' },
    { id: 'pr-es-vaca', tappa: 'prima-es-un', forma: 'es-un', it: 'è una mucca', es: 'es una vaca' },
    { id: 'pr-es-pelota', tappa: 'prima-es-un', forma: 'es-un', it: 'è una palla', es: 'es una pelota' },
    { id: 'pr-es-pez', tappa: 'prima-es-un', forma: 'es-un', it: 'è un pesce', es: 'es un pez' },
    { id: 'pr-es-muneca', tappa: 'prima-es-un', forma: 'es-un', it: 'è una bambola', es: 'es una muñeca' },
    { id: 'pr-es-peluche', tappa: 'prima-es-un', forma: 'es-un', it: 'è un orsacchiotto', es: 'es un peluche' },
    { id: 'pr-es-pato', tappa: 'prima-es-un', forma: 'es-un', it: 'è un’anatra', es: 'es un pato' },
    { id: 'pr-es-auto', tappa: 'prima-es-un', forma: 'es-un', it: 'è un’automobile', es: 'es un auto' },
    { id: 'pr-es-bote', tappa: 'prima-es-un', forma: 'es-un', it: 'è una barca', es: 'es un bote' },
    { id: 'pr-es-cometa', tappa: 'prima-es-un', forma: 'es-un', it: 'è un aquilone', es: 'es una cometa' },
    { id: 'pr-no-cerdo', tappa: 'prima-es-un', forma: 'es-un', it: 'non è un maiale', es: 'no es un cerdo' },
    { id: 'pr-no-vaca', tappa: 'prima-es-un', forma: 'es-un', it: 'non è una mucca', es: 'no es una vaca' },
    { id: 'pr-no-caballo', tappa: 'prima-es-un', forma: 'es-un', it: 'non è un cavallo', es: 'no es un caballo' },
    { id: 'pr-es-gato-dom', tappa: 'prima-es-un', forma: 'es-un', it: 'è un gatto?', es: 'es un gato' },
    { id: 'pr-es-raton-dom', tappa: 'prima-es-un', forma: 'es-un', it: 'è un topo?', es: 'es un ratón' },
    { id: 'pr-es-conejo-dom', tappa: 'prima-es-un', forma: 'es-un', it: 'è un coniglio?', es: 'es un conejo' },
    { id: 'pr-si-dado', tappa: 'prima-es-un', forma: 'es-un', it: 'sì, è un dado', es: 'sí es un dado' },

    /* ── Il gatto, la mucca ── */
    { id: 'e-gato-negro', tappa: 'prima-el-la', forma: 'el-la', it: 'il gatto è nero', es: 'el gato es negro' },
    { id: 'pr-la-vaca-blanca', tappa: 'prima-el-la', forma: 'el-la', it: 'la mucca è bianca', es: 'la vaca es blanca' },
    { id: 'pr-la-pelota-azul', tappa: 'prima-el-la', forma: 'el-la', it: 'la palla è blu', es: 'la pelota es azul' },
    { id: 'pr-el-pez-naranja', tappa: 'prima-el-la', forma: 'el-la', it: 'il pesce è arancione', es: 'el pez es naranja' },
    { id: 'pr-el-caballo-marron', tappa: 'prima-el-la', forma: 'el-la', it: 'il cavallo è marrone',
      es: 'el caballo es marrón' },
    { id: 'pr-la-muneca-rosada', tappa: 'prima-el-la', forma: 'el-la', it: 'la bambola è rosa', es: 'la muñeca es rosada' },
    { id: 'pr-el-raton-blanco', tappa: 'prima-el-la', forma: 'el-la', it: 'il topo è bianco', es: 'el ratón es blanco' },
    { id: 'pr-el-pato-amarillo', tappa: 'prima-el-la', forma: 'el-la', it: 'l’anatra è gialla', es: 'el pato es amarillo' },
    { id: 'pr-el-auto-rojo', tappa: 'prima-el-la', forma: 'el-la', it: 'l’automobile è rossa', es: 'el auto es rojo' },
    { id: 'pr-el-bote-blanco', tappa: 'prima-el-la', forma: 'el-la', it: 'la barca è bianca', es: 'el bote es blanco' },
    { id: 'pr-la-cometa-verde', tappa: 'prima-el-la', forma: 'el-la', it: 'l’aquilone è verde', es: 'la cometa es verde' },
    { id: 'pr-el-conejo-no-negro', tappa: 'prima-el-la', forma: 'el-la', it: 'il coniglio non è nero',
      es: 'el conejo no es negro' },
    { id: 'pr-el-perro-no-blanco', tappa: 'prima-el-la', forma: 'el-la', it: 'il cane non è bianco',
      es: 'el perro no es blanco' },
    { id: 'pr-la-pelota-no-roja', tappa: 'prima-el-la', forma: 'el-la', it: 'la palla non è rossa',
      es: 'la pelota no es roja' },
    { id: 'pr-el-dado-rojo-dom', tappa: 'prima-el-la', forma: 'el-la', it: 'il dado è rosso?', es: 'el dado es rojo' },
    { id: 'pr-la-vaca-marron-dom', tappa: 'prima-el-la', forma: 'el-la', it: 'la mucca è marrone?',
      es: 'la vaca es marrón' },
    { id: 'pr-el-patin-azul-dom', tappa: 'prima-el-la', forma: 'el-la', it: 'il pattino è blu?', es: 'el patín es azul' },

    /* ── Un gatto nero ── */
    { id: 'pr-gato-negro', tappa: 'prima-color', forma: 'color-despues', it: 'è un gatto nero', es: 'es un gato negro' },
    { id: 'pr-pelota-roja', tappa: 'prima-color', forma: 'color-despues', it: 'è una palla rossa', es: 'es una pelota roja' },
    { id: 'pr-vaca-blanca-negra', tappa: 'prima-color', forma: 'color-despues', it: 'è una mucca bianca e nera',
      es: 'es una vaca blanca y negra' },
    { id: 'pr-muneca-morada', tappa: 'prima-color', forma: 'color-despues', it: 'è una bambola viola',
      es: 'es una muñeca morada' },
    { id: 'pr-cerdo-rosado', tappa: 'prima-color', forma: 'color-despues', it: 'è un maiale rosa', es: 'es un cerdo rosado' },
    { id: 'pr-auto-rojo', tappa: 'prima-color', forma: 'color-despues', it: 'è un’automobile rossa', es: 'es un auto rojo' },
    { id: 'pr-pato-amarillo', tappa: 'prima-color', forma: 'color-despues', it: 'è un’anatra gialla',
      es: 'es un pato amarillo' },
    { id: 'pr-cometa-roja-amarilla', tappa: 'prima-color', forma: 'color-despues', it: 'l’aquilone è rosso e giallo',
      es: 'la cometa es roja y amarilla' },
    { id: 'pr-pez-naranja', tappa: 'prima-color', forma: 'color-despues', it: 'è un pesce arancione', es: 'es un pez naranja' },
    { id: 'pr-cometa-azul', tappa: 'prima-color', forma: 'color-despues', it: 'è un aquilone blu', es: 'es una cometa azul' },
    { id: 'pr-bote-verde', tappa: 'prima-color', forma: 'color-despues', it: 'è una barca verde', es: 'es un bote verde' },
    { id: 'pr-pelota-verde-azul', tappa: 'prima-color', forma: 'color-despues', it: 'è una palla verde e blu',
      es: 'es una pelota verde y azul' },
    { id: 'pr-no-conejo-blanco', tappa: 'prima-color', forma: 'color-despues', it: 'non è un coniglio bianco',
      es: 'no es un conejo blanco' },
    { id: 'pr-caballo-negro-dom', tappa: 'prima-color', forma: 'color-despues', it: 'è un cavallo nero?',
      es: 'es un caballo negro' },
    { id: 'pr-pelota-amarilla-dom', tappa: 'prima-color', forma: 'color-despues', it: 'è una palla gialla?',
      es: 'es una pelota amarilla' },
    { id: 'pr-dado-rojo-blanco', tappa: 'prima-color', forma: 'color-despues', it: 'è un dado rosso e bianco',
      es: 'es un dado rojo y blanco' },

    /* ── Ciao! Come ti chiami? ── */
    { id: 'pr-hola-me-llamo', tappa: 'prima-hola', forma: 'saludos', it: 'ciao, mi chiamo Leo', es: 'hola me llamo Leo' },
    { id: 'pr-yo-me-llamo', tappa: 'prima-hola', forma: 'saludos', it: 'io mi chiamo Laura', es: 'yo me llamo Laura' },
    { id: 'pr-hola-soy-tom', tappa: 'prima-hola', forma: 'saludos', it: 'ciao, sono Tom', es: 'hola soy Tom',
      trappole: [{ es: 'ola soy Tom', perche: 'Hola si scrive con la h, anche se non si sente' },
                 { es: 'hola estoy Tom', perche: 'Per dire chi sei si usa soy: soy Tom' },
                 { es: 'hola es Tom', it: 'ciao, è Tom', perche: 'Io sono: soy; es vuol dire «è»' }] },
    { id: 'd-como-llamas', tappa: 'prima-hola', forma: 'saludos', it: 'come ti chiami?', es: 'cómo te llamas',
      niente: ['riflessivo-persona'] },
    { id: 'pr-te-llamas-tom', tappa: 'prima-hola', forma: 'saludos', it: 'ti chiami Tom?', es: 'te llamas Tom',
      niente: ['riflessivo-persona'],
      trappole: [{ es: 'te llamo Tom', it: 'ti chiamo Tom?', perche: 'Tu ti chiami: te llamas; llamo è «io chiamo»' }] },
    { id: 'pr-y-tu-como', tappa: 'prima-hola', forma: 'saludos', it: 'e tu, come ti chiami?', es: 'y tú cómo te llamas',
      niente: ['riflessivo-persona'] },
    { id: 'd-como-estas', tappa: 'prima-hola', forma: 'saludos', it: 'come stai?', es: 'cómo estás',
      trappole: [{ es: 'cómo estoy', it: 'come sto?', perche: 'Tu: estás; estoy vuol dire «io sto»' },
                 { es: 'cómo es', perche: 'Come stai si dice con estar: cómo estás' }] },
    { id: 'pr-estoy-bien', tappa: 'prima-hola', forma: 'saludos', it: 'sto bene, grazie', es: 'estoy bien gracias',
      trappole: [{ es: 'estás bien gracias', it: 'stai bene, grazie', perche: 'Io sto: estoy; estás vuol dire «tu stai»' },
                 { es: 'estoy bien por favor', it: 'sto bene, per favore',
                   perche: 'Grazie è gracias; por favor vuol dire «per favore»' }] },
    { id: 'pr-no-estoy-bien', tappa: 'prima-hola', forma: 'saludos', it: 'non sto bene', es: 'no estoy bien',
      trappole: [{ es: 'no estás bien', it: 'non stai bene', perche: 'Io sto: estoy; estás vuol dire «tu stai»' },
                 { es: 'estoy no bien', perche: 'No va prima del verbo: no estoy' }] },
    { id: 'e-buenos-dias', tappa: 'prima-hola', forma: 'saludos', it: 'buongiorno', es: 'buenos días',
      trappole: [{ es: 'buenas tardes', it: 'buon pomeriggio', perche: 'Buenos días è il mattino, buenas tardes il pomeriggio' },
                 { es: 'buenas noches', it: 'buonanotte', perche: 'Buenos días è «buongiorno», buenas noches «buonanotte»' }] },
    { id: 'pr-buenas-tardes', tappa: 'prima-hola', forma: 'saludos', it: 'buon pomeriggio, Leo', es: 'buenas tardes Leo',
      trappole: [{ es: 'buena tarde Leo', perche: 'Si dice al plurale: buenas tardes' },
                 { es: 'buenos días Leo', it: 'buongiorno, Leo', perche: 'Buenas tardes è il pomeriggio, buenos días il mattino' }] },
    { id: 'e-buenas-noches', tappa: 'prima-hola', forma: 'saludos', it: 'buonanotte', es: 'buenas noches',
      trappole: [{ es: 'buena noche', perche: 'Si dice al plurale: buenas noches' },
                 { es: 'buenos días', it: 'buongiorno', perche: 'Buenas noches è «buonanotte», buenos días «buongiorno»' }] },
    { id: 'pr-adios-tom', tappa: 'prima-hola', forma: 'saludos', it: 'arrivederci, Tom', es: 'adiós Tom',
      trappole: [{ es: 'adios Tom', perche: 'Adiós si scrive con l’accento sulla o' },
                 { es: 'hola Tom', it: 'ciao, Tom', perche: 'Adiós è «arrivederci», hola è «ciao»' },
                 { es: 'gracias Tom', it: 'grazie, Tom', perche: 'Adiós è «arrivederci», gracias è «grazie»' }] },
    { id: 'pr-gracias-regalo', tappa: 'prima-hola', forma: 'saludos', it: 'grazie per il regalo',
      es: 'gracias por el regalo' },
    { id: 'pr-feliz-navidad', tappa: 'prima-hola', forma: 'saludos', it: 'buon Natale', es: 'feliz Navidad',
      trappole: [{ es: 'felice Navidad', perche: 'Felice in spagnolo si scrive feliz, con la z' },
                 { es: 'buena Navidad', perche: 'Per gli auguri si dice feliz: feliz Navidad' }] },
    { id: 'pr-feliz-pascua', tappa: 'prima-hola', forma: 'saludos', it: 'buona Pasqua', es: 'feliz Pascua',
      trappole: [{ es: 'felice Pascua', perche: 'Felice in spagnolo si scrive feliz, con la z' },
                 { es: 'buena Pascua', perche: 'Per gli auguri si dice feliz: feliz Pascua' }] },
    { id: 'pr-feliz-carnaval', tappa: 'prima-hola', forma: 'saludos', it: 'buon Carnevale', es: 'feliz Carnaval',
      trappole: [{ es: 'felice Carnaval', perche: 'Felice in spagnolo si scrive feliz, con la z' }] },

    /* ── Questo è… ── */
    { id: 'e-gato-1', tappa: 'prima-este', forma: 'este-esta', it: 'questo è un gatto', es: 'este es un gato' },
    { id: 'pr-este-libro', tappa: 'prima-este', forma: 'este-esta', it: 'questo è un libro', es: 'este es un libro' },
    { id: 'pr-esta-caja-dom', tappa: 'prima-este', forma: 'este-esta', it: 'questa è una scatola?', es: 'esta es una caja' },
    { id: 'pr-esta-regla', tappa: 'prima-este', forma: 'este-esta', it: 'questo è un righello', es: 'esta es una regla' },
    { id: 'pr-este-mapa', tappa: 'prima-este', forma: 'este-esta', it: 'questa è una mappa', es: 'este es un mapa' },
    { id: 'pr-este-boligrafo', tappa: 'prima-este', forma: 'este-esta', it: 'questa è una penna', es: 'este es un bolígrafo' },
    { id: 'pr-este-borrador', tappa: 'prima-este', forma: 'este-esta', it: 'questa è la gomma', es: 'este es el borrador' },
    { id: 'pr-esta-mi-mochila', tappa: 'prima-este', forma: 'este-esta', it: 'questo è il mio zaino',
      es: 'esta es mi mochila' },
    { id: 'pr-este-mi-lapiz', tappa: 'prima-este', forma: 'este-esta', it: 'questa è la mia matita', es: 'este es mi lápiz' },
    { id: 'pr-este-mi-perro', tappa: 'prima-este', forma: 'este-esta', it: 'questo è il mio cane', es: 'este es mi perro' },
    { id: 'pr-esta-mi-muneca', tappa: 'prima-este', forma: 'este-esta', it: 'questa è la mia bambola',
      es: 'esta es mi muñeca' },
    { id: 'pr-este-no-mi-cuaderno', tappa: 'prima-este', forma: 'este-esta', it: 'questo non è il mio quaderno',
      es: 'este no es mi cuaderno' },
    { id: 'pr-este-lapiz-rojo', tappa: 'prima-este', forma: 'este-esta', it: 'questa matita è rossa', es: 'este lápiz es rojo' },
    { id: 'pr-esta-regla-amarilla', tappa: 'prima-este', forma: 'este-esta', it: 'questo righello è giallo',
      es: 'esta regla es amarilla' },
    { id: 'pr-este-cuaderno-verde', tappa: 'prima-este', forma: 'este-esta', it: 'questo quaderno è verde',
      es: 'este cuaderno es verde' },
    { id: 'pr-esta-mochila-azul-dom', tappa: 'prima-este', forma: 'este-esta', it: 'questo zaino è blu?',
      es: 'esta mochila es azul' },
    { id: 'pr-este-disfraz', tappa: 'prima-este', forma: 'este-esta', it: 'questo è il mio costume', es: 'este es mi disfraz' },
  ],
}
