// Le frasi componibili del mondo «La terra dei vulcani»: ir e venir con al e
// del, la strada, i soldi, di chi è, querer e poder. Il formato di una frase
// e le regole stanno in docs/lingue/spagnolo-motore.md.
export default {
  mondo: 'quinta',
  frasi: [
    /* ── Vado al parco: ir, venir, al, del ── */
    { id: 'qi-voy-parque', tappa: 'quinta-voy', forma: 'voy-al', it: 'vado al parco', es: 'voy al parque' },
    { id: 'qi-voy-escuela', tappa: 'quinta-voy', forma: 'voy-al', it: 'vado a scuola', es: 'voy a la escuela',
      trappole: [{ es: 'voy a escuela', perche: 'Escuela vuole la anche se l’italiano non la dice: a la escuela' }] },
    { id: 'qi-vamos-cine', tappa: 'quinta-voy', forma: 'voy-al', it: 'andiamo al cinema', es: 'vamos al cine' },
    { id: 'qi-tom-zoologico', tappa: 'quinta-voy', forma: 'voy-al', it: 'Tom va allo zoo', es: 'Tom va al zoológico' },
    { id: 'qi-laura-biblioteca', tappa: 'quinta-voy', forma: 'voy-al', it: 'Laura va in biblioteca',
      es: 'Laura va a la biblioteca' },
    { id: 'qi-mama-estacion', tappa: 'quinta-voy', forma: 'voy-al', it: 'la mamma va alla stazione',
      es: 'mamá va a la estación' },
    { id: 'qi-adonde-vas', tappa: 'quinta-voy', forma: 'voy-al', it: 'dove vai oggi?', es: 'adónde vas hoy',
      varianti: ['a dónde vas hoy'],
      trappole: [{ es: 'adonde vas hoy', perche: 'Per chiedere si scrive con l’accento: adónde' },
                 { es: 'adónde va hoy', it: 'dove va oggi?', perche: 'Vas è «tu vai», va è «lui va»' },
                 { es: 'adónde vamos hoy', it: 'dove andiamo oggi?', perche: 'Vas è «tu vai», vamos è «noi andiamo»' }] },
    { id: 'qi-ellos-museo', tappa: 'quinta-voy', forma: 'voy-al', it: 'loro vanno al museo', es: 'ellos van al museo' },
    { id: 'qi-no-hospital', tappa: 'quinta-voy', forma: 'voy-al', it: 'oggi non vado all’ospedale',
      es: 'hoy no voy al hospital' },
    { id: 'qi-vas-banco', tappa: 'quinta-voy', forma: 'voy-al', it: 'vai in banca?', es: 'vas al banco' },
    { id: 'qi-sabado-zoologico', tappa: 'quinta-voy', forma: 'voy-al', it: 'il sabato andiamo allo zoo',
      es: 'el sábado vamos al zoológico' },
    { id: 'qi-ella-tienda', tappa: 'quinta-voy', forma: 'voy-al', it: 'lei va al negozio', es: 'ella va a la tienda' },
    { id: 'qi-vengo-cine', tappa: 'quinta-voy', forma: 'voy-al', it: 'vengo dal cinema', es: 'vengo del cine' },
    { id: 'qi-leo-tienda', tappa: 'quinta-voy', forma: 'voy-al', it: 'Leo viene dal negozio e va al parco',
      es: 'Leo viene de la tienda y va al parque' },
    { id: 'qi-amigos-parque', tappa: 'quinta-voy', forma: 'voy-al', it: 'i miei amici vengono dal parco',
      es: 'mis amigos vienen del parque' },
    { id: 'qi-papa-banco', tappa: 'quinta-voy', forma: 'voy-al', it: 'papà viene dalla banca',
      es: 'papá viene del banco' },
    { id: 'qi-vienes-museo', tappa: 'quinta-voy', forma: 'voy-al', it: 'vieni dal museo?', es: 'vienes del museo' },

    /* ── Gira a sinistra: la strada ── */
    { id: 'qi-gira-izquierda', tappa: 'quinta-gira', forma: 'direcciones', it: 'gira a sinistra',
      es: 'gira a la izquierda' },
    { id: 'qi-gira-esquina', tappa: 'quinta-gira', forma: 'direcciones', it: 'all’angolo gira a destra',
      es: 'en la esquina gira a la derecha' },
    { id: 'qi-rotonda', tappa: 'quinta-gira', forma: 'direcciones', it: 'alla rotonda gira a sinistra',
      es: 'en la rotonda gira a la izquierda' },
    { id: 'qi-hospital-izquierda', tappa: 'quinta-gira', forma: 'direcciones', it: 'l’ospedale è a sinistra?',
      es: 'el hospital está a la izquierda' },
    { id: 'qi-zoologico-derecha', tappa: 'quinta-gira', forma: 'direcciones',
      it: 'lo zoo non è a sinistra, è a destra', es: 'el zoológico no está a la izquierda está a la derecha',
      niente: ['sinistra-destra', 'negazione-tolta'],
      trappole: [{ es: 'el zoológico no está a la derecha está a la izquierda', it: 'lo zoo non è a destra, è a sinistra',
                   perche: 'Izquierda è «sinistra», derecha è «destra»' }] },
    { id: 'qi-sigue-plaza', tappa: 'quinta-gira', forma: 'direcciones', it: 'vai dritto fino alla piazza',
      es: 'sigue recto hasta la plaza' },
    { id: 'qi-sigue-semaforo', tappa: 'quinta-gira', forma: 'direcciones', it: 'vai avanti fino al semaforo',
      es: 'sigue hasta el semáforo',
      trappole: [{ es: 'sigue hasta al semáforo', perche: 'Al è solo a + el: dopo hasta resta el' }] },
    { id: 'qi-cruza-calle', tappa: 'quinta-gira', forma: 'direcciones', it: 'attraversa la strada',
      es: 'cruza la calle' },
    { id: 'qi-cruza-plaza', tappa: 'quinta-gira', forma: 'direcciones', it: 'attraversa la piazza e poi gira a destra',
      es: 'cruza la plaza y luego gira a la derecha' },
    { id: 'qi-sigue-vereda', tappa: 'quinta-gira', forma: 'direcciones', it: 'vai avanti sul marciapiede',
      es: 'sigue por la vereda' },
    { id: 'qi-banco-lado-parque', tappa: 'quinta-gira', forma: 'direcciones', it: 'la banca è accanto al parco',
      es: 'el banco está al lado del parque' },
    { id: 'qi-parada-lado-escuela', tappa: 'quinta-gira', forma: 'direcciones', it: 'la fermata è accanto alla scuola',
      es: 'la parada está al lado de la escuela' },
    { id: 'qi-casa-lado-tienda', tappa: 'quinta-gira', forma: 'direcciones', it: 'la mia casa è accanto al negozio',
      es: 'mi casa está al lado de la tienda' },
    { id: 'qi-cine-enfrente-museo', tappa: 'quinta-gira', forma: 'direcciones', it: 'il cinema è di fronte al museo',
      es: 'el cine está enfrente del museo' },
    { id: 'qi-letrero-enfrente', tappa: 'quinta-gira', forma: 'direcciones',
      it: 'il cartello è di fronte alla stazione', es: 'el letrero está enfrente de la estación' },
    { id: 'qi-tienda-entre', tappa: 'quinta-gira', forma: 'direcciones', it: 'il negozio è tra la banca e il cinema',
      es: 'la tienda está entre el banco y el cine' },

    /* ── Quanto costa? ── */
    { id: 'qi-cuanto-pelota', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'quanto costa la palla?',
      es: 'cuánto cuesta la pelota' },
    { id: 'qi-cuanto-jugo', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'quanto costa il succo?',
      es: 'cuánto cuesta el jugo' },
    { id: 'qi-cuanto-manzanas', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'quanto costano le mele?',
      es: 'cuánto cuestan las manzanas' },
    { id: 'qi-cuanto-zapatos', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'quanto costano le scarpe?',
      es: 'cuánto cuestan los zapatos' },
    { id: 'qi-cuesta-diez', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'costa dieci boliviani',
      es: 'cuesta diez bolivianos' },
    { id: 'qi-libro-veinte', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'il libro costa venti boliviani',
      es: 'el libro cuesta veinte bolivianos' },
    { id: 'qi-pan-boliviano', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'il pane costa un boliviano',
      es: 'el pan cuesta un boliviano' },
    { id: 'qi-manzana-centavos', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'la mela costa cinquanta centesimi',
      es: 'la manzana cuesta cincuenta centavos' },
    { id: 'qi-jugo-tres', tappa: 'quinta-cuanto', forma: 'cuanto',
      it: 'il succo costa tre boliviani e cinquanta centesimi', es: 'el jugo cuesta tres bolivianos y cincuenta centavos' },
    { id: 'qi-galletas-cinco', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'i biscotti costano cinque boliviani',
      es: 'las galletas cuestan cinco bolivianos' },
    { id: 'qi-uvas-mucho', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'l’uva non costa molto',
      es: 'las uvas no cuestan mucho' },
    { id: 'qi-monopatin-caro', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'il monopattino è molto caro',
      es: 'el monopatín es muy caro' },
    { id: 'qi-peluche-barato', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'il peluche è economico',
      es: 'el peluche es barato' },
    { id: 'qi-libro-caro-dinero', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'il libro è caro e non ho soldi',
      es: 'el libro es caro y no tengo dinero' },
    { id: 'qi-moneda-boliviano', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'ho una moneta da un boliviano',
      es: 'tengo una moneda de un boliviano' },
    { id: 'qi-billete-veinte', tappa: 'quinta-cuanto', forma: 'cuanto', it: 'ho una banconota da venti boliviani',
      es: 'tengo un billete de veinte bolivianos' },

    /* ── Il cane di Tom: de, del, de la ── */
    { id: 'qi-perro-tom', tappa: 'quinta-de', forma: 'de', it: 'è il cane di Tom', es: 'es el perro de Tom',
      trappole: [{ es: 'es el perro del Tom', perche: 'Davanti a un nome come Tom niente el: de Tom' }] },
    { id: 'qi-pelota-pip', tappa: 'quinta-de', forma: 'de', it: 'è la palla di Pip', es: 'es la pelota de Pip',
      trappole: [{ es: 'es la pelota del Pip', perche: 'Davanti a un nome come Pip niente el: de Pip' }] },
    { id: 'qi-muneca-laura', tappa: 'quinta-de', forma: 'de', it: 'la bambola di Laura è nuova',
      es: 'la muñeca de Laura es nueva' },
    { id: 'qi-no-perro-leo', tappa: 'quinta-de', forma: 'de', it: 'non è il cane di Leo', es: 'no es el perro de Leo' },
    { id: 'qi-zapatos-papa', tappa: 'quinta-de', forma: 'de', it: 'sono le scarpe di papà',
      es: 'son los zapatos de papá' },
    { id: 'qi-libro-hermano', tappa: 'quinta-de', forma: 'de', it: 'è il libro di mio fratello',
      es: 'es el libro de mi hermano' },
    { id: 'qi-casa-abuelos', tappa: 'quinta-de', forma: 'de', it: 'è la casa dei miei nonni',
      es: 'es la casa de mis abuelos' },
    { id: 'qi-gato-abuela', tappa: 'quinta-de', forma: 'de', it: 'è il gatto della nonna', es: 'es el gato de la abuela' },
    { id: 'qi-mochila-maestra', tappa: 'quinta-de', forma: 'de', it: 'lo zaino della maestra è blu',
      es: 'la mochila de la maestra es azul' },
    { id: 'qi-casa-tio', tappa: 'quinta-de', forma: 'de', it: 'la casa dello zio è grande', es: 'la casa del tío es grande' },
    { id: 'qi-pelota-perro', tappa: 'quinta-de', forma: 'de', it: 'è la palla del cane', es: 'es la pelota del perro' },
    { id: 'qi-ojos-gato', tappa: 'quinta-de', forma: 'de', it: 'gli occhi del gatto sono verdi',
      es: 'los ojos del gato son verdes' },
    { id: 'qi-auto-policia', tappa: 'quinta-de', forma: 'de', it: 'l’auto del poliziotto è bianca',
      es: 'el auto del policía es blanco' },
    { id: 'qi-gorra-doctor', tappa: 'quinta-de', forma: 'de', it: 'è il cappellino del dottore',
      es: 'es la gorra del doctor' },
    { id: 'qi-de-quien-libro', tappa: 'quinta-de', forma: 'de', it: 'di chi è il libro?', es: 'de quién es el libro',
      trappole: [{ es: 'quién es el libro', perche: 'Di chi si dice de quién, con de davanti' }] },
    { id: 'qi-de-quien-gorra', tappa: 'quinta-de', forma: 'de', it: 'di chi è il cappellino rosso?',
      es: 'de quién es la gorra roja' },
    { id: 'qi-de-quien-zapatos', tappa: 'quinta-de', forma: 'de', it: 'di chi sono le scarpe?',
      es: 'de quién son los zapatos' },

    /* ── Voglio, posso: querer, poder, jugar, dormir ── */
    { id: 'qi-tom-quiere-perro', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'Tom vuole un cane',
      es: 'Tom quiere un perro' },
    { id: 'qi-laura-bicicleta', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'Laura vuole una bicicletta nuova',
      es: 'Laura quiere una bicicleta nueva' },
    { id: 'qi-quieres-leche', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'vuoi un po’ di latte?',
      es: 'quieres un poco de leche' },
    { id: 'qi-yo-no-quiero-sopa', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'io non voglio la minestra',
      es: 'yo no quiero sopa' },
    { id: 'qi-quiero-jugar', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'voglio giocare', es: 'quiero jugar' },
    { id: 'qi-puedo-ir-parque', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'posso andare al parco?',
      es: 'puedo ir al parque' },
    { id: 'qi-no-puedo-dormir', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'non posso dormire',
      es: 'no puedo dormir' },
    { id: 'qi-quieres-comer', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'vuoi mangiare la pizza?',
      es: 'quieres comer pizza' },
    { id: 'qi-podemos-tenis', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'possiamo giocare a tennis',
      es: 'podemos jugar al tenis' },
    { id: 'qi-queremos-zoologico', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'noi vogliamo andare allo zoo',
      es: 'nosotros queremos ir al zoológico' },
    { id: 'qi-ella-no-puede-venir', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'lei oggi non può venire',
      es: 'ella no puede venir hoy' },
    { id: 'qi-ellos-quieren-salir', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'loro vogliono uscire',
      es: 'ellos quieren salir' },
    { id: 'qi-puedes-ayudar', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'puoi aiutare la mamma?',
      es: 'puedes ayudar a mamá' },
    { id: 'qi-leo-torta', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'Leo vuole fare una torta',
      es: 'Leo quiere hacer una torta' },
    { id: 'qi-yo-juego-perro', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'io gioco con il mio cane',
      es: 'yo juego con mi perro' },
    { id: 'qi-tu-juegas', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'tu giochi con Leo?',
      es: 'tú juegas con Leo' },
    { id: 'qi-nosotros-jugamos', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'noi giochiamo al parco',
      es: 'nosotros jugamos en el parque' },
    { id: 'qi-yo-duermo', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'io dormo molto', es: 'yo duermo mucho' },
    { id: 'qi-pip-duerme', tappa: 'quinta-quiero', forma: 'quiero-puedo', it: 'Pip dorme sul sofà',
      es: 'Pip duerme en el sofá' },
  ],
}
