// Le frasi componibili del mondo «seconda», La baia delle palme: i plurali,
// gustar, i possessivi, ser e tener. Formato e regole in
// docs/lingue/spagnolo-motore.md; gli id cominciano con se- e sono chiavi SRS.
export default {
  mondo: 'seconda',
  frasi: [
    /* ── Due gatti, i gatti ── */
    { id: 'se-dos-gatos', tappa: 'seconda-plural', forma: 'plural', it: 'sono due gatti', es: 'son dos gatos' },
    { id: 'se-tres-peces', tappa: 'seconda-plural', forma: 'plural', it: 'sono tre pesci rossi', es: 'son tres peces rojos' },
    { id: 'se-cinco-ratones', tappa: 'seconda-plural', forma: 'plural', it: 'sono cinque topi bianchi', es: 'son cinco ratones blancos' },
    { id: 'se-cuatro-patines', tappa: 'seconda-plural', forma: 'plural', it: 'sono quattro pattini', es: 'son cuatro patines' },
    { id: 'se-libros-azules', tappa: 'seconda-plural', forma: 'plural', it: 'sono dei libri blu', es: 'son unos libros azules' },
    { id: 'se-gato-y-perros', tappa: 'seconda-plural', forma: 'plural', it: 'sono un gatto e due cani', es: 'son un gato y dos perros' },
    { id: 'se-son-conejos', tappa: 'seconda-plural', forma: 'plural', it: 'sono conigli bianchi?', es: 'son conejos blancos' },
    { id: 'se-los-lapices', tappa: 'seconda-plural', forma: 'plural', it: 'le matite sono rosse', es: 'los lápices son rojos',
      niente: ['negazione-aggiunta'] },
    { id: 'se-las-vacas', tappa: 'seconda-plural', forma: 'plural', it: 'le mucche sono nere', es: 'las vacas son negras',
      niente: ['negazione-aggiunta'] },
    { id: 'se-estos-huevos', tappa: 'seconda-plural', forma: 'plural', it: 'queste uova sono bianche', es: 'estos huevos son blancos' },
    { id: 'se-estas-galletas', tappa: 'seconda-plural', forma: 'plural', it: 'questi biscotti sono marroni', es: 'estas galletas son marrones' },
    { id: 'se-patos-amarillos', tappa: 'seconda-plural', forma: 'plural', it: 'le anatre sono gialle?', es: 'los patos son amarillos' },
    { id: 'se-perros-no-negros', tappa: 'seconda-plural', forma: 'plural', it: 'i cani non sono neri', es: 'los perros no son negros' },
    { id: 'se-ocho-platanos', tappa: 'seconda-plural', forma: 'plural', it: 'sono otto banane gialle', es: 'son ocho plátanos amarillos' },
    { id: 'se-dos-mapas', tappa: 'seconda-plural', forma: 'plural', it: 'sono due mappe rosse', es: 'son dos mapas rojos' },
    { id: 'se-disfraces', tappa: 'seconda-plural', forma: 'plural', it: 'i costumi sono neri', es: 'los disfraces son negros' },

    /* ── Mi piace! ── */
    { id: 'se-gusta-chocolate', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace il cioccolato', es: 'me gusta el chocolate' },
    { id: 'se-gusta-pizza', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace la pizza', es: 'me gusta la pizza' },
    { id: 'se-gusta-mucho-arroz', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace tanto il riso', es: 'me gusta mucho el arroz' },
    { id: 'se-gusta-jugo', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace il succo', es: 'me gusta el jugo' },
    { id: 'se-gustan-uvas', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace l’uva', es: 'me gustan las uvas' },
    { id: 'se-gustan-fideos', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piace la pasta', es: 'me gustan los fideos' },
    { id: 'se-gustan-galletas', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piacciono tanto i biscotti', es: 'me gustan mucho las galletas' },
    { id: 'se-gustan-perros', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piacciono i cani', es: 'me gustan los perros' },
    { id: 'se-tambien-papas', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'mi piacciono anche le patate', es: 'también me gustan las papas',
      niente: ['negazione-aggiunta'] },
    { id: 'se-no-gusta-sopa', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'non mi piace la minestra', es: 'no me gusta la sopa' },
    { id: 'se-no-gustan-tomates', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'non mi piacciono i pomodori', es: 'no me gustan los tomates' },
    { id: 'se-no-gusta-queso', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'non mi piace il formaggio', es: 'no me gusta el queso' },
    { id: 'se-te-gusta-torta', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'ti piace la torta?', es: 'te gusta la torta' },
    { id: 'se-te-gustan-frutillas', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'ti piacciono le fragole?', es: 'te gustan las frutillas' },
    { id: 'se-no-te-gusta-ensalada', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'non ti piace l’insalata?', es: 'no te gusta la ensalada' },
    { id: 'se-a-mi-leche', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'a me piace il latte', es: 'a mí me gusta la leche',
      trappole: [{ es: 'a mí gusta la leche', perche: 'Anche con a mí ci vuole me: a mí me gusta' }] },
    { id: 'se-a-mi-tambien-gatos', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'anche a me piacciono i gatti', es: 'a mí también me gustan los gatos',
      trappole: [{ es: 'a mí también gustan los gatos', perche: 'Anche con a mí ci vuole me: a mí también me gustan' }],
      niente: ['gustar-io'] },
    { id: 'se-a-ti-zanahorias', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'a te piacciono le carote?', es: 'a ti te gustan las zanahorias',
      trappole: [{ es: 'a ti gustan las zanahorias', perche: 'Anche con a ti ci vuole te: a ti te gustan' }] },
    { id: 'se-a-mi-no-arroz', tappa: 'seconda-gusta', forma: 'me-gusta', it: 'a me non piace il riso', es: 'a mí no me gusta el arroz',
      trappole: [{ es: 'a mí no gusta el arroz', perche: 'Anche con a mí ci vuole me: a mí no me gusta' }],
      niente: ['gustar-io'] },

    /* ── Questo è mio ── */
    { id: 'se-mi-perro', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'è il mio cane', es: 'es mi perro',
      trappole: [{ es: 'es el mi perro', perche: 'Davanti a mi niente el: mi perro' }] },
    { id: 'se-mi-mama', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'questa è la mia mamma', es: 'esta es mi mamá' },
    { id: 'se-leo-mi-amigo', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'Leo è mio amico', es: 'Leo es mi amigo' },
    { id: 'se-mi-vestido', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'il mio vestito è blu', es: 'mi vestido es azul',
      trappole: [{ es: 'el mi vestido es azul', perche: 'Davanti a mi niente el: mi vestido' }] },
    { id: 'se-no-mi-sombrero', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'non è il mio cappello', es: 'no es mi sombrero' },
    { id: 'se-el-mi-papa', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'lui è il mio papà', es: 'él es mi papá' },
    { id: 'se-tu-gorra', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'è il tuo berretto', es: 'es tu gorra' },
    { id: 'se-tu-tio', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'è tuo zio?', es: 'es tu tío' },
    { id: 'se-tu-bufanda', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'la tua sciarpa è rossa', es: 'tu bufanda es roja',
      trappole: [{ es: 'la tu bufanda es roja', perche: 'Davanti a tu niente la: tu bufanda' }] },
    { id: 'se-su-abrigo', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'è il suo cappotto', es: 'es su abrigo',
      trappole: [{ es: 'es el su abrigo', perche: 'Davanti a su niente el: su abrigo' }] },
    { id: 'se-su-hermana', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'lei è sua sorella', es: 'ella es su hermana' },
    { id: 'se-su-camiseta', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'la sua maglietta è verde', es: 'su camiseta es verde',
      trappole: [{ es: 'la su camiseta es verde', perche: 'Davanti a su niente la: su camiseta' }] },
    { id: 'se-mis-gatos', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'sono i miei gatti', es: 'son mis gatos',
      trappole: [{ es: 'son los mis gatos', perche: 'Davanti a mis niente los: mis gatos' }] },
    { id: 'se-mis-abuelos', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'questi sono i miei nonni', es: 'estos son mis abuelos' },
    { id: 'se-tus-zapatos', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'sono le tue scarpe?', es: 'son tus zapatos' },
    { id: 'se-tus-calcetines', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'i tuoi calzini sono rossi', es: 'tus calcetines son rojos',
      trappole: [{ es: 'los tus calcetines son rojos', perche: 'Davanti a tus niente los: tus calcetines' }] },
    { id: 'se-sus-guantes', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'sono i suoi guanti', es: 'son sus guantes' },
    { id: 'se-sus-pantalones', tappa: 'seconda-mi', forma: 'mi-tu-su', it: 'i suoi pantaloni sono neri', es: 'sus pantalones son negros' },

    /* ── Io sono, tu sei ── */
    { id: 'se-yo-soy-alto', tappa: 'seconda-soy', forma: 'ser', it: 'io sono alto', es: 'yo soy alto' },
    { id: 'se-soy-laura', tappa: 'seconda-soy', forma: 'ser', it: 'io sono Laura e sono alta', es: 'yo soy Laura y soy alta' },
    { id: 'se-no-soy-malo', tappa: 'seconda-soy', forma: 'ser', it: 'io non sono cattivo', es: 'yo no soy malo' },
    { id: 'se-soy-muy-fuerte', tappa: 'seconda-soy', forma: 'ser', it: 'sono molto forte', es: 'soy muy fuerte',
      trappole: [{ es: 'es muy fuerte', it: 'è molto forte', perche: 'Io sono: soy. Es vuol dire «è»' }] },
    { id: 'se-tu-eres-fuerte', tappa: 'seconda-soy', forma: 'ser', it: 'tu sei forte', es: 'tú eres fuerte' },
    { id: 'se-eres-mi-amigo', tappa: 'seconda-soy', forma: 'ser', it: 'tu sei mio amico?', es: 'tú eres mi amigo',
      niente: ['mio-tuo'] },
    { id: 'se-eres-muy-alta', tappa: 'seconda-soy', forma: 'ser', it: 'tu sei molto alta', es: 'tú eres muy alta' },
    { id: 'se-no-eres-malo', tappa: 'seconda-soy', forma: 'ser', it: 'tu non sei cattivo', es: 'tú no eres malo' },
    { id: 'se-ella-es-baja', tappa: 'seconda-soy', forma: 'ser', it: 'lei è bassa e io sono alto', es: 'ella es baja y yo soy alto' },
    { id: 'se-el-es-pequeno', tappa: 'seconda-soy', forma: 'ser', it: 'lui è piccolo e io sono grande', es: 'él es pequeño y yo soy grande' },
    { id: 'se-tom-hermano', tappa: 'seconda-soy', forma: 'ser', it: 'Tom è mio fratello e io sono sua sorella', es: 'Tom es mi hermano y yo soy su hermana' },
    { id: 'se-yo-leo-el-tom', tappa: 'seconda-soy', forma: 'ser', it: 'io sono Leo e lui è Tom', es: 'yo soy Leo y él es Tom' },
    { id: 'se-somos-amigos', tappa: 'seconda-soy', forma: 'ser', it: 'noi siamo amici', es: 'nosotros somos amigos' },
    { id: 'se-somos-pequenos', tappa: 'seconda-soy', forma: 'ser', it: 'siamo piccoli', es: 'somos pequeños',
      trappole: [{ es: 'son pequeños', perche: 'Noi siamo: somos. Son è «sono» di loro' }, { es: 'somos pequeño', perche: 'Siamo in tanti: pequeños, al plurale' }] },
    { id: 'se-ellos-fuertes', tappa: 'seconda-soy', forma: 'ser', it: 'loro sono forti', es: 'ellos son fuertes' },
    { id: 'se-ellas-hermanas', tappa: 'seconda-soy', forma: 'ser', it: 'loro sono le mie sorelle', es: 'ellas son mis hermanas' },
    { id: 'se-zapatos-nuevos', tappa: 'seconda-soy', forma: 'ser', it: 'le mie scarpe sono nuove', es: 'mis zapatos son nuevos',
      niente: ['negazione-aggiunta'] },

    /* ── Ho un…, ho fame ── */
    { id: 'se-tengo-perro', tappa: 'seconda-tengo', forma: 'tener', it: 'ho un cane e due gatti', es: 'tengo un perro y dos gatos' },
    { id: 'se-tengo-hermana', tappa: 'seconda-tengo', forma: 'tener', it: 'io ho una sorella', es: 'yo tengo una hermana' },
    { id: 'se-tengo-lapices', tappa: 'seconda-tengo', forma: 'tener', it: 'ho quindici matite', es: 'tengo quince lápices' },
    { id: 'se-tienes-hermanos', tappa: 'seconda-tengo', forma: 'tener', it: 'tu hai due fratelli?', es: 'tú tienes dos hermanos' },
    { id: 'se-cuantos-lapices', tappa: 'seconda-tengo', forma: 'tener', it: 'quante matite hai?', es: 'cuántos lápices tienes' },
    { id: 'se-tengo-siete', tappa: 'seconda-tengo', forma: 'tener', it: 'ho sette anni', es: 'tengo siete años' },
    { id: 'se-yo-tengo-doce', tappa: 'seconda-tengo', forma: 'tener', it: 'io ho dodici anni', es: 'yo tengo doce años' },
    { id: 'se-tu-tienes-nueve', tappa: 'seconda-tengo', forma: 'tener', it: 'tu hai nove anni', es: 'tú tienes nueve años' },
    { id: 'se-cuantos-anos', tappa: 'seconda-tengo', forma: 'tener', it: 'quanti anni hai?', es: 'cuántos años tienes' },
    { id: 'se-tengo-hambre', tappa: 'seconda-tengo', forma: 'tener', it: 'ho fame', es: 'tengo hambre' },
    { id: 'se-tengo-sed', tappa: 'seconda-tengo', forma: 'tener', it: 'io ho sete', es: 'yo tengo sed' },
    { id: 'se-tienes-mucho-frio', tappa: 'seconda-tengo', forma: 'tener', it: 'hai tanto freddo?', es: 'tienes mucho frío' },
    { id: 'se-mucho-sueno', tappa: 'seconda-tengo', forma: 'tener', it: 'ho tanto sonno', es: 'tengo mucho sueño' },
    { id: 'se-no-tengo-miedo', tappa: 'seconda-tengo', forma: 'tener', it: 'non ho paura', es: 'no tengo miedo' },
    { id: 'se-mucho-calor', tappa: 'seconda-tengo', forma: 'tener', it: 'ho tanto caldo', es: 'tengo mucho calor' },
    { id: 'se-no-tienes-hambre', tappa: 'seconda-tengo', forma: 'tener', it: 'non hai fame?', es: 'no tienes hambre' },

    /* ── Lei ha… ── */
    { id: 'se-tom-hambre', tappa: 'seconda-tiene', forma: 'tiene', it: 'Tom ha fame', es: 'Tom tiene hambre' },
    { id: 'se-laura-ocho', tappa: 'seconda-tiene', forma: 'tiene', it: 'Laura ha otto anni', es: 'Laura tiene ocho años' },
    { id: 'se-ella-no-miedo', tappa: 'seconda-tiene', forma: 'tiene', it: 'lei non ha paura', es: 'ella no tiene miedo' },
    { id: 'se-bebe-sueno', tappa: 'seconda-tiene', forma: 'tiene', it: 'il bebè ha sonno?', es: 'el bebé tiene sueño' },
    { id: 'se-hermana-muneca', tappa: 'seconda-tiene', forma: 'tiene', it: 'mia sorella ha una bambola nuova', es: 'mi hermana tiene una muñeca nueva' },
    { id: 'se-cuantos-anos-abuelo', tappa: 'seconda-tiene', forma: 'tiene', it: 'quanti anni ha tuo nonno?', es: 'cuántos años tiene tu abuelo' },
    { id: 'se-ella-ojos', tappa: 'seconda-tiene', forma: 'tiene', it: 'lei ha gli occhi azzurri', es: 'ella tiene los ojos azules' },
    { id: 'se-el-pelo', tappa: 'seconda-tiene', forma: 'tiene', it: 'lui ha i capelli neri', es: 'él tiene el pelo negro' },
    { id: 'se-perro-nariz', tappa: 'seconda-tiene', forma: 'tiene', it: 'il cane ha il naso nero', es: 'el perro tiene la nariz negra' },
    { id: 'se-ellos-sueno', tappa: 'seconda-tiene', forma: 'tiene', it: 'loro hanno sonno', es: 'ellos tienen sueño' },
    { id: 'se-abuelos-perro', tappa: 'seconda-tiene', forma: 'tiene', it: 'i miei nonni hanno un cane', es: 'mis abuelos tienen un perro' },
    { id: 'se-gatos-ojos', tappa: 'seconda-tiene', forma: 'tiene', it: 'i gatti hanno gli occhi verdi', es: 'los gatos tienen los ojos verdes' },
    { id: 'se-ellas-sombreros', tappa: 'seconda-tiene', forma: 'tiene', it: 'loro hanno dei cappelli rossi', es: 'ellas tienen unos sombreros rojos' },
    { id: 'se-tenemos-sed', tappa: 'seconda-tiene', forma: 'tiene', it: 'noi abbiamo sete', es: 'nosotros tenemos sed' },
    { id: 'se-tenemos-manos', tappa: 'seconda-tiene', forma: 'tiene', it: 'abbiamo due mani', es: 'tenemos dos manos' },
    { id: 'se-tenemos-gato', tappa: 'seconda-tiene', forma: 'tiene', it: 'abbiamo un gatto bianco', es: 'tenemos un gato blanco' },
  ],
}
