// Le frasi componibili del mondo «terza», L’altopiano d’autunno: estar per i
// posti, hay, le domande con l’accento, i giorni e i mesi, il tempo, ser o
// estar. Formato e regole in docs/lingue/spagnolo-motore.md; gli id
// cominciano con te- e sono chiavi SRS.
export default {
  mondo: 'terza',
  frasi: [
    /* ── Dov’è? ── */
    { id: 'te-gato-cocina', tappa: 'terza-donde', forma: 'esta-en', it: 'il gatto è in cucina', es: 'el gato está en la cocina' },
    { id: 'te-perro-jardin', tappa: 'terza-donde', forma: 'esta-en', it: 'il cane è in giardino', es: 'el perro está en el jardín' },
    { id: 'te-mama-en-casa', tappa: 'terza-donde', forma: 'esta-en', it: 'la mamma è a casa', es: 'mamá está en casa',
      trappole: [
        { es: 'papá está en casa', it: 'papà è a casa', parola: 'mamá', perche: 'Mamá è «mamma», papá è «papà»' }] },
    { id: 'te-auto-garaje', tappa: 'terza-donde', forma: 'esta-en', it: 'la macchina è in garage', es: 'el auto está en el garaje' },
    { id: 'te-cuadro-no-cocina', tappa: 'terza-donde', forma: 'esta-en', it: 'il quadro non è in cucina', es: 'el cuadro no está en la cocina' },
    { id: 'te-abuela-aqui', tappa: 'terza-donde', forma: 'esta-en', it: 'la nonna è qui', es: 'la abuela está aquí' },
    { id: 'te-gatos-sofa', tappa: 'terza-donde', forma: 'esta-en', it: 'i gatti sono sul divano', es: 'los gatos están en el sofá',
      varianti: ['los gatos están sobre el sofá'] },
    { id: 'te-libro-sobre-mesa', tappa: 'terza-donde', forma: 'esta-en', it: 'il libro è sopra il tavolo', es: 'el libro está sobre la mesa' },
    { id: 'te-pelota-debajo-cama', tappa: 'terza-donde', forma: 'esta-en', it: 'la palla è sotto il letto', es: 'la pelota está debajo de la cama' },
    { id: 'te-zapatos-debajo-silla', tappa: 'terza-donde', forma: 'esta-en', it: 'le scarpe sono sotto la sedia', es: 'los zapatos están debajo de la silla' },
    { id: 'te-pip-detras-puerta', tappa: 'terza-donde', forma: 'esta-en', it: 'Pip è dietro la porta', es: 'Pip está detrás de la puerta' },
    { id: 'te-lampara-al-lado-cama', tappa: 'terza-donde', forma: 'esta-en', it: 'la lampada è accanto al letto', es: 'la lámpara está al lado de la cama' },
    { id: 'te-reloj-cerca-ventana', tappa: 'terza-donde', forma: 'esta-en', it: 'l’orologio è vicino alla finestra', es: 'el reloj está cerca de la ventana' },
    { id: 'te-donde-gato', tappa: 'terza-donde', forma: 'esta-en', it: 'dov’è il gatto?', es: 'dónde está el gato' },
    { id: 'te-donde-mochila', tappa: 'terza-donde', forma: 'esta-en', it: 'dov’è il mio zaino?', es: 'dónde está mi mochila' },
    { id: 'te-donde-tijeras', tappa: 'terza-donde', forma: 'esta-en', it: 'dove sono le forbici?', es: 'dónde están las tijeras' },
    { id: 'te-donde-estas', tappa: 'terza-donde', forma: 'esta-en', it: 'dove sei?', es: 'dónde estás' },
    { id: 'te-estoy-bano', tappa: 'terza-donde', forma: 'esta-en', it: 'sono in bagno', es: 'estoy en el baño' },
    { id: 'te-estamos-jardin', tappa: 'terza-donde', forma: 'esta-en', it: 'siamo in giardino', es: 'estamos en el jardín' },
    { id: 'te-estoy-aqui', tappa: 'terza-donde', forma: 'esta-en', it: 'sono qui, nella mia camera', es: 'estoy aquí en mi dormitorio' },

    /* ── C’è, ci sono ── */
    { id: 'te-hay-gato-cocina', tappa: 'terza-hay', forma: 'hay', it: 'c’è un gatto in cucina', es: 'hay un gato en la cocina' },
    { id: 'te-hay-perro-jardin', tappa: 'terza-hay', forma: 'hay', it: 'c’è un cane in giardino', es: 'hay un perro en el jardín' },
    { id: 'te-hay-lampara-mesa', tappa: 'terza-hay', forma: 'hay', it: 'c’è una lampada sul tavolo', es: 'hay una lámpara sobre la mesa',
      varianti: ['hay una lámpara en la mesa'] },
    { id: 'te-hay-espejo-bano', tappa: 'terza-hay', forma: 'hay', it: 'c’è uno specchio in bagno', es: 'hay un espejo en el baño' },
    { id: 'te-hay-raton-cama', tappa: 'terza-hay', forma: 'hay', it: 'c’è un topo sotto il letto', es: 'hay un ratón debajo de la cama' },
    { id: 'te-gato-esta-hay-perro', tappa: 'terza-hay', forma: 'hay', it: 'il gatto è in cucina e c’è un cane in giardino', es: 'el gato está en la cocina y hay un perro en el jardín' },
    { id: 'te-hay-dos-gatos', tappa: 'terza-hay', forma: 'hay', it: 'ci sono due gatti in giardino', es: 'hay dos gatos en el jardín',
      trappole: [
        { es: 'están dos gatos en el jardín', perche: '«Ci sono» si dice hay, non están' }] },
    { id: 'te-hay-tres-sillas', tappa: 'terza-hay', forma: 'hay', it: 'ci sono tre sedie in cucina', es: 'hay tres sillas en la cocina' },
    { id: 'te-hay-cien-globos', tappa: 'terza-hay', forma: 'hay', it: 'ci sono cento palloncini alla festa', es: 'hay cien globos en la fiesta' },
    { id: 'te-hay-setenta-galletas', tappa: 'terza-hay', forma: 'hay', it: 'ci sono settanta biscotti nella scatola', es: 'hay setenta galletas en la caja' },
    { id: 'te-hay-unas-manzanas', tappa: 'terza-hay', forma: 'hay', it: 'ci sono delle mele in cucina', es: 'hay unas manzanas en la cocina' },
    { id: 'te-no-hay-leche', tappa: 'terza-hay', forma: 'hay', it: 'non c’è latte in cucina', es: 'no hay leche en la cocina' },
    { id: 'te-no-hay-sillas', tappa: 'terza-hay', forma: 'hay', it: 'non ci sono sedie in giardino', es: 'no hay sillas en el jardín' },
    { id: 'te-no-hay-pan', tappa: 'terza-hay', forma: 'hay', it: 'non c’è pane sul tavolo', es: 'no hay pan en la mesa',
      varianti: ['no hay pan sobre la mesa'] },
    { id: 'te-hay-ducha', tappa: 'terza-hay', forma: 'hay', it: 'c’è una doccia in bagno?', es: 'hay una ducha en el baño' },
    { id: 'te-hay-perros', tappa: 'terza-hay', forma: 'hay', it: 'ci sono cani in giardino?', es: 'hay perros en el jardín' },
    { id: 'te-cuantos-gatos-hay', tappa: 'terza-hay', forma: 'hay', it: 'quanti gatti ci sono?', es: 'cuántos gatos hay' },
    { id: 'te-cuantas-sillas-hay', tappa: 'terza-hay', forma: 'hay', it: 'quante sedie ci sono in cucina?', es: 'cuántas sillas hay en la cocina' },

    /* ── Chi? Che cosa? Come? ── */
    { id: 'te-que-hay-caja', tappa: 'terza-quien', forma: 'preguntas', it: 'che cosa c’è nella scatola?', es: 'qué hay en la caja' },
    { id: 'te-que-hay-mesa', tappa: 'terza-quien', forma: 'preguntas', it: 'che cosa c’è sul tavolo?', es: 'qué hay en la mesa',
      varianti: ['qué hay sobre la mesa'] },
    { id: 'te-que-tiene-leo', tappa: 'terza-quien', forma: 'preguntas', it: 'che cosa ha Leo?', es: 'qué tiene Leo' },
    { id: 'te-que-tienes-mochila', tappa: 'terza-quien', forma: 'preguntas', it: 'che cosa hai nello zaino?', es: 'qué tienes en la mochila' },
    { id: 'te-cual-tu-libro', tappa: 'terza-quien', forma: 'preguntas', it: 'qual è il tuo libro?', es: 'cuál es tu libro' },
    { id: 'te-donde-esta-papa', tappa: 'terza-quien', forma: 'preguntas', it: 'dov’è papà?', es: 'dónde está papá' },
    { id: 'te-quien-cocina', tappa: 'terza-quien', forma: 'preguntas', it: 'chi c’è in cucina?', es: 'quién está en la cocina' },
    { id: 'te-quien-tu-amigo', tappa: 'terza-quien', forma: 'preguntas', it: 'chi è il tuo amico?', es: 'quién es tu amigo' },
    { id: 'te-quien-tiene-pelota', tappa: 'terza-quien', forma: 'preguntas', it: 'chi ha la palla?', es: 'quién tiene la pelota' },
    { id: 'te-quien-tiene-perro', tappa: 'terza-quien', forma: 'preguntas', it: 'chi ha un cane?', es: 'quién tiene un perro' },
    { id: 'te-como-abuela', tappa: 'terza-quien', forma: 'preguntas', it: 'come sta la nonna?', es: 'cómo está la abuela' },
    { id: 'te-como-tu-casa', tappa: 'terza-quien', forma: 'preguntas', it: 'com’è la tua casa?', es: 'cómo es tu casa' },
    { id: 'te-como-perro-tom', tappa: 'terza-quien', forma: 'preguntas', it: 'com’è il cane di Tom?', es: 'cómo es el perro de Tom' },
    { id: 'te-cuantos-anos', tappa: 'terza-quien', forma: 'preguntas', it: 'quanti anni hai?', es: 'cuántos años tienes' },
    { id: 'te-cuantos-hermanos', tappa: 'terza-quien', forma: 'preguntas', it: 'quanti fratelli hai?', es: 'cuántos hermanos tienes' },
    { id: 'te-cuantas-ventanas', tappa: 'terza-quien', forma: 'preguntas', it: 'quante finestre ha la casa?', es: 'cuántas ventanas tiene la casa' },
    { id: 'te-cuantos-libros-caja', tappa: 'terza-quien', forma: 'preguntas', it: 'quanti libri ci sono nella scatola?', es: 'cuántos libros hay en la caja' },

    /* ── Oggi è lunedì ── */
    { id: 'te-hoy-lunes', tappa: 'terza-hoy', forma: 'hoy-es', it: 'oggi è lunedì', es: 'hoy es lunes' },
    { id: 'te-manana-sabado', tappa: 'terza-hoy', forma: 'hoy-es', it: 'domani è sabato', es: 'mañana es sábado' },
    { id: 'te-hoy-no-domingo', tappa: 'terza-hoy', forma: 'hoy-es', it: 'oggi non è domenica', es: 'hoy no es domingo' },
    { id: 'te-hoy-cumpleanos', tappa: 'terza-hoy', forma: 'hoy-es', it: 'oggi è il mio compleanno', es: 'hoy es mi cumpleaños' },
    { id: 'te-miercoles-jueves', tappa: 'terza-hoy', forma: 'hoy-es', it: 'oggi è mercoledì e domani è giovedì', es: 'hoy es miércoles y mañana es jueves',
      niente: ['oggi-domani'] },
    { id: 'te-sabado-fiesta', tappa: 'terza-hoy', forma: 'hoy-es', it: 'sabato c’è una festa', es: 'el sábado hay una fiesta' },
    { id: 'te-domingo-en-casa', tappa: 'terza-hoy', forma: 'hoy-es', it: 'domenica sono a casa', es: 'el domingo estoy en casa' },
    { id: 'te-cumple-el-lunes', tappa: 'terza-hoy', forma: 'hoy-es', it: 'il mio compleanno è lunedì', es: 'mi cumpleaños es el lunes' },
    { id: 'te-jueves-pizza', tappa: 'terza-hoy', forma: 'hoy-es', it: 'giovedì c’è la pizza', es: 'el jueves hay pizza' },
    { id: 'te-cumple-en-mayo', tappa: 'terza-hoy', forma: 'hoy-es', it: 'il mio compleanno è a maggio', es: 'mi cumpleaños es en mayo' },
    { id: 'te-vacaciones-agosto', tappa: 'terza-hoy', forma: 'hoy-es', it: 'le vacanze sono ad agosto', es: 'las vacaciones son en agosto' },
    { id: 'te-navidad-diciembre', tappa: 'terza-hoy', forma: 'hoy-es', it: 'Natale è a dicembre', es: 'la Navidad es en diciembre' },
    { id: 'te-cumple-tom-junio', tappa: 'terza-hoy', forma: 'hoy-es', it: 'il compleanno di Tom è a giugno', es: 'el cumpleaños de Tom es en junio' },
    { id: 'te-verano-vacaciones', tappa: 'terza-hoy', forma: 'hoy-es', it: 'd’estate ho le vacanze', es: 'en verano tengo vacaciones' },
    { id: 'te-que-dia-hoy', tappa: 'terza-hoy', forma: 'hoy-es', it: 'che giorno è oggi?', es: 'qué día es hoy' },
    { id: 'te-cuando-cumpleanos', tappa: 'terza-hoy', forma: 'hoy-es', it: 'quando è il compleanno di Tom?', es: 'cuándo es el cumpleaños de Tom' },
    { id: 'te-manana-domingo', tappa: 'terza-hoy', forma: 'hoy-es', it: 'domani è domenica?', es: 'mañana es domingo' },
    { id: 'te-vacaciones-julio', tappa: 'terza-hoy', forma: 'hoy-es', it: 'le vacanze sono a luglio?', es: 'las vacaciones son en julio' },

    /* ── Fa freddo, piove ── */
    { id: 'te-hoy-hace-frio', tappa: 'terza-hace', forma: 'hace', it: 'oggi fa freddo', es: 'hoy hace frío',
      trappole: [
        { es: 'hoy tengo frío', it: 'oggi ho freddo', perche: 'Tengo frío è «ho freddo»; il tempo si dice con hace' },
        { es: 'mañana hace frío', it: 'domani fa freddo', parola: 'hoy', perche: 'Hoy è «oggi», mañana è «domani»' }] },
    { id: 'te-verano-calor', tappa: 'terza-hace', forma: 'hace', it: 'd’estate fa caldo', es: 'en verano hace calor',
      trappole: [
        { es: 'en verano tengo calor', it: 'd’estate ho caldo', perche: 'Tengo calor è «ho caldo»; il tempo si dice con hace' }] },
    { id: 'te-hoy-hace-sol', tappa: 'terza-hace', forma: 'hace', it: 'oggi c’è il sole', es: 'hoy hace sol',
      varianti: ['hoy hay sol'],
      trappole: [
        { es: 'hoy hace viento', it: 'oggi c’è vento', parola: 'sol', perche: 'Sol è «sole», viento è «vento»' },
        { es: 'mañana hace sol', it: 'domani c’è il sole', parola: 'hoy', perche: 'Hoy è «oggi», mañana è «domani»' }] },
    { id: 'te-hace-viento', tappa: 'terza-hace', forma: 'hace', it: 'oggi c’è vento', es: 'hoy hace viento',
      varianti: ['hoy hay viento'],
      trappole: [
        { es: 'hoy hace vento', parola: 'viento', perche: 'Vento in spagnolo è viento, con ie' },
        { es: 'hoy hace sol', it: 'oggi c’è il sole', parola: 'viento', perche: 'Viento è «vento», sol è «sole»' }] },
    { id: 'te-no-hace-frio', tappa: 'terza-hace', forma: 'hace', it: 'oggi non fa freddo', es: 'hoy no hace frío',
      trappole: [
        { es: 'hoy no tengo frío', it: 'oggi non ho freddo', perche: 'No tengo frío è «non ho freddo»; il tempo è hace' }] },
    { id: 'te-frio-jardin', tappa: 'terza-hace', forma: 'hace', it: 'fa freddo in giardino?', es: 'hace frío en el jardín' },
    { id: 'te-invierno-mucho-frio', tappa: 'terza-hace', forma: 'hace', it: 'd’inverno fa molto freddo', es: 'en invierno hace mucho frío' },
    { id: 'te-mucho-calor', tappa: 'terza-hace', forma: 'hace', it: 'oggi fa molto caldo', es: 'hoy hace mucho calor' },
    { id: 'te-mucho-viento', tappa: 'terza-hace', forma: 'hace', it: 'c’è tanto vento', es: 'hace mucho viento',
      varianti: ['hay mucho viento'] },
    { id: 'te-hoy-llueve', tappa: 'terza-hace', forma: 'hace', it: 'oggi piove', es: 'hoy llueve',
      trappole: [
        { es: 'hoy lluvia', perche: 'Piove è llueve; lluvia è la pioggia, una cosa' },
        { es: 'hoy hace llueve', perche: 'Llueve basta da solo: niente hace' },
        { es: 'hoy llove', perche: 'Piove si dice llueve, con ue' }] },
    { id: 'te-nieva-jardin', tappa: 'terza-hace', forma: 'hace', it: 'nevica in giardino', es: 'nieva en el jardín' },
    { id: 'te-no-llueve', tappa: 'terza-hace', forma: 'hace', it: 'oggi non piove', es: 'hoy no llueve',
      trappole: [
        { es: 'hoy no lluvia', perche: 'Piove è llueve; lluvia è la pioggia, una cosa' },
        { es: 'hoy no llove', perche: 'Piove si dice llueve, con ue' }] },
    { id: 'te-llueve-mucho', tappa: 'terza-hace', forma: 'hace', it: 'piove tanto', es: 'llueve mucho',
      trappole: [
        { es: 'llueve muy', perche: 'Piove tanto: llueve mucho, non muy' },
        { es: 'lluvia mucho', perche: 'Piove è llueve; lluvia è la pioggia, una cosa' }] },
    { id: 'te-manana-nieva', tappa: 'terza-hace', forma: 'hace', it: 'domani nevica', es: 'mañana nieva',
      trappole: [
        { es: 'mañana nieve', perche: 'Nevica è nieva; nieve è la neve, una cosa' },
        { es: 'mañana hace nieva', perche: 'Nieva basta da solo: niente hace' },
        { es: 'mañana neva', perche: 'Nevica si dice nieva, con ie' }] },
    { id: 'te-hay-niebla', tappa: 'terza-hace', forma: 'hace', it: 'c’è nebbia e fa freddo', es: 'hay niebla y hace frío' },
    { id: 'te-hay-tormenta', tappa: 'terza-hace', forma: 'hace', it: 'c’è un temporale e piove', es: 'hay una tormenta y llueve' },
    { id: 'te-hay-nubes', tappa: 'terza-hace', forma: 'hace', it: 'ci sono le nuvole e non piove', es: 'hay nubes y no llueve' },

    /* ── Essere o stare? ── */
    { id: 'te-soy-alto-eres-bajo', tappa: 'terza-estar', forma: 'ser-estar', it: 'io sono alto e tu sei basso', es: 'yo soy alto y tú eres bajo' },
    { id: 'te-laura-alta', tappa: 'terza-estar', forma: 'ser-estar', it: 'Laura è alta', es: 'Laura es alta' },
    { id: 'te-perro-grande', tappa: 'terza-estar', forma: 'ser-estar', it: 'il mio cane è grande', es: 'mi perro es grande' },
    { id: 'te-casa-azul', tappa: 'terza-estar', forma: 'ser-estar', it: 'la casa è blu', es: 'la casa es azul' },
    { id: 'te-pip-un-perro', tappa: 'terza-estar', forma: 'ser-estar', it: 'Pip è un cane grande', es: 'Pip es un perro grande' },
    { id: 'te-abuelo-fuerte', tappa: 'terza-estar', forma: 'ser-estar', it: 'il nonno è forte', es: 'el abuelo es fuerte' },
    { id: 'te-estoy-cansado', tappa: 'terza-estar', forma: 'ser-estar', it: 'sono stanco', es: 'estoy cansado' },
    { id: 'te-laura-cansada', tappa: 'terza-estar', forma: 'ser-estar', it: 'Laura è stanca', es: 'Laura está cansada' },
    { id: 'te-estas-enojado', tappa: 'terza-estar', forma: 'ser-estar', it: 'sei arrabbiato?', es: 'estás enojado' },
    { id: 'te-tom-contento', tappa: 'terza-estar', forma: 'ser-estar', it: 'Tom è contento', es: 'Tom está contento' },
    { id: 'te-abuela-enferma', tappa: 'terza-estar', forma: 'ser-estar', it: 'la nonna è malata', es: 'la abuela está enferma' },
    { id: 'te-pip-asustado', tappa: 'terza-estar', forma: 'ser-estar', it: 'Pip è spaventato', es: 'Pip está asustado' },
    { id: 'te-alto-y-cansado', tappa: 'terza-estar', forma: 'ser-estar', it: 'Leo è alto e oggi è stanco', es: 'Leo es alto y hoy está cansado' },
    { id: 'te-leo-en-casa', tappa: 'terza-estar', forma: 'ser-estar', it: 'Leo è a casa', es: 'Leo está en casa' },
    { id: 'te-papa-cocina', tappa: 'terza-estar', forma: 'ser-estar', it: 'papà è in cucina', es: 'papá está en la cocina' },
    { id: 'te-gato-aqui', tappa: 'terza-estar', forma: 'ser-estar', it: 'il gatto è qui', es: 'el gato está aquí' },
    { id: 'te-libro-de-laura', tappa: 'terza-estar', forma: 'ser-estar', it: 'il libro è di Laura', es: 'el libro es de Laura' },
    { id: 'te-gorra-de-papa', tappa: 'terza-estar', forma: 'ser-estar', it: 'il cappellino è di papà', es: 'la gorra es de papá' },
    { id: 'te-pelota-de-tom', tappa: 'terza-estar', forma: 'ser-estar', it: 'la palla è di Tom ed è in giardino', es: 'la pelota es de Tom y está en el jardín' },
    { id: 'te-libro-laura-mesa', tappa: 'terza-estar', forma: 'ser-estar', it: 'il libro è di Laura ed è sul tavolo', es: 'el libro es de Laura y está sobre la mesa',
      varianti: ['el libro es de Laura y está en la mesa'] },
  ],
}
