// I concetti delle strutture del mondo «quinta» (formato in concetti.js)
const con = rx => f => rx.test(f.es)
const INFINITO_DOPO = /\b(quiero|quieres|quiere|queremos|quieren|puedo|puedes|puede|podemos|pueden) (ir|[a-zñ]+(ar|er|ir))\b/

export default {
  'voy-al': [
    { id: 'voy-al:ir', titolo: 'Vado a…',
      spiega: 'Andare è ir: voy, vas, va, vamos, van. Verso un posto sempre a, mai en: va a la biblioteca, «va in biblioteca».',
      esempi: [['mamá está en la escuela', 'la mamma è a scuola'], ['mamá [va a] la escuela', 'la mamma va a scuola']] },
    { id: 'voy-al:al', titolo: 'A + el = al', prende: con(/\bal\b/),
      spiega: 'A e el non si scrivono mai vicini: diventano al, come «al» in italiano. Con la restano due: a la.',
      esempi: [['voy [a la] escuela', 'vado a scuola'], ['voy [al] parque', 'vado al parco']] },
    { id: 'voy-al:del', titolo: 'Vengo da…', prende: con(/\b(vengo|vienes|viene|vienen)\b/),
      spiega: 'Venire è venir: vengo, vienes, viene. Da un posto si dice de, e de + el diventa del.',
      esempi: [['vengo [de la] tienda', 'vengo dal negozio'], ['vengo [del] cine', 'vengo dal cinema']] },
  ],
  direcciones: [
    { id: 'direcciones:lado', titolo: 'A sinistra, a destra', prende: con(/\b(izquierda|derecha)\b/),
      spiega: 'Per dare la strada si parla a «tu»: gira. Sinistra e destra vogliono la: a la izquierda.',
      esempi: [['gira a la izquierda', 'gira a sinistra'], ['gira a la [derecha]', 'gira a destra']] },
    { id: 'direcciones:dove', titolo: 'Accanto, di fronte, tra', prende: con(/\b(lado|enfrente|entre)\b/),
      spiega: 'Accanto a è al lado de, di fronte a è enfrente de, tra è entre. Se dopo c’è el, de + el fa del.',
      esempi: [['el banco está [al lado de] la plaza', 'la banca è accanto alla piazza'],
               ['el banco está al lado [del] parque', 'la banca è accanto al parco']] },
    { id: 'direcciones:sigue', titolo: 'Vai dritto, attraversa',
      spiega: 'Sigue è «vai avanti», cruza è «attraversa», hasta è «fino a». Hasta el resta in due parole.',
      esempi: [['sigue recto', 'vai dritto'], ['sigue recto [hasta] la plaza', 'vai dritto fino alla piazza']] },
  ],
  cuanto: [
    { id: 'cuanto:cuesta', titolo: 'Quanto costa?',
      spiega: 'Costare è costar, ma la o diventa ue: cuesta. Per chiedere il prezzo: ¿cuánto cuesta?',
      esempi: [['el pan cuesta un boliviano', 'il pane costa un boliviano'],
               ['¿[cuánto] cuesta el pan?', 'quanto costa il pane?']] },
    { id: 'cuanto:cuestan', titolo: 'Quanto costano?', prende: con(/\bcuestan\b/),
      spiega: 'Per più cose cuestan, come «costano». Las uvas sono tante: cuestan, anche se in italiano «l’uva costa».',
      esempi: [['la manzana cuesta un boliviano', 'la mela costa un boliviano'],
               ['las [manzanas cuestan] un boliviano', 'le mele costano un boliviano']] },
    { id: 'cuanto:caro', titolo: 'Caro, economico, i soldi', prende: con(/\b(caro|cara|barato|barata|dinero|moneda|billete)\b/),
      spiega: 'Caro e barato (economico) vanno d’accordo con la cosa. Una moneta da un boliviano: una moneda de un boliviano.',
      esempi: [['el libro es caro', 'il libro è caro'], ['el libro es [barato]', 'il libro è economico']] },
  ],
  de: [
    { id: 'de:de', titolo: 'Il cane di Tom',
      spiega: 'Di chi è: prima la cosa, poi de e chi la ha, come in italiano. Mai Tom prima del cane.',
      esempi: [['es el perro', 'è il cane'], ['es el perro [de Tom]', 'è il cane di Tom']] },
    { id: 'de:del', titolo: 'De + el = del', prende: con(/\bdel\b/),
      spiega: 'De e el non si scrivono vicini: diventano del. Con la restano due: de la abuela.',
      esempi: [['es el gato [de la] abuela', 'è il gatto della nonna'], ['es el gato [del] abuelo', 'è il gatto del nonno']] },
    { id: 'de:quien', titolo: 'Di chi è?', prende: con(/\bde quién\b/),
      spiega: 'Per chiedere di chi è una cosa: ¿de quién es? De sta in testa, come «di» in «di chi».',
      esempi: [['es el libro de Tom', 'è il libro di Tom'], ['¿[de quién] es el libro?', 'di chi è il libro?']] },
  ],
  'quiero-puedo': [
    { id: 'quiero-puedo:quiero', titolo: 'Voglio',
      spiega: 'Volere è querer, e la e diventa ie: quiero, quieres, quiere. Con nosotros no: queremos.',
      esempi: [['tengo un perro', 'ho un cane'], ['[quiero] un perro', 'voglio un cane']] },
    { id: 'quiero-puedo:infinito', titolo: 'Voglio giocare, posso andare', prende: f => INFINITO_DOPO.test(f.es),
      spiega: 'Potere è poder: puedo, puedes, puede. Dopo quiero e puedo il verbo resta com’è, come in italiano.',
      esempi: [['quiero un perro', 'voglio un cane'], ['quiero [jugar]', 'voglio giocare']] },
    { id: 'quiero-puedo:juego', titolo: 'Gioco, dormo', prende: con(/\b(juego|juegas|juega|juegan|jugamos|duermo|duermes|duerme|duermen|dormimos)\b/),
      spiega: 'Anche jugar e dormir cambiano la vocale: juego, duermo. Con nosotros no: jugamos, dormimos.',
      esempi: [['yo como mucho', 'io mangio molto'], ['yo [duermo] mucho', 'io dormo molto']] },
  ],
}
