// I concetti delle strutture del mondo «seconda» (formato in concetti.js)
const con = rx => f => rx.test(f.es)
// un plurale in -es dopo una consonante (lápices, ratones, azules), non tres
const inEs = f => f.es.split(' ').some(w => w !== 'tres' && /[^aeiouáéíóú]es$/.test(w))

export default {
  plural: [
    { id: 'plural:s', titolo: 'Due gatti',
      spiega: 'Per più cose si aggiunge la s, e «sono» si dice son: un gato, dos gatos.',
      esempi: [['es un gato', 'è un gatto'], ['[son] dos gato[s]', 'sono due gatti']] },
    { id: 'plural:es', titolo: 'Una matita, due matite', prende: inEs,
      spiega: 'Se la parola finisce con una consonante si aggiunge -es: ratón, ratones. La z diventa c: lápiz, lápices.',
      esempi: [['un lápiz', 'una matita'], ['dos [lápices]', 'due matite']] },
    { id: 'plural:los', titolo: 'I gatti, le mucche', prende: con(/^(los|las|estos|estas)\b/),
      spiega: 'El diventa los, la diventa las. E va al plurale anche il colore: las vacas son negras.',
      esempi: [['la vaca es negra', 'la mucca è nera'], ['[las] vaca[s] [son] negra[s]', 'le mucche sono nere']] },
  ],
  'me-gusta': [
    { id: 'me-gusta:gusta', titolo: 'Mi piace',
      spiega: 'Come «mi piace»: me gusta e poi la cosa, con el o la davanti. Mai «yo gusto».',
      esempi: [['el chocolate', 'il cioccolato'], ['[me gusta] el chocolate', 'mi piace il cioccolato']] },
    { id: 'me-gusta:gustan', titolo: 'Mi piacciono', prende: f => /\bgustan\b/.test(f.es) && !/^(no|a|te)\b/.test(f.es),
      spiega: 'Se piacciono più cose, gusta diventa gustan. Attento: «l’uva» è las uvas, più cose.',
      esempi: [['me gusta el perro', 'mi piace il cane'], ['me [gustan] lo[s] perro[s]', 'mi piacciono i cani']] },
    { id: 'me-gusta:no', titolo: 'Non mi piace', prende: con(/^no me\b/),
      spiega: 'Per dire di no, no va davanti a tutto: no me gusta.',
      esempi: [['me gusta la sopa', 'mi piace la minestra'], ['[no] me gusta la sopa', 'non mi piace la minestra']] },
    { id: 'me-gusta:te', titolo: 'Ti piace?', prende: con(/^(no )?te\b/),
      spiega: 'Per chiedere a un amico: te gusta? Come in italiano, ma si dice te, non ti.',
      esempi: [['me gusta la pizza', 'mi piace la pizza'], ['¿[te] gusta la pizza?', 'ti piace la pizza?']] },
    { id: 'me-gusta:a-mi', titolo: 'A me, a te', prende: con(/^a (mí|ti) /),
      spiega: 'Per dire «a me» si mette a mí davanti, ma me resta: a mí me gusta. A te: a ti te gusta.',
      esempi: [['me gusta la leche', 'mi piace il latte'], ['[a mí] me gusta la leche', 'a me piace il latte']] },
  ],
  'mi-tu-su': [
    { id: 'mi-tu-su:mi', titolo: 'Il mio: mi',
      spiega: 'Mio e mia si dicono mi, e davanti non va el o la: mi perro, non el mi perro.',
      esempi: [['el perro', 'il cane'], ['[mi] perro', 'il mio cane']] },
    { id: 'mi-tu-su:tu', titolo: 'Il tuo: tu', prende: con(/\btu\b/),
      spiega: 'Tuo e tua: tu, senza accento. Tú con l’accento vuol dire «tu» che fai.',
      esempi: [['mi gorra', 'il mio berretto'], ['[tu] gorra', 'il tuo berretto']] },
    { id: 'mi-tu-su:su', titolo: 'Il suo: su', prende: con(/\bsu\b/),
      spiega: 'Suo e sua si dicono su, che sia di lui o di lei.',
      esempi: [['mi abrigo', 'il mio cappotto'], ['[su] abrigo', 'il suo cappotto']] },
    { id: 'mi-tu-su:mis', titolo: 'I miei: mis', prende: con(/\b(mis|tus|sus)\b/),
      spiega: 'Se le cose sono più d’una si aggiunge la s: mis, tus, sus. Maschile o femminile è uguale.',
      esempi: [['mi gato', 'il mio gatto'], ['[mis] gato[s]', 'i miei gatti']] },
  ],
  ser: [
    { id: 'ser:soy', titolo: 'Io sono: soy', prende: f => /\bsoy\b/.test(f.es) && !/\bes\b/.test(f.es),
      spiega: 'Essere è ser. Io sono: yo soy. Dice chi sei e come sei: yo soy Leo, yo soy alto.',
      esempi: [['yo soy Leo', 'io sono Leo'], ['yo soy [alto]', 'io sono alto']] },
    { id: 'ser:eres', titolo: 'Tu sei: eres', prende: f => /\beres\b/.test(f.es) && !/\bes\b/.test(f.es),
      spiega: 'Tu sei: tú eres. È un’altra parola, come in italiano «sei» non è «sono».',
      esempi: [['yo soy alto', 'io sono alto'], ['[tú eres] alto', 'tu sei alto']] },
    { id: 'ser:es', titolo: 'Lui è, lei è: es',
      spiega: 'Lui, lei, una cosa: es. La parola dopo va d’accordo, come in italiano: yo soy alto, ella es alta.',
      esempi: [['yo soy alto', 'io sono alto'], ['[ella es] alt[a]', 'lei è alta']] },
    { id: 'ser:somos', titolo: 'Noi siamo, loro sono', prende: con(/\b(somos|son)\b/),
      spiega: 'Noi siamo: somos. Loro sono: son. E la parola dopo va al plurale: ellos son altos.',
      esempi: [['él es alto', 'lui è alto'], ['[ellos son] alto[s]', 'loro sono alti']] },
  ],
  tener: [
    { id: 'tener:tengo', titolo: 'Ho: tengo',
      spiega: 'Avere si dice tener: io ho è tengo, tu hai è tienes. Mai «he», come in italiano.',
      esempi: [['es un perro', 'è un cane'], ['[tengo] un perro', 'ho un cane']] },
    { id: 'tener:anos', titolo: 'Ho sette anni', prende: con(/\baños\b/),
      spiega: 'Gli anni si «hanno», come in italiano: tengo siete años. Mai «soy siete años».',
      esempi: [['tengo un perro', 'ho un cane'], ['tengo [siete años]', 'ho sette anni']] },
    { id: 'tener:hambre', titolo: 'Ho fame', prende: con(/\b(hambre|sed|frío|calor|sueño|miedo)\b/),
      spiega: 'Fame, sete, freddo, caldo, sonno e paura si «hanno», come in italiano: tengo hambre. Mai «soy hambre».',
      esempi: [['tengo un perro', 'ho un cane'], ['tengo [hambre]', 'ho fame']] },
  ],
  tiene: [
    { id: 'tiene:tiene', titolo: 'Lui ha, lei ha: tiene',
      spiega: 'Con lui, lei o un nome si dice tiene: Tom tiene hambre. Io tengo, lui tiene.',
      esempi: [['tengo hambre', 'ho fame'], ['Tom [tiene] hambre', 'Tom ha fame']] },
    { id: 'tiene:tienen', titolo: 'Loro hanno: tienen', prende: con(/\btienen\b/),
      spiega: 'Con loro, o con più persone e cose, si aggiunge la n: tienen.',
      esempi: [['él tiene frío', 'lui ha freddo'], ['[ellos tienen] frío', 'loro hanno freddo']] },
    { id: 'tiene:tenemos', titolo: 'Noi abbiamo: tenemos', prende: con(/\btenemos\b/),
      spiega: 'Noi abbiamo: tenemos. Qui la ie torna e: tenemos, non «tienemos».',
      esempi: [['tengo un gato', 'ho un gatto'], ['[tenemos] un gato', 'abbiamo un gatto']] },
    { id: 'tiene:cuerpo', titolo: 'Ha gli occhi azzurri', prende: con(/\b(ojos|pelo|nariz)\b/),
      spiega: 'Per com’è fatto qualcuno: tiene el, la, los. «I capelli» è el pelo, al singolare.',
      esempi: [['tiene un perro negro', 'ha un cane nero'], ['tiene [el pelo] negro', 'ha i capelli neri']] },
  ],
}
