// I concetti delle strutture del mondo «sesta» (formato in concetti.js)
// \b non conosce le lettere accentate (jugué): il confine è lo spazio
const con = rx => f => new RegExp(`(?:^| )(?:${rx.source})(?: |$)`).test(f.es)
const domanda = f => f.domanda

export default {
  ayer: [
    { id: 'ayer:estuve', titolo: 'Ieri ero al parco',
      spiega: 'Per dire dove eri o come stavi ieri, estar va al passato: estuve, estuvo, estuvimos.',
      esempi: [['hoy [estoy] en el parque', 'oggi sono al parco'], ['ayer [estuve] en el parque', 'ieri sono stato al parco']] },
    { id: 'ayer:fui', titolo: 'Ieri sono andato', prende: con(/(fui|fuiste|fue|fuimos|fueron) (a|al)/),
      spiega: 'Ir al passato fa fui, fue, fueron. Come nel presente, dopo c’è a o al: fui al cine.',
      esempi: [['hoy [voy] al cine', 'oggi vado al cinema'], ['ayer [fui] al cine', 'ieri sono andato al cinema']] },
    { id: 'ayer:fue', titolo: 'Ieri era lunedì', prende: con(/fui|fuiste|fue|fuimos|fueron/),
      spiega: 'Anche ser al passato fa fui, fue: le stesse parole di ir! Ayer fue lunes: ieri era lunedì.',
      esempi: [['hoy [es] lunes', 'oggi è lunedì'], ['ayer [fue] lunes', 'ieri era lunedì']] },
  ],
  'pasado-irr': [
    { id: 'pasado-irr:hice', titolo: 'Ho fatto: hice', prende: con(/hice|hiciste|hizo|hicimos|hicieron/),
      spiega: 'Hacer al passato cambia tutto: hice, hiciste, hizo. Niente «hací»: va imparato a memoria.',
      esempi: [['hoy [hago] una torta', 'oggi faccio una torta'], ['ayer [hice] una torta', 'ieri ho fatto una torta']] },
    { id: 'pasado-irr:vi', titolo: 'Ho visto, ho dato: vi, di', prende: con(/vi|viste|vio|vimos|vieron|di|diste|dio|dimos|dieron/),
      spiega: 'Ver e dar al passato sono corti: vi, vio; di, dio. Così corti non hanno l’accento.',
      esempi: [['Leo [ve] un pájaro', 'Leo vede un uccello'], ['Leo [vio] un pájaro', 'Leo ha visto un uccello']] },
    { id: 'pasado-irr:vine', titolo: 'Sono venuto, ho potuto',
      spiega: 'Anche venir, poder e querer cambiano: vine, vino; pude; quiso. Ir fa fui, come ser.',
      esempi: [['mi abuela [viene] a mi casa', 'mia nonna viene a casa mia'],
               ['mi abuela [vino] a mi casa', 'mia nonna è venuta a casa mia']] },
  ],
  'pasado-reg': [
    { id: 'pasado-reg:ar', titolo: 'Ho aiutato: ayudé',
      spiega: 'I verbi in -ar al passato: -é per io, -ó per lui o lei, -aron per loro. L’accento è obbligatorio.',
      esempi: [['hoy [ayudo] a mi papá', 'oggi aiuto il mio papà'], ['ayer [ayudé] a mi papá', 'ieri ho aiutato il mio papà']] },
    { id: 'pasado-reg:er-ir', titolo: 'Ha mangiato: comió',
      prende: con(/[a-zñ]+(í|iste|ió|imos|ieron)/),
      spiega: 'I verbi in -er e -ir: -í per io, -ió per lui o lei. Comió con l’accento: comio è sbagliato.',
      esempi: [['ella [come] una manzana', 'lei mangia una mela'], ['ella [comió] una manzana', 'lei ha mangiato una mela']] },
    { id: 'pasado-reg:gue', titolo: 'Ho giocato: jugué', prende: con(/jugué|lancé/),
      spiega: 'Con io, jugar fa jugué: la u tiene il suono di «ghe». Lanzar fa lancé, con la c.',
      esempi: [['ella [jugó] al tenis', 'lei ha giocato a tennis'], ['yo [jugué] al tenis', 'io ho giocato a tennis']] },
  ],
  decir: [
    { id: 'decir:dijo', titolo: 'Ha detto: dijo',
      spiega: 'Decir al passato cambia: dije, dijiste, dijo, dijeron. Niente «decí»: si dice con la j.',
      esempi: [['Leo [dice] hola', 'Leo dice ciao'], ['Leo [dijo] hola', 'Leo ha detto ciao']] },
    { id: 'decir:me-dijo', titolo: 'Mi ha detto', prende: con(/(me|te|le|nos|les) (dijo|dije|dijiste|dijimos|dijeron|dice|dicen|digo)/),
      spiega: 'A chi lo dici va prima del verbo: me dijo (mi ha detto), te dijo, le dijo (gli ha detto).',
      esempi: [['papá dijo adiós', 'papà ha detto ciao'], ['papá [me] dijo adiós', 'papà mi ha detto ciao']] },
    { id: 'decir:que', titolo: 'Dice che…', prende: con(/(dice|dicen|digo|dijo|dije|dijiste|dijimos|dijeron) que/),
      spiega: 'Dopo decir viene que, come «che» in italiano: dice que tiene hambre. E «dico di sì» è digo que sí.',
      esempi: [['Tom tiene hambre', 'Tom ha fame'], ['Tom [dice que] tiene hambre', 'Tom dice che ha fame']] },
  ],
  cuando: [
    { id: 'cuando:cuando', titolo: 'Quando fa freddo',
      spiega: 'Quando si dice cuando, senza accento. Dopo viene il verbo: cuando hace frío, cuando llueve.',
      esempi: [['hace frío', 'fa freddo'], ['[cuando] hace frío bebo leche', 'quando fa freddo bevo latte']] },
    { id: 'cuando:mientras', titolo: 'Mentre', prende: con(/mientras/),
      spiega: 'Mentre si dice mientras: due cose nello stesso momento. Cuando invece è «quando».',
      esempi: [['[cuando] cocino escucho música', 'quando cucino ascolto la musica'],
               ['[mientras] cocino escucho música', 'mentre cucino ascolto la musica']] },
    { id: 'cuando:domanda', titolo: 'Che cosa fai quando…?', prende: domanda,
      spiega: 'Anche dentro una domanda cuando non ha l’accento: l’accento va solo su ¿qué?, ¿dónde?…',
      esempi: [['cuando llueve juego', 'quando piove gioco'], ['¿[qué haces] cuando llueve?', 'che cosa fai quando piove?']] },
  ],
  comparativos: [
    { id: 'comparativos:mas-que', titolo: 'Più alto di',
      spiega: 'Più … di si dice más … que, non «de»: más alto que yo. Meno … di: menos … que.',
      esempi: [['mi hermano es alto', 'mio fratello è alto'], ['mi hermano es [más] alto [que] yo', 'mio fratello è più alto di me']] },
    { id: 'comparativos:el-mas', titolo: 'Il più alto', prende: con(/(el|la|los|las) (más|menos)/),
      spiega: 'Il più, la più: el más, la más. Come in italiano, con l’articolo davanti.',
      esempi: [['Laura es [más] valiente', 'Laura è più coraggiosa'], ['Laura es [la más] valiente', 'Laura è la più coraggiosa']] },
    { id: 'comparativos:mejor', titolo: 'Migliore, peggiore', prende: con(/mejor|peor/),
      spiega: 'Più buono si dice mejor, più cattivo peor: mai «más bueno». Mejor vuol dire anche «meglio».',
      esempi: [['la pizza es buena', 'la pizza è buona'], ['la pizza es [mejor] que la sopa', 'la pizza è più buona della minestra']] },
  ],
  'voy-a': [
    { id: 'voy-a:voy-a', titolo: 'Domani giocherò',
      spiega: 'Per quello che farai: voy a + il verbo com’è (voy a jugar). La a non si dimentica mai.',
      esempi: [['voy al parque', 'vado al parco'], ['voy [a jugar]', 'giocherò']] },
    { id: 'voy-a:domanda', titolo: 'Che cosa farai?', prende: domanda,
      spiega: 'Per chiedere a te: vas a. ¿Qué vas a hacer? vuol dire «che cosa farai?».',
      esempi: [['voy a hacer una torta', 'farò una torta'], ['¿qué [vas] a hacer?', 'che cosa farai?']] },
    { id: 'voy-a:no', titolo: 'Non piangerò', prende: con(/no (voy|vas|va|vamos|van)/),
      spiega: 'Per dire di no, no va prima di voy: no voy a llorar.',
      esempi: [['voy a llorar', 'piangerò'], ['[no] voy a llorar', 'non piangerò']] },
  ],
}
