// I concetti delle strutture del mondo «terza» (formato in concetti.js)
const domanda = f => f.domanda
const con = rx => f => rx.test(f.es)
const GIORNI = 'lunes|martes|miércoles|jueves|viernes|sábado|domingo'
const MESI = 'enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre|' +
  'primavera|verano|otoño|invierno'

export default {
  'esta-en': [
    { id: 'esta-en:esta', titolo: 'Il gatto è in cucina',
      spiega: 'Per dire dove sta una cosa si usa está, non es. In italiano «è in cucina», in spagnolo «está en la cocina».',
      esempi: [['el gato es negro', 'il gatto è nero'], ['el gato [está en] la cocina', 'il gatto è in cucina']] },
    { id: 'esta-en:posto', titolo: 'Sopra, sotto, dietro', prende: con(/\b(sobre|debajo|detrás|cerca|lado)\b/),
      spiega: 'Sobre vuol dire sopra. Debajo (sotto), detrás (dietro), cerca (vicino) e al lado (accanto) vogliono de: debajo de la cama.',
      esempi: [['la pelota está [sobre] la cama', 'la palla è sopra il letto'],
               ['la pelota está [debajo de] la cama', 'la palla è sotto il letto']] },
    { id: 'esta-en:dove', titolo: 'Dov’è?', prende: domanda,
      spiega: 'Per chiedere dove: ¿dónde está?, con l’accento su dónde. Per più cose: ¿dónde están?',
      esempi: [['el gato está en la cocina', 'il gatto è in cucina'], ['[¿dónde] está el gato?', 'dov’è il gatto?']] },
    { id: 'esta-en:persone', titolo: 'Sono a casa', prende: con(/\b(estoy|estás|estamos)\b/),
      spiega: 'Anche per le persone si usa estar: estoy (io), estás (tu), está (lui, lei), estamos (noi), están (loro).',
      esempi: [['mamá está en casa', 'la mamma è a casa'], ['[estoy] en casa', 'sono a casa']] },
  ],
  hay: [
    { id: 'hay:uno', titolo: 'C’è un gatto',
      spiega: '«C’è» si dice hay: hay un gato. Il gatto che conosci già, con el, invece está: el gato está en la cocina.',
      esempi: [['el gato está en la cocina', 'il gatto è in cucina'], ['[hay un] gato en la cocina', 'c’è un gatto in cucina']] },
    { id: 'hay:tanti', titolo: 'Ci sono due gatti',
      prende: f => /\bhay (?!un\b|una\b)/.test(f.es) && !f.domanda && !/\bno hay\b/.test(f.es),
      spiega: 'Anche «ci sono» si dice hay: non cambia mai. Hay un gato, hay dos gatos.',
      esempi: [['hay un gato', 'c’è un gatto'], ['hay [dos gatos]', 'ci sono due gatti']] },
    { id: 'hay:no', titolo: 'Non c’è', prende: con(/\bno hay\b/),
      spiega: 'Per dire che non c’è, no va prima di hay: no hay pan.',
      esempi: [['hay pan en la mesa', 'c’è del pane sul tavolo'], ['[no] hay pan en la mesa', 'non c’è pane sul tavolo']] },
    { id: 'hay:domanda', titolo: 'Quanti ce ne sono?', prende: domanda,
      spiega: 'Per chiedere basta il punto di domanda: ¿hay un gato? Per contare: ¿cuántos gatos hay?, con hay in fondo.',
      esempi: [['hay dos gatos', 'ci sono due gatti'], ['[¿cuántos] gatos hay?', 'quanti gatti ci sono?']] },
  ],
  preguntas: [
    { id: 'preguntas:que', titolo: 'Che cosa?',
      spiega: '«Che cosa?» si dice qué, con l’accento. Tutte le parole che chiedono hanno l’accento: qué, dónde, cuál.',
      esempi: [['hay un libro en la caja', 'c’è un libro nella scatola'], ['[¿qué] hay en la caja?', 'che cosa c’è nella scatola?']] },
    { id: 'preguntas:chi', titolo: 'Chi?', prende: con(/\bquién\b/),
      spiega: '«Chi?» si dice quién, con l’accento: ¿quién es?, ¿quién tiene la pelota?',
      esempi: [['Leo tiene la pelota', 'Leo ha la palla'], ['[¿quién] tiene la pelota?', 'chi ha la palla?']] },
    { id: 'preguntas:come', titolo: 'Come?', prende: con(/\bcómo\b/),
      spiega: '«Come?» si dice cómo. ¿Cómo es? chiede com’è una cosa; ¿cómo está? chiede come sta adesso.',
      esempi: [['¿cómo [está] la abuela?', 'come sta la nonna?'], ['¿cómo [es] tu casa?', 'com’è la tua casa?']] },
    { id: 'preguntas:quanti', titolo: 'Quanti? Quante?', prende: con(/\bcuánt(os|as)\b/),
      spiega: 'Cuántos per le cose maschili, cuántas per le femminili, come quanti e quante.',
      esempi: [['¿[cuántos] libros hay?', 'quanti libri ci sono?'], ['¿[cuántas] sillas hay?', 'quante sedie ci sono?']] },
  ],
  'hoy-es': [
    { id: 'hoy-es:oggi', titolo: 'Oggi è lunedì',
      spiega: 'Oggi è hoy, domani è mañana. Come in italiano, dopo es il giorno va da solo: hoy es lunes.',
      esempi: [['hoy es lunes', 'oggi è lunedì'], ['[mañana] es lunes', 'domani è lunedì']] },
    { id: 'hoy-es:giorno', titolo: 'Sabato c’è una festa', prende: con(new RegExp(`\\bel (${GIORNI})\\b`)),
      spiega: 'Per dire in che giorno succede una cosa si mette el davanti: el sábado. Mai en el sábado.',
      esempi: [['hoy es sábado', 'oggi è sabato'], ['[el] sábado hay una fiesta', 'sabato c’è una festa']] },
    { id: 'hoy-es:mese', titolo: 'A maggio, d’estate', prende: con(new RegExp(`\\ben (${MESI})\\b`)),
      spiega: 'Con i mesi e le stagioni si usa en, senza el: en mayo, en verano. Come «a maggio», «d’estate».',
      esempi: [['mi cumpleaños es el lunes', 'il mio compleanno è lunedì'],
               ['mi cumpleaños es [en mayo]', 'il mio compleanno è a maggio']] },
    { id: 'hoy-es:quando', titolo: 'Che giorno è?', prende: domanda,
      spiega: 'Per chiedere che giorno è: ¿qué día es hoy? Per chiedere quando: ¿cuándo?, con l’accento.',
      esempi: [['hoy es lunes', 'oggi è lunedì'], ['[¿qué día] es hoy?', 'che giorno è oggi?']] },
  ],
  hace: [
    { id: 'hace:fa', titolo: 'Fa freddo',
      spiega: 'Il tempo si dice con hace, come «fa» in italiano: hace frío, hace calor, hace sol. Mai es frío.',
      esempi: [['tengo frío', 'ho freddo'], ['[hace] frío', 'fa freddo']] },
    { id: 'hace:molto', titolo: 'Fa molto freddo', prende: con(/\bmucho (frío|calor|viento|sol)\b/),
      spiega: '«Fa molto freddo» è hace mucho frío: davanti a frío, calor e viento va mucho, non muy.',
      esempi: [['hace frío', 'fa freddo'], ['hace [mucho] frío', 'fa molto freddo']] },
    { id: 'hace:piove', titolo: 'Piove, nevica', prende: f => /\b(llueve|nieva)\b/.test(f.es) && !/\bhay\b/.test(f.es),
      spiega: '«Piove» è una parola sola, llueve; «nevica» è nieva. Niente hace davanti.',
      esempi: [['hoy hace frío', 'oggi fa freddo'], ['hoy [llueve]', 'oggi piove']] },
    { id: 'hace:hay', titolo: 'C’è la nebbia', prende: con(/\bhay\b/),
      spiega: 'Le cose che vedi in cielo si dicono con hay, come «c’è»: hay nubes, hay niebla, hay una tormenta.',
      esempi: [['hace frío', 'fa freddo'], ['[hay niebla] y hace frío', 'c’è nebbia e fa freddo']] },
  ],
  'ser-estar': [
    { id: 'ser-estar:ser', titolo: 'Sono alto',
      spiega: 'Ser dice chi sei e come sei sempre: soy alto, es un perro, la casa es azul.',
      esempi: [['soy alto', 'sono alto'], ['[Laura es] alta', 'Laura è alta']] },
    { id: 'ser-estar:estar', titolo: 'Sono stanco',
      prende: con(/\b(estoy|estás|está|estamos|están) (?!(en|aquí|allí|sobre|debajo)(\s|$))/),
      spiega: 'Estar dice come stai adesso: estoy cansado, está enfermo. In italiano per tutte e due diciamo «sono»!',
      esempi: [['[soy] alto', 'sono alto'], ['[estoy] cansado', 'sono stanco']] },
    { id: 'ser-estar:dove', titolo: 'Leo è a casa',
      prende: f => /\b(estoy|estás|está|estamos|están) (en|aquí|allí)(\s|$)/.test(f.es) && !/\b(es|son) de\b/.test(f.es),
      spiega: 'Anche dove sei si dice con estar: Leo está en casa. Mai es en casa.',
      esempi: [['Leo es alto', 'Leo è alto'], ['Leo [está en] casa', 'Leo è a casa']] },
    { id: 'ser-estar:di', titolo: 'Di chi è?', prende: con(/\b(es|son) de\b/),
      spiega: 'Di chi è una cosa si dice con ser: es de Laura. Dove sta, con estar: está en la mesa.',
      esempi: [['el libro [es de] Laura', 'il libro è di Laura'], ['el libro [está en] la mesa', 'il libro è sul tavolo']] },
  ],
}
