// I concetti di ogni struttura: una tappa di frasi li presenta uno alla
// volta, con la sua pagina, e la pagina torna a chi continua a sbagliarlo.
// Il perché e la partita in docs/lingue/concetti.md.
//
// Un concetto: { id, titolo, spiega, esempi: [[en, it]…], prende? }.
// - `esempi`: la prima riga è quella che il bambino sa già, la seconda
//   cambia una cosa sola; fra [quadre] quello che cambia, e si colora.
//   Solo parole note alla tappa (lo controlla guastiDeiConcetti).
// - `prende(f)`: le frasi della struttura che sono sue; `f` ha `en` in
//   minuscolo e `domanda`. Si prova nell'ordine, e il concetto senza
//   `prende` (uno per struttura) tiene il resto.
const domanda = f => f.domanda
const con = rx => f => rx.test(f.en)

export const CONCETTI = {
  /* ── In prima ── */
  'it-is': [
    { id: 'it-is:e', titolo: 'È un…',
      spiega: 'Per dire che cos’è una cosa: it is a… It è la cosa, is vuol dire «è».',
      esempi: [['[it is] a dog', 'è un cane'], ['[it is] a cat', 'è un gatto']] },
    { id: 'it-is:non', titolo: 'Non è', prende: con(/\bnot\b/),
      spiega: 'Per dire di no si mette not dopo is.',
      esempi: [['it is a fish', 'è un pesce'], ['it is [not] a fish', 'non è un pesce']] },
  ],
  'is-it': [
    { id: 'is-it:domanda', titolo: 'È un…?',
      spiega: 'Per chiedere si girano le prime due parole: is va prima di it.',
      esempi: [['it is a dog', 'è un cane'], ['[is it] a dog?', 'è un cane?']] },
  ],
  'colore-prima': [
    { id: 'colore-prima:prima', titolo: 'Una palla rossa',
      spiega: 'In inglese il colore va prima della cosa, al contrario dell’italiano.',
      esempi: [['a ball', 'una palla'], ['a [red] ball', 'una palla rossa']] },
    { id: 'colore-prima:dopo', titolo: 'La palla è rossa', prende: con(/\bthe\b/),
      spiega: 'Per dire di che colore è una cosa: il colore va dopo is, da solo.',
      esempi: [['a red ball', 'una palla rossa'], ['the ball [is red]', 'la palla è rossa']] },
  ],
  saluti: [
    { id: 'saluti:buongiorno', titolo: 'Buongiorno, buonanotte', prende: con(/\bgood\b/),
      spiega: 'Good vuol dire «buono»: good morning è buongiorno, good night è buonanotte.',
      esempi: [['[good morning]', 'buongiorno'], ['[good night]', 'buonanotte']] },
    { id: 'saluti:mi-chiamo', titolo: 'Mi chiamo Leo',
      spiega: 'Per presentarti dici my name is… («il mio nome è»), oppure I am… («io sono»).',
      esempi: [['[my name is] Leo', 'mi chiamo Leo'], ['[I am] Leo', 'io sono Leo']] },
    { id: 'saluti:come', titolo: 'Come ti chiami? Come stai?', prende: con(/\b(what|how|fine)\b/),
      spiega: 'What vuol dire «che cosa», how vuol dire «come». Chi chiede mette prima what o how, poi is o are.',
      esempi: [['[what] is your name?', 'come ti chiami?'], ['[how] are you?', 'come stai?']] },
  ],
  'this-is': [
    { id: 'this-is:e', titolo: 'Questo è…',
      spiega: 'This vuol dire «questo»: si usa per la cosa che hai vicino, da indicare col dito.',
      esempi: [['it is a pen', 'è una penna'], ['[this] is a pen', 'questa è una penna']] },
    { id: 'this-is:domanda', titolo: 'Questo è…?', prende: domanda,
      spiega: 'Per chiedere si gira, come con it: is va prima di this.',
      esempi: [['this is a pen', 'questa è una penna'], ['[is this] a pen?', 'questa è una penna?']] },
    { id: 'this-is:non', titolo: 'Questo non è', prende: con(/\bnot\b/),
      spiega: 'Per dire di no, not va dopo is.',
      esempi: [['this is a pen', 'questa è una penna'], ['this is [not] a pen', 'questa non è una penna']] },
  ],
  plurale: [
    { id: 'plurale:s', titolo: 'Due cani',
      spiega: 'Da due in su la cosa prende la s: dog, two dogs. E «sono» si dice they are.',
      esempi: [['it is a dog', 'è un cane'], ['[they are] two [dogs]', 'sono due cani']] },
    { id: 'plurale:domanda', titolo: 'Sono cani?', prende: domanda,
      spiega: 'Per chiedere si gira: are va prima di they.',
      esempi: [['they are dogs', 'sono cani'], ['[are they] dogs?', 'sono cani?']] },
  ],

  /* ── In seconda ── */
  'i-like': [
    { id: 'i-like:si', titolo: 'Mi piace',
      spiega: 'Mi piace si dice I like: «io» e poi like. Le cose che ti piacciono vanno dopo.',
      esempi: [['[I like] pizza', 'mi piace la pizza'], ['[I like] apples', 'mi piacciono le mele']] },
    { id: 'i-like:no', titolo: 'Non mi piace', prende: con(/\bnot\b/),
      spiega: 'Per dire che una cosa non ti piace, metti do not prima di like.',
      esempi: [['I like milk', 'mi piace il latte'], ['I [do not] like milk', 'non mi piace il latte']] },
    { id: 'i-like:domanda', titolo: 'Ti piace?', prende: domanda,
      spiega: 'Per chiedere si comincia con do: do you like…? You vuol dire «tu».',
      esempi: [['I like cake', 'mi piace la torta'], ['[do you] like cake?', 'ti piace la torta?']] },
  ],
  'this-is-my': [
    { id: 'this-is-my:mio', titolo: 'Mio e tuo',
      spiega: 'My vuol dire «mio» o «mia», your vuol dire «tuo» o «tua». Vanno prima della cosa.',
      esempi: [['[my] hat', 'il mio cappello'], ['[your] hat', 'il tuo cappello']] },
    { id: 'this-is-my:lui-lei', titolo: 'Lui e lei', prende: con(/\b(he|she)\b/),
      spiega: 'He vuol dire «lui», she vuol dire «lei». Dopo he e she si dice is.',
      esempi: [['[he] is my brother', 'lui è mio fratello'], ['[she] is my sister', 'lei è mia sorella']] },
    { id: 'this-is-my:sono', titolo: 'Io sono, tu sei', prende: con(/\b(am|are)\b/),
      spiega: '«Essere» cambia con chi parla: I am (io sono), you are (tu sei), he is (lui è).',
      esempi: [['[I am] happy', 'io sono felice'], ['[you are] happy', 'tu sei felice']] },
  ],
  'have-got': [
    { id: 'have-got:si', titolo: 'Ho un…',
      spiega: '«Ho» si dice I have got: have got insieme, come una parola sola.',
      esempi: [['a dog', 'un cane'], ['I [have got] a dog', 'ho un cane']] },
    { id: 'have-got:domanda', titolo: 'Hai un…?', prende: domanda,
      spiega: 'Per chiedere si gira: have va prima di you, e got resta dopo.',
      esempi: [['I have got a dog', 'ho un cane'], ['[have you] got a dog?', 'hai un cane?']] },
    { id: 'have-got:no', titolo: 'Non ho', prende: con(/\bnot\b/),
      spiega: 'Per dire di no, not va fra have e got.',
      esempi: [['I have got a hat', 'ho un cappello'], ['I have [not] got a hat', 'non ho un cappello']] },
  ],
  'has-got': [
    { id: 'has-got:ha', titolo: 'Lei ha…',
      spiega: 'Con he, she e con un nome (the dog, Laura) non si dice have got ma has got.',
      esempi: [['I [have got] a cat', 'ho un gatto'], ['she [has got] a cat', 'lei ha un gatto']] },
    { id: 'has-got:domanda', titolo: 'Lei ha…?', prende: domanda,
      spiega: 'Per chiedere si gira: has va prima di she, e got resta dopo.',
      esempi: [['she has got a cat', 'lei ha un gatto'], ['[has she] got a cat?', 'lei ha un gatto?']] },
  ],

  /* ── In terza ── */
  dove: [
    { id: 'dove:dove', titolo: 'Dov’è?', prende: con(/^where\b/),
      spiega: 'Dov’è si dice where is. Per più cose: where are.',
      esempi: [['[where is] the cat?', 'dov’è il gatto?'], ['[where are] my shoes?', 'dove sono le mie scarpe?']] },
    { id: 'dove:in-on-under', titolo: 'Dentro, sopra, sotto',
      spiega: 'In vuol dire «dentro», on «sopra», under «sotto». Vanno prima del posto, come in italiano.',
      esempi: [['the cat is [on] the bed', 'il gatto è sopra il letto'],
               ['the cat is [under] the bed', 'il gatto è sotto il letto']] },
    { id: 'dove:dietro', titolo: 'Dietro, vicino', prende: con(/\b(behind|near)\b/),
      spiega: 'Behind vuol dire «dietro», near vuol dire «vicino».',
      esempi: [['the dog is [behind] the sofa', 'il cane è dietro il divano'],
               ['the dog is [near] the sofa', 'il cane è vicino al divano']] },
  ],
  'there-is': [
    { id: 'there-is:c-e', titolo: 'C’è',
      spiega: '«C’è» si dice there is. Per dire di no: there is not.',
      esempi: [['a cat', 'un gatto'], ['[there is] a cat', 'c’è un gatto']] },
    { id: 'there-is:ci-sono', titolo: 'Ci sono', prende: f => !f.domanda && /\bare\b/.test(f.en),
      spiega: 'Per più cose «ci sono» si dice there are, e la cosa prende la s.',
      esempi: [['there is a cat', 'c’è un gatto'], ['[there are] two cats', 'ci sono due gatti']] },
    { id: 'there-is:domanda', titolo: 'C’è? Quanti sono?', prende: domanda,
      spiega: 'Per chiedere si gira: is there…? Per chiedere quanti: how many… are there?',
      esempi: [['there is a cat', 'c’è un gatto'], ['[is there] a cat?', 'c’è un gatto?']] },
  ],
  oggi: [
    { id: 'oggi:giorni', titolo: 'Oggi è lunedì',
      prende: con(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/),
      spiega: 'Oggi è lunedì: today is Monday. I giorni in inglese si scrivono con la maiuscola.',
      esempi: [['[today is] Monday', 'oggi è lunedì'], ['[tomorrow is] Tuesday', 'domani è martedì']] },
    { id: 'oggi:tempo', titolo: 'Fa freddo',
      spiega: 'Per il tempo che fa si dice it is: it is cold, fa freddo. It qui non vuol dire niente, ma ci va.',
      esempi: [['cold', 'freddo'], ['[it is] cold', 'fa freddo']] },
    { id: 'oggi:in', titolo: 'A maggio, d’inverno', prende: con(/\bin\b/),
      spiega: 'Con i mesi e le stagioni si dice in: in May, a maggio; in winter, d’inverno.',
      esempi: [['[in] May', 'a maggio'], ['it is cold [in] winter', 'fa freddo d’inverno']] },
  ],
  can: [
    { id: 'can:so', titolo: 'So nuotare',
      spiega: 'Can vuol dire «so fare» o «posso». Dopo can il verbo resta com’è.',
      esempi: [['swim', 'nuotare'], ['I [can] swim', 'so nuotare']] },
    { id: 'can:domanda', titolo: 'Sai nuotare?', prende: domanda,
      spiega: 'Per chiedere si comincia con can: can you…?',
      esempi: [['I can swim', 'so nuotare'], ['[can you] swim?', 'sai nuotare?']] },
    { id: 'can:no', titolo: 'Non so', prende: con(/\bcannot\b/),
      spiega: 'Per dire di no si scrive cannot, tutto attaccato.',
      esempi: [['I can fly', 'so volare'], ['I [cannot] fly', 'non so volare']] },
  ],

  /* ── In quarta ── */
  ora: [
    { id: 'ora:domanda', titolo: 'Che ore sono?', prende: domanda,
      spiega: '«Che ore sono?» si dice what time is it? Time vuol dire «ora», «tempo».',
      esempi: [['[what time] is it?', 'che ore sono?'], ['is it eight o\'clock?', 'sono le otto?']] },
    { id: 'ora:sono-le', titolo: 'Sono le sette',
      spiega: 'Sono le sette: it is seven o’clock. O’clock vuol dire «in punto», e va dopo il numero.',
      esempi: [['seven', 'sette'], ['it is seven [o\'clock]', 'sono le sette']] },
    { id: 'ora:alle', titolo: 'Alle sette', prende: con(/\bis at\b/),
      spiega: '«Alle sette» si dice at seven o’clock: at va prima dell’ora.',
      esempi: [['it is seven o\'clock', 'sono le sette'], ['lunch is [at] one o\'clock', 'il pranzo è all’una']] },
  ],
  presente: [
    { id: 'presente:gioco', titolo: 'Gioco ogni giorno',
      spiega: 'Per quello che fai di solito il verbo resta com’è: I play, we eat, they go.',
      esempi: [['play', 'giocare'], ['I [play] tennis every day', 'gioco a tennis ogni giorno']] },
    { id: 'presente:sempre', titolo: 'Sempre, mai, a volte', prende: con(/\b(always|never|sometimes)\b/),
      spiega: 'Always (sempre), never (mai) e sometimes (a volte) vanno prima del verbo.',
      esempi: [['I eat pasta', 'mangio la pasta'], ['I [always] eat pasta', 'mangio sempre la pasta']] },
    { id: 'presente:do', titolo: 'Giochi? Non gioco', prende: con(/^do\b|\bdo not\b/),
      spiega: 'Per chiedere si comincia con do: do you play? Per dire di no: I do not play.',
      esempi: [['[do] you play the piano?', 'suoni il pianoforte?'], ['I [do not] play the piano', 'non suono il pianoforte']] },
  ],
  'terza-s': [
    { id: 'terza-s:s', titolo: 'Lei gioca',
      spiega: 'Con he, she e con un nome il verbo prende la s: I play, she plays.',
      esempi: [['I [play] tennis', 'gioco a tennis'], ['she [plays] tennis', 'lei gioca a tennis']] },
    { id: 'terza-s:es', titolo: 'Va, lava, vola', prende: con(/\b(goes|washes|flies)\b/),
      spiega: 'Qualche verbo prende -es: go, goes; wash, washes. Fly, che finisce in y, diventa flies.',
      esempi: [['I [go] to bed', 'vado a letto'], ['he [goes] to bed', 'lui va a letto']] },
  ],
  does: [
    { id: 'does:domanda', titolo: 'Lui gioca?',
      spiega: 'Con he e she si chiede con does: does she play? Dopo does il verbo perde la s.',
      esempi: [['she plays', 'lei gioca'], ['[does] she [play]?', 'lei gioca?']] },
    { id: 'does:no', titolo: 'Lui non gioca', prende: con(/\bnot\b/),
      spiega: 'Per dire di no: does not, e il verbo senza s.',
      esempi: [['he plays', 'lui gioca'], ['he [does not play]', 'lui non gioca']] },
    { id: 'does:dove', titolo: 'Dove? Che cosa?', prende: con(/^(where|what)\b/),
      spiega: 'Where (dove) e what (che cosa) vanno prima di does.',
      esempi: [['does she eat?', 'lei mangia?'], ['[what] does she eat?', 'che cosa mangia lei?']] },
  ],
  ing: [
    { id: 'ing:adesso', titolo: 'Sto mangiando',
      spiega: 'Per quello che succede adesso: am, is o are, e il verbo con -ing.',
      esempi: [['I eat', 'mangio'], ['I [am eating]', 'sto mangiando']] },
    { id: 'ing:domanda', titolo: 'Stai mangiando?', prende: domanda,
      spiega: 'Per chiedere si gira: are va prima di you, is prima di he.',
      esempi: [['you are eating', 'stai mangiando'], ['[are you] eating?', 'stai mangiando?']] },
    { id: 'ing:no', titolo: 'Non sto dormendo', prende: con(/\bnot\b/),
      spiega: 'Per dire di no, not va dopo am, is o are.',
      esempi: [['I am sleeping', 'sto dormendo'], ['I am [not] sleeping', 'non sto dormendo']] },
  ],

  /* ── In quinta ── */
  'was-were': [
    { id: 'was-were:was', titolo: 'Ero, era',
      spiega: 'Al passato is e am diventano was: I was (ero), he was (era).',
      esempi: [['I am at the park', 'sono al parco'], ['I [was] at the park', 'ero al parco']] },
    { id: 'was-were:were', titolo: 'Eravamo, erano', prende: f => !f.domanda && /\bwere\b/.test(f.en),
      spiega: 'Al passato are diventa were: we were (eravamo), they were (erano).',
      esempi: [['we are at the zoo', 'siamo allo zoo'], ['we [were] at the zoo', 'eravamo allo zoo']] },
    { id: 'was-were:domanda', titolo: 'Eri?', prende: domanda,
      spiega: 'Per chiedere si gira, come al presente: were you…? was it…?',
      esempi: [['you were at school', 'eri a scuola'], ['[were you] at school?', 'eri a scuola?']] },
  ],
  passato: [
    { id: 'passato:went', titolo: 'Sono andato',
      spiega: 'Tanti verbi al passato cambiano forma: go diventa went, see diventa saw.',
      esempi: [['I [go] to the park', 'vado al parco'], ['I [went] to the park', 'sono andato al parco']] },
    { id: 'passato:did', titolo: 'Sei andato?', prende: con(/\bdid\b/),
      spiega: 'Per chiedere o dire di no si usa did, e il verbo torna com’è: did you go? I did not go.',
      esempi: [['I went', 'sono andato'], ['[did] you [go]?', 'sei andato?']] },
  ],
  'passato-ed': [
    { id: 'passato-ed:ed', titolo: 'Ho giocato',
      spiega: 'Al passato tanti verbi prendono -ed: play, played; cook, cooked.',
      esempi: [['I [play] tennis', 'gioco a tennis'], ['I [played] tennis', 'ho giocato a tennis']] },
    { id: 'passato-ed:did', titolo: 'Hai giocato?', prende: con(/\bdid\b/),
      spiega: 'Con did il verbo perde -ed: did you play? I did not play.',
      esempi: [['I played', 'ho giocato'], ['[did] you [play]?', 'hai giocato?']] },
  ],
  dire: [
    { id: 'dire:said', titolo: 'Ha detto',
      prende: con(/\b(said|say|says)\b/),
      spiega: 'Say è dire una cosa: she said hello. Al passato say diventa said.',
      esempi: [['she [says] hello', 'lei dice ciao'], ['she [said] hello', 'lei ha detto ciao']] },
    { id: 'dire:told', titolo: 'Mi ha detto',
      spiega: 'Tell è dire a qualcuno: dopo tell c’è sempre a chi (me, us). Al passato diventa told.',
      esempi: [['she said hello', 'lei ha detto ciao'], ['she [told me] her name', 'lei mi ha detto il suo nome']] },
  ],
  quando: [
    { id: 'quando:when', titolo: 'Quando',
      spiega: 'When vuol dire «quando». Dopo when c’è una frase intera: when it is cold.',
      esempi: [['it is cold', 'fa freddo'], ['[when] it is cold', 'quando fa freddo']] },
    { id: 'quando:while', titolo: 'Mentre', prende: con(/\bwhile\b/),
      spiega: 'While vuol dire «mentre»: due cose che succedono insieme.',
      esempi: [['I sing', 'canto'], ['I sing [while] I cook', 'canto mentre cucino']] },
  ],
  paragoni: [
    { id: 'paragoni:than', titolo: 'Più grande di', prende: con(/\bthan\b/),
      spiega: 'Più grande di: bigger than. Si aggiunge -er alla parola, e «di» si dice than.',
      esempi: [['the dog is [big]', 'il cane è grande'], ['the horse is [bigger than] the dog', 'il cavallo è più grande del cane']] },
    { id: 'paragoni:more', titolo: 'Le parole lunghe', prende: con(/\b(more|most)\b/),
      spiega: 'Le parole lunghe non prendono -er: si mette more prima, e most per «il più».',
      esempi: [['[more] beautiful', 'più bello'], ['the [most] beautiful', 'il più bello']] },
    { id: 'paragoni:est', titolo: 'Il più grande',
      spiega: 'Il più grande: the biggest. Si aggiunge -est alla parola, con the davanti.',
      esempi: [['[bigger]', 'più grande'], ['[the biggest]', 'il più grande']] },
  ],
  'going-to': [
    { id: 'going-to:faro', titolo: 'Farò',
      spiega: 'Per quello che farai: am, is o are, poi going to e il verbo com’è.',
      esempi: [['I swim', 'nuoto'], ['I [am going to] swim', 'nuoterò']] },
    { id: 'going-to:domanda', titolo: 'Farai? Non farò', prende: f => f.domanda || /\bnot\b/.test(f.en),
      spiega: 'Per chiedere si gira: are you going to…? Per dire di no: I am not going to…',
      esempi: [['[are you] going to swim?', 'nuoterai?'], ['I am [not] going to swim', 'non nuoterò']] },
  ],
}
