// Gli errori tipici, una riga per errore. Ogni riga dice quale operazione
// del motore (`fa`, in motore/trappole.js) la produce e con quali
// parametri (`con`), la forma che mette alla prova (`forma`; null = quella
// della frase), su cosa pesa uno sbaglio (`pesa`: 'forma' o 'parola') e il
// perché in una riga — sotto i 70 caratteri, con i buchi {…} riempiti
// dall'operazione. `esempio` è [giusta, sbagliata]: il test lo rifà.
// `soloForme`: la riga vale solo per le frasi di quelle forme (in/on è una
// cosa con i mesi e un'altra con i mobili).
// Un errore nuovo che somiglia a uno che c'è è una riga; uno di specie
// nuova è un'operazione nuova. Vedi docs/lingue/mondi.md.
// Le gemelle di grammatica: se la frase ne usa una, le altre sono le tessere
// di troppo che contano (I am / I is, my / your). Solo scambi che cambiano
// davvero la frase: niente this / it o a / the, che in italiano si somigliano.
export const GEMELLE = [
  ['am', 'is', 'are'], ['was', 'were'], ['have', 'has'], ['do', 'does'],
  ['my', 'your', 'his', 'her'], ['he', 'she', 'they'], ['a', 'an'],
  ['in', 'on', 'under', 'behind', 'near'], ['can', 'cannot'], ['there', 'here'],
]

export const TRAPPOLE = [
  { id: 'gira-domanda', fa: 'giraDomanda', forma: null,
    perche: 'Per chiedere, {verbo} va prima di {chi}: {verbo} {chi}…',
    esempio: ['is it a dog', 'it is a dog'] },
  { id: 'gira-affermazione', fa: 'giraAffermazione', forma: null,
    perche: 'Così è una domanda: per dirlo è {chi} {verbo}…',
    esempio: ['it is a dog', 'is it a dog'] },
  { id: 'do-mancante', fa: 'togliDo', forma: 'i-like',
    perche: 'Per chiedere ci vuole do davanti: do you like…?',
    esempio: ['do you like pizza', 'you like pizza'] },
  { id: 'accordo-be', fa: 'accordo', con: { verbi: 'be' }, forma: null,
    perche: 'Con {chi} si dice {giusto}, non {sbagliato}',
    esempio: ['I am happy', 'I is happy'] },
  { id: 'accordo-have', fa: 'accordo', con: { verbi: 'have' }, forma: null,
    perche: 'Con {chi} si dice {giusto} got, non {sbagliato} got',
    esempio: ['she has got a cat', 'she have got a cat'] },
  { id: 'soggetto-mancante', fa: 'togliSoggetto', forma: null,
    perche: 'In inglese {chi} non si lascia mai a casa',
    esempio: ['it is a dog', 'is a dog'] },
  { id: 'aggettivo-dopo', fa: 'aggettivoDopo', forma: 'colore-prima',
    perche: '{agg} va prima della cosa: {agg} {cosa}',
    esempio: ['it is a red fish', 'it is a fish red'] },
  { id: 'aggettivo-con-s', fa: 'aggettivoPlurale', forma: 'colore-prima',
    perche: '{agg} non prende mai la s: {agg} {cosa}',
    esempio: ['they are black cats', 'they are blacks cats'] },
  { id: 'plurale-senza-s', fa: 'pluraleSenzaS', forma: 'plurale',
    perche: 'Con {numero} ci vuole il plurale: {numero} {cosa}',
    esempio: ['they are two dogs', 'they are two dog'] },
  { id: 'a-an', fa: 'aDavantiVocale', forma: 'it-is',
    perche: 'Davanti a una vocale si dice an: an {cosa}',
    esempio: ['it is an elephant', 'it is a elephant'] },
  { id: 'the-generico', fa: 'theGenerico', forma: 'i-like',
    perche: 'Per le cose in generale niente the: like {cosa}',
    esempio: ['I like apples', 'I like the apples'] },
  { id: 'not-senza-do', fa: 'notSenzaDo', forma: 'i-like',
    perche: 'Per dire di no ci vuole do: I do not like',
    esempio: ['I do not like milk', 'I not like milk'] },
  { id: 'lui-lei', fa: 'scambia', forma: 'this-is-my',
    con: { coppie: [['he', 'she'], ['his', 'her']], it: [['lui', 'lei']],
           glossa: { he: 'lui', she: 'lei', his: 'suo (di lui)', her: 'suo (di lei)' } },
    perche: '{giusto} vuol dire {itGiusto}, {sbagliato} vuol dire {itSbagliato}',
    esempio: ['she is my sister', 'he is my sister'] },
  { id: 'mio-tuo', fa: 'scambia', forma: 'this-is-my',
    con: { coppie: [['my', 'your']], it: [['mio', 'tuo'], ['mia', 'tua'], ['miei', 'tuoi'], ['mie', 'tue']],
           glossa: { my: 'mio', your: 'tuo' } },
    perche: '{giusto} vuol dire {itGiusto}, {sbagliato} vuol dire {itSbagliato}',
    esempio: ['this is my dog', 'this is your dog'] },
  { id: 'negazione-tolta', fa: 'togliNegazione', forma: null,
    perche: 'Qui c’è not: la frase dice di no',
    esempio: ['I do not like milk', 'I like milk'] },
  { id: 'negazione-aggiunta', fa: 'aggiungiNegazione', forma: 'i-like',
    perche: 'Qui non c’è not: la frase dice di sì',
    esempio: ['I like milk', 'I do not like milk'] },
  { id: 'wh-ordine', fa: 'giraWh', forma: null,
    perche: 'Per chiedere, {verbo} va subito dopo {wh}: {wh} {verbo}…',
    esempio: ['where is the cat', 'where the cat is'] },
  { id: 'come-cosa', fa: 'scambia', forma: null,
    con: { coppie: [['how', 'what'], ['where', 'what']], glossa: { how: 'come', what: 'che cosa', where: 'dove' } },
    perche: '{giusto} vuol dire {itGiusto}, {sbagliato} vuol dire {itSbagliato}',
    esempio: ['how are you', 'what are you'] },
  { id: 'there-is-are', fa: 'thereAccordo', forma: 'there-is',
    perche: 'Per una cosa sola there is, per tante there are',
    esempio: ['there is a cat in the garden', 'there are a cat in the garden'] },
  { id: 'c-e', fa: 'thereInIt', forma: 'there-is',
    perche: 'C’è si dice there is: it is vuol dire «è»',
    esempio: ['there is a cat in the garden', 'it is a cat in the garden'] },
  { id: 'preposizioni', fa: 'scambia', forma: null, soloForme: ['dove', 'there-is'],
    con: { coppie: [['in', 'on'], ['on', 'under'], ['under', 'behind'], ['behind', 'near']],
           glossa: { in: 'dentro', on: 'sopra', under: 'sotto', behind: 'dietro', near: 'vicino' } },
    perche: '{giusto} vuol dire {itGiusto}, {sbagliato} vuol dire {itSbagliato}',
    esempio: ['the cat is under the bed', 'the cat is on the bed'] },
  { id: 'in-on-tempo', fa: 'scambia', forma: 'oggi', soloForme: ['oggi'],
    con: { coppie: [['in', 'on']], unVerso: true },
    perche: 'Con i mesi e le stagioni si dice in, con i giorni on',
    esempio: ['my birthday is in May', 'my birthday is on May'] },
  { id: 'parola-vicina', fa: 'parolaVicina', forma: null, pesa: 'parola',
    perche: '{giusto} vuol dire {itGiusto}, {sbagliato} vuol dire {itSbagliato}',
    esempio: ['it is a dog', 'it is a cat'] },

  /* ── dei mondi che hanno solo le parole: non trovano ancora frasi, ma si provano ── */
  { id: 'can-to', fa: 'inserisci', con: { dopo: ['can', 'cannot'], parola: 'to' }, forma: 'can',
    perche: 'Dopo can il verbo va da solo, senza to',
    esempio: ['I can swim', 'I can to swim'] },
  { id: 'terza-senza-s', fa: 'togliS', forma: 'terza-s',
    perche: 'Con {chi} il verbo prende la s: {chi} {verbo}',
    esempio: ['she plays football', 'she play football'] },
  { id: 'does-con-s', fa: 'sDopoDoes', forma: 'terza-s',
    perche: 'Dopo does il verbo va senza s: does {chi} {verbo}',
    esempio: ['does he like fish', 'does he likes fish'] },
  { id: 'passato-in-ed', fa: 'passatoInEd', forma: 'passato',
    con: { irregolari: { went: 'go', saw: 'see', ate: 'eat', ran: 'run', swam: 'swim',
                         had: 'have', made: 'make', came: 'come', drank: 'drink', sang: 'sing' } },
    perche: '{base} al passato fa {giusto}, non {sbagliato}',
    esempio: ['I went to school', 'I goed to school'] },
]

export const trappolaDi = id => TRAPPOLE.find(t => t.id === id) || null
