// Le frasi componibili del mondo «In quarta». Stesso formato di prima.js;
// i verbi flessi (plays, playing) valgono dalla tappa della loro struttura.
export default {
  mondo: 'quarta',
  frasi: [
    /* ── Che ore sono? (contratta) ── */
    { id: 'q-what-time', tappa: 'quarta-ora', forma: 'ora', it: 'che ore sono?', en: 'what time is it' },
    { id: 'q-seven-oclock', tappa: 'quarta-ora', forma: 'ora', it: 'sono le sette', en: 'it is seven o\'clock' },
    { id: 'q-is-it-eight', tappa: 'quarta-ora', forma: 'ora', it: 'sono le otto?', en: 'is it eight o\'clock' },
    { id: 'q-not-nine', tappa: 'quarta-ora', forma: 'ora', it: 'non sono le nove', en: 'it is not nine o\'clock' },
    { id: 'q-breakfast-seven', tappa: 'quarta-ora', forma: 'ora', it: 'la colazione è alle sette',
      en: 'breakfast is at seven o\'clock' },
    { id: 'q-lunch-one', tappa: 'quarta-ora', forma: 'ora', it: 'il pranzo è all’una', en: 'lunch is at one o\'clock' },
    { id: 'q-dinner-eight', tappa: 'quarta-ora', forma: 'ora', it: 'la cena è alle otto di sera',
      en: 'dinner is at eight o\'clock in the evening' },
    { id: 'q-three-afternoon', tappa: 'quarta-ora', forma: 'ora', it: 'sono le tre del pomeriggio',
      en: 'it is three o\'clock in the afternoon' },
    { id: 'q-ten-night', tappa: 'quarta-ora', forma: 'ora', it: 'sono le dieci di sera', en: 'it is ten o\'clock at night' },
    { id: 'q-what-time-lunch', tappa: 'quarta-ora', forma: 'ora', it: 'a che ora è il pranzo?', en: 'what time is lunch' },

    /* ── Gioco ogni giorno (contratta) ── */
    { id: 'q-play-every-day', tappa: 'quarta-io-gioco', forma: 'presente', it: 'gioco a tennis ogni giorno',
      en: 'I play tennis every day' },
    { id: 'q-pasta-lunch', tappa: 'quarta-io-gioco', forma: 'presente', it: 'a pranzo mangiamo sempre la pasta',
      en: 'we always eat pasta for lunch' },
    { id: 'q-never-milk', tappa: 'quarta-io-gioco', forma: 'presente', it: 'non bevo mai il latte',
      en: 'I never drink milk' },
    { id: 'q-play-piano', tappa: 'quarta-io-gioco', forma: 'presente', it: 'suoni il pianoforte?',
      en: 'do you play the piano' },
    { id: 'q-sometimes-cook', tappa: 'quarta-io-gioco', forma: 'presente', it: 'a volte cuciniamo la zuppa',
      en: 'we sometimes cook soup' },
    { id: 'q-go-to-bed', tappa: 'quarta-io-gioco', forma: 'presente', it: 'vanno a letto alle nove ogni sera',
      en: 'they go to bed at nine o\'clock every evening' },
    { id: 'q-not-music', tappa: 'quarta-io-gioco', forma: 'presente', it: 'la sera non ascolto la musica',
      en: 'I do not listen to music in the evening' },
    { id: 'q-wash-hands', tappa: 'quarta-io-gioco', forma: 'presente', it: 'mi lavo sempre le mani',
      en: 'I always wash my hands' },
    { id: 'q-help-mother', tappa: 'quarta-io-gioco', forma: 'presente', it: 'aiutano la loro mamma?',
      en: 'do they help their mother' },
    { id: 'q-play-guitar', tappa: 'quarta-io-gioco', forma: 'presente', it: 'suono la chitarra ogni giorno', en: 'I play the guitar every day' },

    /* ── Lei gioca ── */
    { id: 'q-she-plays', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'lei gioca a tennis', en: 'she plays tennis' },
    { id: 'q-brother-bed', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'mio fratello va a letto alle nove',
      en: 'my brother goes to bed at nine o\'clock' },
    { id: 'q-nurse-helps', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'l’infermiera aiuta il dottore',
      en: 'the nurse helps the doctor' },
    { id: 'q-firefighter-eats', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'il pompiere mangia una pizza',
      en: 'the firefighter eats a pizza' },
    { id: 'q-teacher-reads', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'la maestra legge un libro',
      en: 'the teacher reads a book' },
    { id: 'q-singer-sings', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'la cantante canta ogni sera',
      en: 'the singer sings every evening' },
    { id: 'q-pilot-flies', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'il pilota guida un aereo',
      en: 'the pilot flies a plane' },
    { id: 'q-cat-sleeps', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'il mio gatto dorme sul letto',
      en: 'my cat sleeps on the bed' },
    { id: 'q-laura-drinks', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'Laura beve il latte a colazione',
      en: 'Laura drinks milk for breakfast' },
    { id: 'q-he-washes', tappa: 'quarta-lei-gioca', forma: 'terza-s', it: 'lui si lava le mani',
      en: 'he washes his hands' },

    /* ── Lui gioca? ── */
    { id: 'q-does-she-play', tappa: 'quarta-does', forma: 'does', it: 'lei gioca a basket?',
      en: 'does she play basketball' },
    { id: 'q-doesnt-drink', tappa: 'quarta-does', forma: 'does', it: 'lui non beve il latte',
      en: 'he does not drink milk' },
    { id: 'q-sister-guitar', tappa: 'quarta-does', forma: 'does', it: 'tua sorella suona la chitarra?',
      en: 'does your sister play the guitar' },
    { id: 'q-dog-carrots', tappa: 'quarta-does', forma: 'does', it: 'il mio cane non mangia le carote',
      en: 'my dog does not eat carrots' },
    { id: 'q-pilot-sleep', tappa: 'quarta-does', forma: 'does', it: 'il pilota dorme sull’aereo?',
      en: 'does the pilot sleep on the plane' },
    { id: 'q-where-cat-sleep', tappa: 'quarta-does', forma: 'does', it: 'dove dorme il gatto?',
      en: 'where does the cat sleep' },
    { id: 'q-what-she-eat', tappa: 'quarta-does', forma: 'does', it: 'che cosa mangia lei a pranzo?',
      en: 'what does she eat for lunch' },
    { id: 'q-tom-not-listen', tappa: 'quarta-does', forma: 'does', it: 'Tom non ascolta la musica',
      en: 'Tom does not listen to music' },
    { id: 'q-help-father', tappa: 'quarta-does', forma: 'does', it: 'lui aiuta suo papà?',
      en: 'does he help his father' },
    { id: 'q-baby-night', tappa: 'quarta-does', forma: 'does', it: 'il bebè non dorme di notte',
      en: 'the baby does not sleep at night' },
    { id: 'q-what-dog-eat', tappa: 'quarta-does', forma: 'does', it: 'che cosa mangia il cane?', en: 'what does the dog eat' },

    /* ── Che cosa stai facendo? ── */
    { id: 'q-i-am-eating', tappa: 'quarta-adesso', forma: 'ing', it: 'sto mangiando', en: 'I am eating' },
    { id: 'q-she-sleeping', tappa: 'quarta-adesso', forma: 'ing', it: 'lei sta dormendo', en: 'she is sleeping' },
    { id: 'q-what-doing', tappa: 'quarta-adesso', forma: 'ing', it: 'che cosa stai facendo?',
      en: 'what are you doing' },
    { id: 'q-we-playing', tappa: 'quarta-adesso', forma: 'ing', it: 'stiamo giocando a basket',
      en: 'we are playing basketball' },
    { id: 'q-is-he-reading', tappa: 'quarta-adesso', forma: 'ing', it: 'lui sta leggendo?', en: 'is he reading' },
    { id: 'q-father-washing', tappa: 'quarta-adesso', forma: 'ing', it: 'mio papà sta lavando la macchina',
      en: 'my father is washing the car' },
    { id: 'q-leo-not-listening', tappa: 'quarta-adesso', forma: 'ing', it: 'Leo non sta ascoltando',
      en: 'Leo is not listening' },
    { id: 'q-cooking-dinner', tappa: 'quarta-adesso', forma: 'ing', it: 'stanno cucinando la cena',
      en: 'they are cooking dinner' },
    { id: 'q-drinking-juice', tappa: 'quarta-adesso', forma: 'ing', it: 'stai bevendo il succo?',
      en: 'are you drinking juice' },
    { id: 'q-helicopter-sky', tappa: 'quarta-adesso', forma: 'ing', it: 'un elicottero sta volando nel cielo',
      en: 'a helicopter is flying in the sky' },
    { id: 'q-not-sleeping', tappa: 'quarta-adesso', forma: 'ing', it: 'non sto dormendo', en: 'I am not sleeping' },
    { id: 'q-she-not-eating', tappa: 'quarta-adesso', forma: 'ing', it: 'lei non sta mangiando', en: 'she is not eating' },
  ],
}
