// Le frasi componibili del quinto mondo, «L'isola dei vulcani»: la strada,
// i soldi, di chi è. Stesso formato di prima.js. Il genitivo (Tom's) resta
// una parola sola: motore/testo.js espande 's solo dopo i pronomi.
export default {
  mondo: 'quinta',
  frasi: [
    /* ── Gira a sinistra (contratta) ── */
    { id: 'v-turn-left', tappa: 'quinta-gira', forma: 'strada', it: 'gira a sinistra', en: 'turn left',
      trappole: [{ en: 'turn right', it: 'gira a destra', perche: 'left vuol dire sinistra, right vuol dire destra' },
                 { en: 'left turn', perche: 'Per dare la strada il verbo va in testa: turn left' },
                 { en: 'turn at left', perche: 'A sinistra si dice solo left, senza at' }] },
    { id: 'v-turn-right-corner', tappa: 'quinta-gira', forma: 'strada', it: 'gira a destra all’angolo',
      en: 'turn right at the corner' },
    { id: 'v-go-straight', tappa: 'quinta-gira', forma: 'strada', it: 'vai dritto', en: 'go straight on' },
    { id: 'v-left-bank', tappa: 'quinta-gira', forma: 'strada', it: 'gira a sinistra alla banca',
      en: 'turn left at the bank' },
    { id: 'v-bank-next-school', tappa: 'quinta-gira', forma: 'strada', it: 'la banca è accanto alla scuola',
      en: 'the bank is next to the school' },
    { id: 'v-museum-opposite-park', tappa: 'quinta-gira', forma: 'strada', it: 'il museo è di fronte al parco',
      en: 'the museum is opposite the park' },
    { id: 'v-shop-between', tappa: 'quinta-gira', forma: 'strada', it: 'il negozio è fra la banca e il cinema',
      en: 'the shop is between the bank and the cinema' },
    { id: 'v-cinema-next-station', tappa: 'quinta-gira', forma: 'strada',
      it: 'il cinema è accanto alla stazione', en: 'the cinema is next to the station' },

    /* ── Quanto costa? (contratta) ── */
    { id: 'v-how-much-cake', tappa: 'quinta-quanto', forma: 'costa', it: 'quanto costa la torta?',
      en: 'how much is the cake' },
    { id: 'v-how-much-bike', tappa: 'quinta-quanto', forma: 'costa', it: 'quanto costa questa bicicletta?',
      en: 'how much is this bike' },
    { id: 'v-how-much-apples', tappa: 'quinta-quanto', forma: 'costa', it: 'quanto costano le mele?',
      en: 'how much are the apples' },
    { id: 'v-two-pounds', tappa: 'quinta-quanto', forma: 'costa', it: 'costa due sterline', en: 'it is two pounds' },
    { id: 'v-one-pound', tappa: 'quinta-quanto', forma: 'costa', it: 'il pane costa una sterlina',
      en: 'the bread is one pound' },
    { id: 'v-three-pounds', tappa: 'quinta-quanto', forma: 'costa', it: 'costano tre sterline',
      en: 'they are three pounds' },
    { id: 'v-bike-expensive', tappa: 'quinta-quanto', forma: 'costa', it: 'la bicicletta è cara',
      en: 'the bike is expensive' },
    { id: 'v-apples-cheap', tappa: 'quinta-quanto', forma: 'costa', it: 'le mele costano poco',
      en: 'the apples are cheap' },
    { id: 'v-hat-not-expensive', tappa: 'quinta-quanto', forma: 'costa', it: 'il cappello non è caro',
      en: 'the hat is not expensive' },

    /* ── Il cane di Tom (contratta) ── */
    { id: 'v-tom-dog', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'questo è il cane di Tom',
      en: 'this is Tom\'s dog' },
    { id: 'v-laura-bike', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'la bicicletta di Laura è rossa',
      en: 'Laura\'s bike is red' },
    { id: 'v-mother-car', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'la macchina della mamma è blu',
      en: 'my mother\'s car is blue' },
    { id: 'v-sister-cat', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'il gatto di mia sorella è nero',
      en: 'my sister\'s cat is black' },
    { id: 'v-leo-hat', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'questo è il cappello di Leo?',
      en: 'is this Leo\'s hat' },
    { id: 'v-brother-ball', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'la palla di mio fratello è nel parco',
      en: 'my brother\'s ball is in the park' },
    { id: 'v-pip-bed', tappa: 'quinta-di-chi', forma: 'genitivo', it: 'il letto di Pip è sotto il tavolo',
      en: 'Pip\'s bed is under the table' },
  ],
}
