// Le frasi componibili del sesto mondo, «Il castello tra le nuvole» (il
// passato, going to, i paragoni: oltre la primaria). Stesso formato di prima.js;
// i verbi al passato (went, played) e i paragoni (bigger) valgono dalla
// tappa della loro struttura. `niente: ['lui-lei']` dove l'italiano non dice
// chi fa la seconda cosa («quando ha visto»): he e she sarebbero giuste tutte e due.
export default {
  mondo: 'sesta',
  frasi: [
    /* ── Ieri ero al parco ── */
    { id: 'v-was-park', tappa: 'quinta-ieri', forma: 'was-were', it: 'ieri ero al parco',
      en: 'I was at the park yesterday' },
    { id: 'v-were-zoo', tappa: 'quinta-ieri', forma: 'was-were', it: 'eravamo allo zoo', en: 'we were at the zoo' },
    { id: 'v-was-cold', tappa: 'quinta-ieri', forma: 'was-were', it: 'ieri faceva freddo?', en: 'was it cold yesterday' },
    { id: 'v-museum-big', tappa: 'quinta-ieri', forma: 'was-were', it: 'il museo era grande', en: 'the museum was big' },
    { id: 'v-were-school', tappa: 'quinta-ieri', forma: 'was-were', it: 'ieri eri a scuola?',
      en: 'were you at school yesterday' },
    { id: 'v-mother-hospital', tappa: 'quinta-ieri', forma: 'was-were', it: 'mia mamma era all’ospedale',
      en: 'my mother was at the hospital' },
    { id: 'v-were-tired', tappa: 'quinta-ieri', forma: 'was-were', it: 'erano stanchi', en: 'they were tired' },
    { id: 'v-not-cinema', tappa: 'quinta-ieri', forma: 'was-were', it: 'non ero al cinema',
      en: 'I was not at the cinema' },
    { id: 'v-library-sunday', tappa: 'quinta-ieri', forma: 'was-were', it: 'domenica scorsa eravamo in biblioteca',
      en: 'we were at the library last Sunday' },
    { id: 'v-was-hot', tappa: 'quinta-ieri', forma: 'was-were', it: 'ieri faceva caldo', en: 'it was hot yesterday' },
    { id: 'v-were-they-zoo', tappa: 'quinta-ieri', forma: 'was-were', it: 'erano allo zoo?', en: 'were they at the zoo' },

    /* ── Sono andato al castello ── */
    { id: 'v-went-castle', tappa: 'quinta-andai', forma: 'passato', it: 'sono andato al castello',
      en: 'I went to the castle' },
    { id: 'v-saw-bird', tappa: 'quinta-andai', forma: 'passato', it: 'ho visto un uccello sul ponte',
      en: 'I saw a bird on the bridge' },
    { id: 'v-ate-pizza', tappa: 'quinta-andai', forma: 'passato', it: 'abbiamo mangiato la pizza al ristorante',
      en: 'we ate pizza at the restaurant' },
    { id: 'v-bought-apples', tappa: 'quinta-andai', forma: 'passato', it: 'lei ha comprato le mele al mercato',
      en: 'she bought apples at the market' },
    { id: 'v-did-you-go', tappa: 'quinta-andai', forma: 'passato', it: 'sei andato al museo?',
      en: 'did you go to the museum' },
    { id: 'v-found-ball', tappa: 'quinta-andai', forma: 'passato', it: 'Leo ha trovato una palla nel parco',
      en: 'Leo found a ball in the park' },
    { id: 'v-not-see-bridge', tappa: 'quinta-andai', forma: 'passato', it: 'non ho visto il ponte',
      en: 'I did not see the bridge' },
    { id: 'v-won-game', tappa: 'quinta-andai', forma: 'passato', it: 'abbiamo vinto la partita', en: 'we won the game' },
    { id: 'v-dog-caught', tappa: 'quinta-andai', forma: 'passato', it: 'il cane ha preso la palla',
      en: 'the dog caught the ball' },
    { id: 'v-came-train', tappa: 'quinta-andai', forma: 'passato', it: 'mia nonna è venuta in treno',
      en: 'my grandmother came by train' },
    { id: 'v-did-see-castle', tappa: 'quinta-andai', forma: 'passato', it: 'hai visto il castello?', en: 'did you see the castle' },

    /* ── Ho giocato ── */
    { id: 'v-played-tennis', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'ieri ho giocato a tennis',
      en: 'I played tennis yesterday' },
    { id: 'v-cooked-dinner', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'lei ha cucinato la cena',
      en: 'she cooked dinner' },
    { id: 'v-walked-village', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'abbiamo camminato fino al villaggio',
      en: 'we walked to the village' },
    { id: 'v-did-you-help', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'hai aiutato la tua mamma?',
      en: 'did you help your mother' },
    { id: 'v-listened-music', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'abbiamo ascoltato la musica',
      en: 'we listened to music' },
    { id: 'v-danced-garden', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'Laura ha ballato in giardino',
      en: 'Laura danced in the garden' },
    { id: 'v-not-play', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'Tom non ha giocato a basket',
      en: 'Tom did not play basketball' },
    { id: 'v-washed-car', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'mio papà ha lavato la macchina',
      en: 'my father washed the car' },
    { id: 'v-cat-jumped', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'il gatto è saltato sul tavolo',
      en: 'the cat jumped on the table' },
    { id: 'v-looked-bridge', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'abbiamo guardato il ponte',
      en: 'we looked at the bridge' },
    { id: 'v-did-play-tennis', tappa: 'quinta-giocai', forma: 'passato-ed', it: 'hai giocato a tennis?', en: 'did you play tennis' },

    /* ── Ha detto ciao (contratta) ── */
    { id: 'v-said-hello', tappa: 'quinta-disse', forma: 'dire', it: 'Leo ha detto ciao', en: 'Leo said hello' },
    { id: 'v-told-name', tappa: 'quinta-disse', forma: 'dire', it: 'lei mi ha detto il suo nome',
      en: 'she told me her name' },
    { id: 'v-what-say', tappa: 'quinta-disse', forma: 'dire', it: 'che cosa ha detto lui?', en: 'what did he say' },
    { id: 'v-said-yes', tappa: 'quinta-disse', forma: 'dire', it: 'lei ha detto di sì', en: 'she said yes' },
    { id: 'v-goodbye-teacher', tappa: 'quinta-disse', forma: 'dire', it: 'Tom ha detto arrivederci alla maestra',
      en: 'Tom said goodbye to the teacher' },
    { id: 'v-told-time', tappa: 'quinta-disse', forma: 'dire', it: 'mio papà ci ha detto l’ora',
      en: 'my father told us the time' },
    { id: 'v-tell-you-name', tappa: 'quinta-disse', forma: 'dire', it: 'lei ti ha detto il suo nome?',
      en: 'did she tell you her name' },
    { id: 'v-says-thank-you', tappa: 'quinta-disse', forma: 'dire', it: 'lui dice sempre grazie',
      en: 'he always says thank you' },
    { id: 'v-teacher-no', tappa: 'quinta-disse', forma: 'dire', it: 'la maestra ha detto di no',
      en: 'the teacher said no' },
    { id: 'v-goodbye-grandmother', tappa: 'quinta-disse', forma: 'dire', it: 'abbiamo detto arrivederci alla nonna',
      en: 'we said goodbye to our grandmother' },

    /* ── Quando fa freddo (contratta) ── */
    { id: 'v-when-cold', tappa: 'quinta-quando', forma: 'quando', it: 'quando fa freddo bevo il latte caldo',
      en: 'when it is cold I drink hot milk' },
    { id: 'v-happy-when', tappa: 'quinta-quando', forma: 'quando', it: 'ero felice quando ho trovato la mia palla',
      en: 'I was happy when I found my ball' },
    { id: 'v-when-birthday', tappa: 'quinta-quando', forma: 'quando', it: 'quando è il tuo compleanno?',
      en: 'when is your birthday' },
    { id: 'v-sing-while', tappa: 'quinta-quando', forma: 'quando', it: 'canto mentre cucino',
      en: 'I sing while I cook' },
    { id: 'v-cat-while', tappa: 'quinta-quando', forma: 'quando', it: 'il mio gatto dorme mentre io leggo',
      en: 'my cat sleeps while I read' },
    { id: 'v-when-tired', tappa: 'quinta-quando', forma: 'quando', it: 'quando sono stanco dormo',
      en: 'when I am tired I sleep' },
    { id: 'v-when-zoo', tappa: 'quinta-quando', forma: 'quando', it: 'quando sei andato allo zoo?',
      en: 'when did you go to the zoo' },
    { id: 'v-laughed-when', tappa: 'quinta-quando', forma: 'quando', it: 'mia sorella ha riso quando ha visto Pip',
      en: 'my sister laughed when she saw Pip', niente: ['lui-lei'] },
    { id: 'v-tom-laughs', tappa: 'quinta-quando', forma: 'quando', it: 'Tom ride quando gioca con Pip',
      en: 'Tom laughs when he plays with Pip', niente: ['lui-lei'] },
    { id: 'v-mother-sings-while', tappa: 'quinta-quando', forma: 'quando', it: 'la mamma canta mentre cucina', en: 'my mother sings while she cooks' },

    /* ── Chi è più alto? (contratta) ── */
    { id: 'v-horse-bigger', tappa: 'quinta-piu', forma: 'paragoni', it: 'il cavallo è più grande del cane',
      en: 'the horse is bigger than the dog' },
    { id: 'v-brother-taller', tappa: 'quinta-piu', forma: 'paragoni', it: 'mio fratello è più alto di me',
      en: 'my brother is taller than me' },
    { id: 'v-tallest-team', tappa: 'quinta-piu', forma: 'paragoni', it: 'Tom è il più alto della squadra',
      en: 'Tom is the tallest in the team' },
    { id: 'v-motorbike-faster', tappa: 'quinta-piu', forma: 'paragoni', it: 'la moto è più veloce della bici',
      en: 'the motorbike is faster than the bike' },
    { id: 'v-most-beautiful', tappa: 'quinta-piu', forma: 'paragoni', it: 'è il castello più bello',
      en: 'it is the most beautiful castle' },
    { id: 'v-more-difficult', tappa: 'quinta-piu', forma: 'paragoni', it: 'questo puzzle è più difficile',
      en: 'this puzzle is more difficult' },
    { id: 'v-cat-smaller', tappa: 'quinta-piu', forma: 'paragoni', it: 'il mio gatto è più piccolo del tuo cane',
      en: 'my cat is smaller than your dog' },
    { id: 'v-rocket-fastest', tappa: 'quinta-piu', forma: 'paragoni', it: 'il razzo è il più veloce',
      en: 'the rocket is the fastest' },
    { id: 'v-summer-hotter', tappa: 'quinta-piu', forma: 'paragoni', it: 'l’estate è più calda della primavera?',
      en: 'is summer hotter than spring' },
    { id: 'v-pip-funniest', tappa: 'quinta-piu', forma: 'paragoni', it: 'Pip è il cane più buffo',
      en: 'Pip is the funniest dog' },
    { id: 'v-castle-more-beautiful', tappa: 'quinta-piu', forma: 'paragoni', it: 'questo castello è più bello', en: 'this castle is more beautiful' },

    /* ── Domani andrò ── */
    { id: 'v-going-swim', tappa: 'quinta-domani', forma: 'going-to', it: 'domani vado a nuotare',
      en: 'I am going to swim tomorrow' },
    { id: 'v-going-buy', tappa: 'quinta-domani', forma: 'going-to', it: 'mia mamma comprerà il pane',
      en: 'my mother is going to buy bread' },
    { id: 'v-going-tennis', tappa: 'quinta-domani', forma: 'going-to', it: 'giocherai a tennis sabato?',
      en: 'are you going to play tennis on Saturday' },
    { id: 'v-going-castle', tappa: 'quinta-domani', forma: 'going-to', it: 'andremo a vedere il castello',
      en: 'we are going to see the castle' },
    { id: 'v-not-going-soup', tappa: 'quinta-domani', forma: 'going-to', it: 'non mangerò la zuppa',
      en: 'I am not going to eat the soup' },
    { id: 'v-tom-going-cook', tappa: 'quinta-domani', forma: 'going-to', it: 'Tom cucinerà la cena',
      en: 'Tom is going to cook dinner' },
    { id: 'v-going-win', tappa: 'quinta-domani', forma: 'going-to', it: 'vinceranno la partita',
      en: 'they are going to win the game' },
    { id: 'v-going-do', tappa: 'quinta-domani', forma: 'going-to', it: 'che cosa farai domani?',
      en: 'what are you going to do tomorrow' },
    { id: 'v-going-train', tappa: 'quinta-domani', forma: 'going-to', it: 'sabato prossimo prenderemo il treno',
      en: 'we are going to take the train next Saturday' },
    { id: 'v-is-tom-going-swim', tappa: 'quinta-domani', forma: 'going-to', it: 'Tom andrà a nuotare?', en: 'is Tom going to swim' },
  ],
}
