// Gli errori tipici di chi parla italiano e impara lo spagnolo, una riga per
// errore: da qui escono le frasi sbagliate di «scegli», l'italiano di «cosa
// vuol dire» e le tessere in più di «componi». Una riga nomina
// un'operazione di motore/trappole.js (`fa`, con i parametri in `con`) e dice
// il perché in una riga (sotto i 70 caratteri, a frase riempita), su quale
// struttura pesa lo sbaglio (`forma`, o quella della frase se null), dove
// vale (`soloForme`, `dallAnno`) e un `esempio` [giusta, sbagliata] che il
// test rifà (una domanda si scrive con ¿…?). Vedi docs/lingue/spagnolo-motore.md.

// Le gemelle di grammatica: le tessere di troppo che contano, perché
// scambiarle fa una frase sbagliata (es / son, un / una). Quelle dei verbi
// e degli aggettivi sono le altre forme della stessa parola che la tappa
// conosce (juego → juegas, jugar; negro → negra, negros: motore/formati.js).
// Niente coppie che danno una seconda frase giusta: en / sobre no, es / está
// nemmeno (el gato es negro, el gato está negro). La prima parola di una
// fila è quella a cui la fila appartiene.
export const GEMELLE = [
  ['es', 'son'], ['son', 'es'], ['soy', 'eres', 'es'], ['estoy', 'estás', 'está'], ['está', 'están', 'estoy'],
  ['tengo', 'tienes', 'tiene'], ['tiene', 'tienen', 'tenemos'], ['un', 'una', 'unos'], ['una', 'un', 'unas'],
  ['el', 'la', 'los', 'las'], ['la', 'el', 'las'], ['los', 'las', 'el'], ['las', 'los', 'la'],
  ['este', 'esta', 'estos'], ['esta', 'este', 'estas'], ['mi', 'mis', 'me'], ['mis', 'mi'], ['tu', 'tus', 'tú'],
  ['tus', 'tu'], ['su', 'sus'], ['sus', 'su'], ['sobre', 'debajo'], ['debajo', 'sobre'],
  ['gusta', 'gustan'], ['gustan', 'gusta'], ['me', 'mi', 'se'], ['te', 'ti', 'se'], ['hay', 'es', 'está'],
  ['voy', 'va', 'vamos'], ['va', 'voy', 'van'], ['al', 'a', 'el'], ['del', 'de', 'el'], ['a', 'en', 'al'],
  ['en', 'a'], ['cuesta', 'cuestan'], ['cuestan', 'cuesta'], ['más', 'menos'], ['mejor', 'peor'],
  ['que', 'de', 'qué'], ['cuando', 'mientras', 'cuándo'], ['mientras', 'cuando'], ['qué', 'que'],
  ['dónde', 'donde'], ['cómo', 'como'], ['él', 'el'], ['tú', 'tu'], ['hace', 'es'], ['muy', 'mucho'],
  ['mucho', 'muy', 'mucha'], ['estuve', 'fui'], ['fui', 'estuve'],
]

const PERSONA = 'Con {chi} si dice {giusto}, non {sbagliato}'
const PAROLA = '{giusto} è «{itGiusto}», {sbagliato} è «{itSbagliato}»'

export const TRAPPOLE = [
  /* ── la valle dei girasoli: genere, aggettivi, saluti ── */
  { id: 'un-una', fa: 'scambiaGenere', con: { famiglie: ['un'] }, forma: 'es-un',
    perche: '{cosa} è {genere}: {giusto} {cosa}, non {sbagliato} {cosa}',
    esempio: ['es un perro', 'es una perro'] },
  { id: 'el-la', fa: 'scambiaGenere', con: { famiglie: ['el'] }, forma: 'el-la',
    perche: '{cosa} è {genere}: {giusto} {cosa}, non {sbagliato} {cosa}',
    esempio: ['la vaca es blanca', 'el vaca es blanca'] },
  { id: 'el-agua', fa: 'elAgua', forma: 'el-la',
    perche: '{cosa} è femminile ma comincia con la a che si sente: {giusto} {cosa}',
    esempio: ['el agua está fría', 'la agua está fría'] },
  { id: 'aggettivo-genere', fa: 'aggettivoGenere', forma: 'color-despues',
    perche: '{cosa} è {genere}: {giusto}, non {sbagliato}',
    esempio: ['es una vaca negra', 'es una vaca negro'] },
  { id: 'aggettivo-numero', fa: 'aggettivoNumero', forma: 'color-despues',
    perche: 'Più cose: anche l’aggettivo va al plurale, {cosa} {giusto}',
    esempio: ['son dos gatos negros', 'son dos gatos negro'] },
  { id: 'aggettivo-prima', fa: 'aggettivoPrima', forma: 'color-despues',
    perche: 'Il colore va dopo la cosa: {cosa} {agg}',
    esempio: ['es un gato negro', 'es un negro gato'] },
  { id: 'este-esta', fa: 'scambiaGenere', con: { famiglie: ['este', 'ese'], pronome: true }, forma: 'este-esta',
    perche: '{cosa} è {genere}: {giusto}, non {sbagliato}',
    esempio: ['esta casa es grande', 'este casa es grande'] },
  { id: 'buenos-buenas', fa: 'aggettivoDavanti', con: { parole: ['bueno', 'buena', 'buenos', 'buenas'] },
    forma: 'saludos', perche: '{cosa} è {genere}: {giusto} {cosa}',
    esempio: ['buenos días', 'buenas días'] },
  { id: 'mi-me', fa: 'cliticoItaliano', con: { da: 'me', a: 'mi' }, forma: null,
    perche: 'Mi chiamo, mi piace: in spagnolo me (mi vuol dire «mio»)',
    esempio: ['me llamo Leo', 'mi llamo Leo'] },
  { id: 'te-ti', fa: 'cliticoItaliano', con: { da: 'te', a: 'ti' }, forma: null,
    perche: 'Ti chiami, ti piace: in spagnolo te, non ti',
    esempio: ['¿cómo te llamas?', '¿cómo ti llamas?'] },
  { id: 'tu-tú', fa: 'scambia', con: { coppie: [['tú', 'tu']] }, forma: null,
    perche: 'Tú con l’accento è «tu» che fai; tu senza è «tuo»',
    esempio: ['¿y tú?', '¿y tu?'] },

  /* ── la baia delle palme: plurali, gustar, mi tu su, ser, tener ── */
  { id: 'plurale-mancante', fa: 'pluraleMancante', forma: 'plural',
    perche: 'Dopo {prima} la cosa va al plurale: {giusto}',
    esempio: ['tengo dos perros', 'tengo dos perro'] },
  { id: 'plurale-in-piu', fa: 'pluraleInPiu', forma: 'plural',
    perche: 'Dopo {prima} la cosa è una sola: {giusto}',
    esempio: ['es un gato', 'es un gatos'] },
  { id: 'plurale-sbagliato', fa: 'pluraleStorto', forma: 'plural',
    perche: '{regola}: {giusto}',
    esempio: ['tengo dos lápices', 'tengo dos lápizes'] },
  { id: 'gustar-io', fa: 'gustarIo', forma: 'me-gusta',
    perche: 'Gustar va al rovescio, come «piacere»: {giusto}, non {sbagliato}',
    esempio: ['me gusta el pan', 'yo gusto el pan'] },
  { id: 'gusta-gustan', fa: 'gustaGustan', forma: 'me-gusta',
    perche: 'Una cosa sola: me gusta; più cose: me gustan',
    esempio: ['me gustan las uvas', 'me gusta las uvas'] },
  { id: 'mi-mis', fa: 'scambiaNumeroDet', con: { famiglie: ['mi', 'tu', 'su'] }, forma: 'mi-tu-su',
    perche: 'Una cosa: {sg} {cosa}; più cose: {pl}',
    esempio: ['son mis gatos', 'son mi gatos'] },
  { id: 'mio-tuo', fa: 'scambia', forma: 'mi-tu-su',
    con: { coppie: [['mi', 'tu'], ['mis', 'tus']], it: [['mio', 'tuo'], ['mia', 'tua'], ['miei', 'tuoi'], ['mie', 'tue']],
           glossa: { mi: 'mio', tu: 'tuo', mis: 'miei', tus: 'tuoi' } },
    perche: PAROLA, esempio: ['es mi perro', 'es tu perro'] },
  { id: 'lui-lei', fa: 'scambia', forma: null,
    con: { coppie: [['él', 'ella']], it: [['lui', 'lei']], glossa: { él: 'lui', ella: 'lei' }, riaccorda: true },
    perche: PAROLA, esempio: ['ella es alta', 'él es alto'] },
  { id: 'el-él', fa: 'scambia', con: { coppie: [['él', 'el']], unVerso: true }, forma: null, dallAnno: 2,
    perche: 'Él con l’accento è «lui»; el senza è «il»',
    esempio: ['él es alto', 'el es alto'] },
  { id: 'persona-ser', fa: 'personaSbagliata', con: { verbi: ['ser'] }, forma: 'ser',
    perche: PERSONA, esempio: ['yo soy alto', 'yo es alto'] },
  { id: 'tener-ser', fa: 'tenerSer', forma: 'tener',
    perche: 'Fame, sete, freddo e anni si «hanno»: {giusto}, non {sbagliato}',
    esempio: ['tengo siete años', 'soy siete años'] },
  { id: 'ho-he', fa: 'tenerHaber', forma: 'tener',
    perche: 'Avere una cosa si dice con tener: {giusto}, non {sbagliato}',
    esempio: ['tengo un perro', 'he un perro'] },
  { id: 'persona-tener', fa: 'personaSbagliata', con: { verbi: ['tener'] }, forma: 'tiene',
    perche: PERSONA, esempio: ['ella tiene un gato', 'ella tengo un gato'] },

  /* ── l'altopiano d'autunno: estar, hay, domande, giorni, tempo ── */
  { id: 'ser-al-posto-di-estar', fa: 'serAlPostoDiEstar', forma: null,
    perche: 'Dove sei e come stai si dice con estar: {giusto}, non {sbagliato}',
    esempio: ['el gato está en la mesa', 'el gato es en la mesa'] },
  { id: 'estar-al-posto-di-ser', fa: 'estarAlPostoDiSer', forma: 'ser-estar', dallAnno: 3,
    perche: 'Chi o che cosa è si dice con ser: {giusto}, non {sbagliato}',
    esempio: ['es un perro', 'está un perro'] },
  { id: 'en-a', fa: 'enInA', forma: 'esta-en',
    perche: 'Per stare in un posto si dice en: estoy en casa',
    esempio: ['estoy en casa', 'estoy a casa'] },
  { id: 'posto-scambiato', fa: 'scambiaPosto', forma: null, soloForme: ['esta-en', 'hay'],
    con: { coppie: [['sobre', 'debajo'], ['detrás', 'cerca']],
           glossa: { sobre: 'sopra', debajo: 'sotto', detrás: 'dietro', cerca: 'vicino' } },
    perche: PAROLA, esempio: ['el gato está sobre la mesa', 'el gato está debajo de la mesa'] },
  { id: 'hay-es', fa: 'hayEs', forma: 'hay',
    perche: '«C’è» e «ci sono» si dicono hay: non cambia mai',
    esempio: ['hay un gato en la mesa', 'es un gato en la mesa'] },
  { id: 'hay-el', fa: 'hayDeterminato', forma: 'hay',
    perche: 'Dopo hay niente el o la: hay {giusto} {cosa}',
    esempio: ['hay un gato en la cocina', 'hay el gato en la cocina'] },
  { id: 'accento-domanda', fa: 'togliAccento', forma: 'preguntas',
    con: { parole: ['qué', 'quién', 'cómo', 'dónde', 'cuándo', 'cuánto', 'cuánta', 'cuántos', 'cuántas', 'cuál'] },
    perche: 'Per chiedere si scrive con l’accento: {giusto}, non {sbagliato}',
    esempio: ['¿qué es?', '¿que es?'] },
  { id: 'accento-in-piu', fa: 'mettiAccento', forma: null, dallAnno: 3,
    con: { coppie: [['que', 'qué'], ['cuando', 'cuándo'], ['donde', 'dónde']] },
    perche: 'Senza domanda {giusto} non ha l’accento',
    esempio: ['es más alto que Leo', 'es más alto qué Leo'] },
  { id: 'parola-che-chiede', fa: 'scambia', forma: null,
    con: { coppie: [['qué', 'cómo'], ['dónde', 'cuándo'], ['quién', 'qué'], ['cómo', 'dónde']],
           it: [['che cosa', 'come'], ['dove', 'quando'], ['chi', 'che cosa'], ['come', 'dove']],
           glossa: { qué: 'che cosa', cómo: 'come', dónde: 'dove', cuándo: 'quando', quién: 'chi' } },
    perche: PAROLA, esempio: ['¿dónde está el gato?', '¿cuándo está el gato?'] },
  { id: 'giorno-con-en', fa: 'giornoConEn', forma: 'hoy-es',
    perche: 'Con i giorni basta el: el lunes, non en el lunes',
    esempio: ['el lunes juego', 'en el lunes juego'] },
  { id: 'oggi-domani', fa: 'scambia', forma: 'hoy-es', soloForme: ['hoy-es'],
    con: { coppie: [['hoy', 'mañana']], it: [['oggi', 'domani']], glossa: { hoy: 'oggi', mañana: 'domani' } },
    perche: PAROLA, esempio: ['hoy es lunes', 'mañana es lunes'] },
  { id: 'hace-es', fa: 'haceEs', forma: 'hace',
    perche: 'Il tempo si dice con hace: hace {cosa}, come «fa freddo»',
    esempio: ['hace frío', 'es frío'] },
  { id: 'muy-mucho', fa: 'muyMucho', forma: null,
    perche: 'Davanti a una cosa ({cosa}) si dice {giusto}, non muy',
    esempio: ['hace mucho frío', 'hace muy frío'] },

  /* ── il rifugio d'inverno: l'ora, il presente, le date, riflessivi, gerundio ── */
  { id: 'ora-es-son', fa: 'oraEsSon', forma: 'hora',
    perche: 'Es la una (una sola), son las dos, son las tres…',
    esempio: ['son las tres', 'es las tres'] },
  { id: 'ora-a-en', fa: 'oraEnA', forma: 'hora', soloForme: ['hora', 'fechas', 'reflexivos', 'presente-ar',
    'presente-er-ir'], perche: 'A che ora: a las siete, non en las siete',
    esempio: ['como a las siete', 'como en las siete'] },
  { id: 'persona-verbo', fa: 'personaSbagliata', con: { tranne: ['ser', 'tener'] }, forma: null, dallAnno: 4,
    perche: PERSONA, esempio: ['yo juego al tenis', 'yo juega al tenis'] },
  { id: 'desinenza-classe', fa: 'desinenzaClasse', forma: null, soloForme: ['presente-ar', 'presente-er-ir'],
    perche: '{base} è un verbo in -{classe}: {giusto}, non {sbagliato}',
    esempio: ['ella come pan', 'ella coma pan'] },
  { id: 'data-senza-de', fa: 'dataSenzaDe', forma: 'fechas',
    perche: 'Nelle date ci vuole de: el cinco de mayo',
    esempio: ['es el cinco de mayo', 'es el cinco mayo'] },
  { id: 'mese-con-el', fa: 'meseConEl', forma: 'fechas',
    perche: 'Con i mesi e le stagioni niente el: en {cosa}',
    esempio: ['en mayo hace calor', 'en el mayo hace calor'] },
  { id: 'mucho-accordo', fa: 'muchoAccordo', forma: 'cantidad',
    perche: 'Mucho e poco vanno d’accordo con la cosa: {giusto} {cosa}',
    esempio: ['hay mucha agua', 'hay mucho agua'] },
  { id: 'un-poco-de', fa: 'togliDe', con: { dopo: 'poco' }, forma: 'cantidad',
    perche: 'Un po’ di: un poco de, con de',
    esempio: ['quiero un poco de leche', 'quiero un poco leche'] },
  { id: 'riflessivo-mancante', fa: 'togliRiflessivo', con: { tranne: ['lavarse', 'sentarse'] }, forma: 'reflexivos',
    perche: '{base} vuole me, te, se davanti: {giusto}',
    esempio: ['me levanto a las siete', 'levanto a las siete'] },
  { id: 'riflessivo-persona', fa: 'riflessivoPersona', forma: 'reflexivos',
    perche: 'Io: me {verbo}; lui, lei: se. Qui ci vuole {giusto}',
    esempio: ['me levanto temprano', 'se levanto temprano'] },
  { id: 'gerundio-senza-estar', fa: 'gerundioSenzaEstar', forma: 'gerundio',
    perche: 'Adesso si dice con estar: {estar} {ger}',
    esempio: ['estoy jugando', 'jugando'] },
  { id: 'gerundio-infinito', fa: 'gerundioInfinito', forma: 'gerundio',
    perche: 'Dopo estar ci va -ando o -iendo: {estar} {giusto}',
    esempio: ['estoy comiendo', 'estoy comer'] },
  { id: 'gerundio-classe', fa: 'gerundioClasse', forma: 'gerundio',
    perche: '-ar fa -ando, -er e -ir fanno -iendo: {giusto}',
    esempio: ['está comiendo', 'está comando'] },

  /* ── la terra dei vulcani: ir, al e del, la strada, i soldi, querer e poder ── */
  { id: 'a-en', fa: 'aInEn', forma: 'voy-al',
    perche: 'Per andare verso un posto: voy a, non voy en',
    esempio: ['voy al parque', 'voy en el parque'] },
  { id: 'contrazione-a', fa: 'contrazioneMancante', con: { prep: 'a' }, forma: 'voy-al',
    perche: 'A + el si scrive al: al {cosa}',
    esempio: ['voy al parque', 'voy a el parque'] },
  { id: 'al-femminile', fa: 'contraiFemminile', con: { prep: 'a' }, forma: 'voy-al',
    perche: 'Al solo col maschile: a la {cosa}, non al {cosa}',
    esempio: ['voy a la escuela', 'voy al escuela'] },
  { id: 'contrazione-de', fa: 'contrazioneMancante', con: { prep: 'de' }, forma: 'de',
    perche: 'De + el si scrive del: del {cosa}',
    esempio: ['es el perro del niño', 'es el perro de el niño'] },
  { id: 'del-femminile', fa: 'contraiFemminile', con: { prep: 'de' }, forma: 'de',
    perche: 'Del solo col maschile: de la {cosa}, non del {cosa}',
    esempio: ['es el gato de la abuela', 'es el gato del abuela'] },
  { id: 'direzione-senza-la', fa: 'togliLa', con: { prima: ['izquierda', 'derecha'] }, forma: 'direcciones',
    perche: 'Si dice a la {cosa}, con la',
    esempio: ['gira a la izquierda', 'gira a izquierda'] },
  { id: 'al-lado-al', fa: 'alLadoAl', forma: 'direcciones',
    perche: 'Accanto a: al lado de (del, de la), non al lado a',
    esempio: ['está al lado del parque', 'está al lado al parque'] },
  { id: 'sinistra-destra', fa: 'scambia', forma: 'direcciones',
    con: { coppie: [['izquierda', 'derecha']], it: [['sinistra', 'destra']],
           glossa: { izquierda: 'sinistra', derecha: 'destra' } },
    perche: PAROLA, esempio: ['gira a la izquierda', 'gira a la derecha'] },
  { id: 'cuesta-cuestan', fa: 'cuestaCuestan', forma: 'cuanto',
    perche: 'Una cosa: cuesta; più cose: cuestan',
    esempio: ['¿cuánto cuesta el helado?', '¿cuánto cuestan el helado?'] },
  { id: 'costa', fa: 'costaCalco', forma: 'cuanto',
    perche: 'Costar cambia la vocale: {giusto}, non {sbagliato}',
    esempio: ['¿cuánto cuesta?', '¿cuánto costa?'] },
  { id: 'dittongo', fa: 'senzaDittongo', forma: 'quiero-puedo', dallAnno: 5,
    perche: '{base} cambia la vocale: {giusto}, non {sbagliato}',
    esempio: ['quiero un helado', 'quero un helado'] },
  { id: 'dittongo-in-piu', fa: 'dittongoInPiu', forma: 'quiero-puedo', dallAnno: 5,
    perche: 'Con nosotros la vocale non cambia: {giusto}',
    esempio: ['podemos jugar', 'puedemos jugar'] },
  { id: 'infinito-dopo-querer', fa: 'infinitoConiugato', con: { dopo: ['querer', 'poder'] }, forma: 'quiero-puedo',
    perche: 'Dopo {verbo} il verbo resta com’è: {verbo} {giusto}',
    esempio: ['quiero nadar', 'quiero nado'] },

  /* ── la città tra le nuvole: il passato, decir, cuando, ir a, i paragoni ── */
  { id: 'passato-al-presente', fa: 'passatoAlPresente', forma: null, dallAnno: 6,
    perche: 'È già successo: {giusto}, non {sbagliato}',
    esempio: ['ayer jugué al tenis', 'ayer juego al tenis'] },
  { id: 'estuve-fui', fa: 'estuveFui', forma: 'ayer',
    perche: 'Per dove eri si dice con estar: {giusto}, non {sbagliato}',
    esempio: ['ayer estuve en el parque', 'ayer fui en el parque'] },
  { id: 'passato-regolare', fa: 'passatoRegolare', con: { tranne: ['ser', 'ir', 'estar', 'dar', 'ver', 'decir'] },
    forma: 'pasado-irr', perche: '{base} al passato è irregolare: {giusto}, non {sbagliato}',
    esempio: ['ayer hice una torta', 'ayer hací una torta'] },
  { id: 'dijo-regolare', fa: 'passatoRegolare', con: { verbi: ['decir'] }, forma: 'decir',
    perche: 'Decir al passato cambia: {giusto}, non {sbagliato}',
    esempio: ['Leo dijo hola', 'Leo deció hola'] },
  { id: 'passato-accento', fa: 'passatoSenzaAccento', forma: 'pasado-reg',
    perche: 'Al passato l’accento conta: {giusto}, non {sbagliato}',
    esempio: ['ella comió pan', 'ella comio pan'] },
  { id: 'passato-ortografia', fa: 'passatoOrtografia', forma: 'pasado-reg',
    perche: 'Per tenere il suono si scrive {giusto}, non {sbagliato}',
    esempio: ['ayer jugué', 'ayer jugé'] },
  { id: 'cuando-mientras', fa: 'scambia', forma: 'cuando',
    con: { coppie: [['cuando', 'mientras']], it: [['quando', 'mentre']],
           glossa: { cuando: 'quando', mientras: 'mentre' } },
    perche: PAROLA, esempio: ['canto cuando cocino', 'canto mientras cocino'] },
  { id: 'voy-senza-a', fa: 'togliA', forma: 'voy-a',
    perche: 'Dopo ir ci vuole a: {ir} a {inf}',
    esempio: ['voy a nadar', 'voy nadar'] },
  { id: 'voy-a-gerundio', fa: 'irAGerundio', forma: 'voy-a',
    perche: 'Dopo {ir} a il verbo resta com’è: {ir} a {inf}',
    esempio: ['voy a nadar', 'voy a nadando'] },
  { id: 'mas-de', fa: 'masDe', forma: 'comparativos',
    perche: 'Più … di si dice más … que: más alto que',
    esempio: ['es más alto que Leo', 'es más alto de Leo'] },
  { id: 'mas-bueno', fa: 'masBueno', forma: 'comparativos',
    perche: 'Più buono si dice {giusto}, non {sbagliato}',
    esempio: ['es mejor', 'es más bueno'] },
  { id: 'mas-mejor', fa: 'masMejor', forma: 'comparativos',
    perche: '{giusto} vuol già dire «più»: niente más',
    esempio: ['es mejor', 'es más mejor'] },

  /* ── dappertutto ── */
  { id: 'negazione-tolta', fa: 'togliNegazione', forma: null,
    perche: 'Manca il «non»: no va prima del verbo',
    esempio: ['no me gusta el pan', 'me gusta el pan'] },
  { id: 'negazione-aggiunta', fa: 'aggiungiNegazione', forma: null,
    perche: 'Qui non c’è il «non»: niente no',
    esempio: ['me gusta el pan', 'no me gusta el pan'] },
  { id: 'parola-vicina', fa: 'parolaVicina', forma: null, pesa: 'parola',
    perche: PAROLA, esempio: ['es un gato', 'es un perro'] },
]
